// Auto-generated by RAG system on 2026-05-09
// Week 5 — do not edit the header

#import "../../template.typ": tip-box, warn-box, formula-box, cheat-box

== Woche 5: Big Data Analytics und Cloud Platforms

---

== 1. Big Data: Grundbegriffe und Definitionen

=== 1.1 Was ist Big Data?

*Kernidee:* Big Data bezeichnet Datenmengen, die mit herkömmlichen Methoden nicht mehr verarbeitet werden können — zu gross, zu komplex, zu schnelllebig oder zu schlecht strukturiert.

#tip-box[
*Woran erkenne ich eine Big-Data-Frage?*
- Aufgabe fragt nach Definition, Merkmalen oder Einordnung von Datenmengen
- Stichwörter: "4 V's", "5 V's", "Volume", "Velocity", "Variety", "Veracity", "Value"
- Frage: "Ist das Big Data?" → Einordnung in Small/Medium/Big
]

=== 1.2 Die 4 (bzw. 5) V's von Big Data

*Definition durch die vier Dimensionen:*

*Volume* — Datenmenge: Die schiere Grösse der Daten (Terabyte bis Petabyte).

*Variety* — Vielfalt: Strukturierte, semi-strukturierte und unstrukturierte Daten (Tabellen, JSON, Bilder, Videos, Sensordaten).

*Velocity* — Geschwindigkeit: Wie schnell Daten entstehen und verarbeitet werden müssen (Echtzeit-Streams, Batch).

*Veracity* — Wahrhaftigkeit/Qualität: Wie zuverlässig und korrekt die Daten sind (Rauschen, Fehler, Inkonsistenzen).

*Value* (seit 2015, 5. V) — Geschäftswert: Der Erkenntnisgewinn, der zu besseren Entscheidungen oder Profit führt.

#cheat-box[
*Entscheidungshilfe: Welches V ist gemeint?*
- Daten wachsen auf TB/PB → *Volume*
- Bilder + JSON + CSV gemischt → *Variety*
- Echtzeit-Sensorstream → *Velocity*
- Datenfehler, Rauschen → *Veracity*
- Nutzen für das Unternehmen → *Value*
]

=== 1.3 Small / Medium / Big Data (Keller, 2020)

Eine pragmatische Einteilung nach physikalischen Grenzen:

*Small Data:* Daten passen vollständig in den Arbeitsspeicher (RAM) eines einzelnen Rechners. Typische Tools: R, Python/Pandas DataFrames.

*Medium Data:* Daten passen auf die Festplatte eines einzelnen Laptops/Servers, aber nicht in den RAM. Typische Tools: Apache Spark (lokal), Python mit DuckDB.

*Big Data:* Daten passen weder in RAM noch auf die Disk eines einzelnen Rechners. Verlangen nach *verteilten Systemen* (Distributed Systems).

#warn-box[
*Häufiger Denkfehler: "Alles ist Big Data"*
Jordan Tigani ("Big Data is Dead", 2023) zeigt: Die meisten Daten sind kleiner als 100 GB. Nicht jedes Datenproblem braucht ein verteiltes System. Zuerst prüfen: Passt es in RAM? → Small Data reicht. Passt es auf Disk? → Medium Data-Tools (DuckDB, Spark lokal) reichen. Nur wenn nicht: verteilte Systeme.
]

=== 1.4 Big Data-Lösungsansätze: Scale Up vs. Scale Out

*Lösungsansatz 1 — Scaling Up (vertikal):*
Mehr RAM, schnellere CPUs in einem einzelnen Rechner.
→ Technologie: *In-Memory Column Stores*

*Lösungsansatz 2 — Scaling Out (horizontal):*
Viele normale Rechner zusammenschalten ("Shared Nothing"-Architektur mit Parallel Processing).
→ Technologie: *Verteilte Systeme* (MapReduce, Apache Spark)

---

== 2. Analytical Processing-Technologien

=== 2.1 Column Stores (Spaltenorientierte DBMS)

*Kernidee:* Statt Daten zeilenweise zu speichern (wie in klassischen OLTP-Datenbanken), werden sie spaltenweise abgelegt — das ermöglicht enorme Lese-Performance bei analytischen Abfragen.

*Vergleich Row Store vs. Column Store:*

- *Row Store:* Alle Attribute einer Zeile liegen zusammen auf Disk. Gut für: `SELECT * FROM t WHERE id = 5` (einzelner Datensatz).
- *Column Store:* Alle Werte einer Spalte liegen zusammen. Gut für: `SELECT AVG(preis) FROM verkauf` (aggregieren über viele Zeilen, wenige Spalten).

*Vorteile Column Store:*
- Schnelle OLAP-Lese-Anfragen (10 bis 100× schneller als Row Stores)
- Bessere Komprimierung pro Spalte (gleiche Werte → Run-Length-Encoding etc.)
- Bessere Indexierung möglich

*Nachteile Column Store:*
- Langsame Updates (alle Spalten-Dateien müssen geändert werden)
- Nicht geeignet für write-heavy OLTP-Workloads

=== 2.2 In-Memory Stores

*Kernidee:* Das DBMS nutzt ausschliesslich den Arbeitsspeicher als Datenspeicher — kein Disk-I/O bei Abfragen, daher extrem schnell.

*Problem:* Persistenz! RAM ist flüchtig.
*Lösungen:*
- Logisches Write-Ahead-Log (WAL) auf Disk schreiben
- Snapshots ("eventuelle Persistenz")

*Oft kombiniert:* In-Memory + Column Store zusammen = maximale OLAP-Performance.

#cheat-box[
*Bekannte Systeme (Auswahl):*
- *SAP HANA* — Spaltenorientiert, In-Memory (min. ~500 GB RAM)
- *Oracle 12+* — In-Memory-Erweiterung spaltenorientiert
- *MS SQL Server* — Spaltenorientierte Erweiterung (nicht In-Memory)
- *PostgreSQL* — Erweiterungen: pg_duckdb, Citus, TimescaleDB
- *DuckDB* — Spaltenorientiert, In-Process, Open Source (kann über RAM hinaus skalieren)
]

=== 2.3 Weitere Query-Optimierungen

*Materialized Views:* Vorberechnete Abfrageergebnisse als eigene Struktur gespeichert (Caching auf Abfrageebene).

*Bitmap-Indexe:* Besonders geeignet für Data Warehouses mit niedrig-kardinalem Spalten (z.B. Geschlecht, Status). Jeder Wert bekommt ein Bit-Array über alle Zeilen.

*Parallel Query Processing:* Nutzung mehrerer CPU-Kerne oder GPUs gleichzeitig.

*Volcano Style vs. Vectorized Style:*

*Volcano Style (Tupel-at-a-Time):*
- Jede Operation verarbeitet ein Tupel vollständig, bevor das nächste kommt
- Einfach zu implementieren
- Overhead: viele Funktionsaufrufe und Kontextwechsel

*Vectorized Style (Batch-Verarbeitung):*
- Verarbeitet Daten in Batches (Arrays/Vektoren von Werten)
- Passt natürlich zu Column Stores
- Weniger Funktionsaufrufe → weniger Overhead
- Nutzt moderne CPU-Architekturen: *SIMD (Single Instruction, Multiple Data)* — eine CPU-Instruktion auf viele Datenwerte gleichzeitig angewendet

#warn-box[
*Achtung: Verwechslungsgefahr*
"Vectorized Processing" hat *nichts* mit "Vector Stores" (für AI/Embeddings bei ChatGPT) zu tun! Es geht um CPU-effiziente Batch-Verarbeitung von Spalten-Arrays.
]

---

== 3. Überblick: Data Processing Tools

#formula-box[
*Entscheidungsrahmen: Welches Tool für welche Datengrösse?*

1. Daten passen in RAM → *Pandas* (einfach, eager), *Polars* (schnell, lazy+eager), *DuckDB* (SQL, in-process)
2. Daten passen nicht in RAM, aber auf einen Rechner → *DuckDB* (skaliert über RAM), *Dask/Modin* (Pandas-API, erweiterbar)
3. Daten brauchen Cluster → *Apache Spark* (Batch+Streaming), *Apache Flink* (Stream-first)
4. Cloud-Managed → *Databricks* (Spark-basiert), *Snowflake*, *BigQuery* (Google), *Redshift* (AWS)
]

*Vergleichstabelle der wichtigsten Eigenschaften:*

#tip-box[
*Relationale Tabelle vs. Pandas vs. Polars vs. DuckDB — Erkennungsmerkmale:*
- *Schema:* Relationale DB und DuckDB strikt vorab definiert; Pandas inferiert und änderbar; Polars strikt und unveränderlich
- *Auswertung:* Relationale DB und DuckDB deklarativ (SQL); Pandas eager (sofort); Polars lazy + eager
- *Parallelität:* Pandas single-thread; Polars, DuckDB, relationale DB multi-thread
- *Fehlende Werte:* SQL/DuckDB → NULL; Pandas → NaN/None; Polars → Null (typisiert)
- *Skalierung:* Pandas RAM-limitiert; DuckDB skaliert über RAM; Relationale DB vertikal/horizontal
]

---

== 4. MapReduce

=== 4.1 Grundidee und Herkunft

*Kernidee:* MapReduce ist ein einfaches, funktionales Programmiermodell für die verteilte Verarbeitung sehr grosser Datenmengen auf vielen Standard-Rechnern.

Ursprung: Google (Dean & Ghemawat, 2004). Später: Apache Hadoop-Implementierung.

=== 4.2 Die drei Phasen

*Map-Phase:*
- Eingabe: Schlüssel/Wert-Paare (key/value pairs)
- Ausgabe: Zwischen-Schlüssel/Wert-Paare (intermediate key/value pairs)
- Jeder Map-Worker verarbeitet einen Teil der Eingabe unabhängig

*Shuffle/Partition-Phase:*
- Zwischen-Paare werden nach Schlüssel gruppiert
- Standard-Partitionierung: $"hash"("key") mod N$ (wobei $N$ = Anzahl Reducer)
- Ziel: Gleiche Schlüssel landen beim selben Reducer

*Reduce-Phase:*
- Eingabe: Ein Schlüssel + alle zugehörigen Zwischenwerte
- Ausgabe: Aggregiertes Ergebnis (z.B. Summe, Anzahl)
- Fasse alle Zwischenwerte mit demselben Schlüssel zusammen

#formula-box[
*MapReduce-Rezept: Wörter zählen (Word Count)*

Aufgabe: Zähle wie oft jedes Wort in einem grossen Textkorpus vorkommt.

1. *Map:* Für jedes Wort $w$ im Input → emittiere $(w, 1)$
   - Eingabe: `"the cat and the dog"` → Ausgabe: `[("the",1), ("cat",1), ("and",1), ("the",1), ("dog",1)]`

2. *Shuffle:* Gruppiere nach Schlüssel
   - `"the"` → $[1, 1]$; `"cat"` → $[1]$; `"and"` → $[1]$; `"dog"` → $[1]$

3. *Reduce:* Summiere die Werte pro Schlüssel
   - `"the"` → $2$; `"cat"` → $1$; `"and"` → $1$; `"dog"` → $1$

*Allgemeines Muster:* Map emittiert $(k, v)$-Paare; Reduce aggregiert alle $v$ mit gleichem $k$.
]

=== 4.3 Vor- und Nachteile MapReduce

*Vorteile:*
- Einfaches Programmiermodell
- Automatische Parallelisierung und Fehlerbehandlung
- Läuft auf vielen Standard-Rechnern (commodity hardware)
- Hohe Verfügbarkeit

*Nachteile:*
- *Master ist Single Point of Failure* und Skalierungsengpass
- Latenz beim Öffnen von tausenden Dateien (disk-intensiv)
- Nicht geeignet für Echtzeit-Verarbeitung
- Inzwischen durch Apache Spark weitgehend ersetzt

#cheat-box[
*MapReduce heute noch relevant für:*
- Massive Batch-Jobs (Petabyte-Verarbeitung)
- Log-Analysen
- Verteilte Berechnungen ohne Echtzeitanforderung
*Nicht geeignet für:* iterative Algorithmen (ML), interaktive Abfragen, Streaming
]

---

== 5. Apache Spark

=== 5.1 Was ist Apache Spark?

*Kernidee:* Apache Spark ist ein Open-Source Framework für verteilte Datenverarbeitung, das durch *In-Memory Computing* 10–100× schneller als Hadoop MapReduce ist.

*Stärken von Spark:*
- *Iterative Programme* (Machine Learning) — Daten bleiben im RAM, kein wiederholtes Disk-Lesen
- *Interaktive Abfragen* — schnelles Explorieren grosser Daten
- *Unified Engine* — Batch + Streaming + SQL + ML + Graph in einem Framework

=== 5.2 Spark-Architektur

*Driver-Prozess:* Zentrales Steuerelement. Koordiniert alle Aufgaben, erstellt den Execution Plan, verteilt Arbeit an Executors.

*Executors (Worker Nodes):* Führen die eigentlichen Berechnungen aus. Verarbeiten Partitionen der Daten parallel.

*Ressourcenmanagement:* Primär über *Kubernetes (K8s)*; früher auch YARN/Mesos.

*Catalyst Optimizer:* Spark's interner Query-Optimierer. Analysiert den logischen Plan und erzeugt einen optimierten physischen Ausführungsplan.

*Separation of Compute & Storage:* Rechenleistung von Speicher getrennt. Storage in Objektspeichern (AWS S3, Azure ADLS) oder Lakehouse-Formaten (Delta Lake, Apache Iceberg).

=== 5.3 Spark-Komponenten

*Spark SQL:*
- SQL-Abfragen direkt auf Spark-Daten
- JDBC-API für BI-Tools
- ETL aus verschiedenen Formaten
- Aufruf: `spark.sql("SELECT ...")`

*Unterstützte Datenformate:*
- *Parquet* — spaltenorientiertes Dateiformat (bevorzugt für Analytics)
- JSON, Protobuf, Avro, ORC (ebenfalls column-based wie Parquet)

*DataFrame/Dataset-API:*
- Unified API seit Spark 2.0
- `Dataset[T]` (Scala/Java) mit Compile-Zeit-Typsicherheit
- DataFrame = Dataset ohne Typsicherheit (Python/R)

=== 5.4 Spark DataFrames — Kernkonzepte

*Immutabilität:* DataFrames sind unveränderlich. Jede Transformation erzeugt einen *neuen* DataFrame. Der ursprüngliche bleibt unberührt.

*Lazy Evaluation:* Transformationen (z.B. `filter()`, `select()`, `groupBy()`) werden *nicht sofort ausgeführt*, sondern als DAG (Directed Acyclic Graph) von Operationen gespeichert. Ausführung erst bei einer *Action*.

*Actions* lösen die Ausführung aus:
- `show()` — erste N Zeilen anzeigen
- `collect()` — alle Daten zum Driver bringen
- `count()` — Anzahl Zeilen zählen
- `write()` — Ergebnis speichern

*Partitionierung:* DataFrames sind intern in Partitionen aufgeteilt, die parallel auf dem Cluster verarbeitet werden.
- `repartition(n)` — Neupartitionierung auf $n$ Partitionen (shuffle)
- `coalesce(n)` — Reduziert Partitionen ohne shuffle (effizienter)

#warn-box[
*Häufiger Denkfehler: Pandas ≠ Spark DataFrames*
"DataFrame" ist ein *Konzept* (strukturierte Tabelle mit Schema). Pandas und Spark *implementieren* dieses Konzept unterschiedlich:
- Pandas: eager, single-machine, mutable, RAM-limitiert
- Spark: lazy, distributed, immutable, cluster-skalierbar
Der Code sieht ähnlich aus, aber das Verhalten ist fundamental verschieden!
]

=== 5.5 PySpark — Praxis-Rezept

#formula-box[
*PySpark Session starten und DataFrame erstellen*

```python
from pyspark.sql import SparkSession

# 1. SparkSession erstellen (Entry Point)
spark = SparkSession.builder \
    .appName("MeinProjekt") \
    .getOrCreate()

# 2. DataFrame aus Python-Liste erstellen
data = [(1, "Alice", 85), (2, "Bob", 92)]
df = spark.createDataFrame(data, ["ID", "Name", "Score"])

# 3. DataFrame anzeigen (Action!)
df.show()

# 4. SQL: Temporäre View registrieren
df.createOrReplaceTempView("studenten")
result = spark.sql("SELECT Name, Score FROM studenten WHERE Score > 90")
result.show()

# 5. DataFrame-API verwenden
from pyspark.sql.functions import col, avg
df.filter(col("Score") > 80) \
  .groupBy("Name") \
  .agg(avg("Score").alias("Durchschnitt")) \
  .show()
```

*Schritte allgemein:*
1. `SparkSession` erstellen
2. Daten laden (CSV, Parquet, Datenbank, Python-Liste)
3. Transformationen definieren (lazy)
4. Action aufrufen → Ausführung
5. Ergebnis anzeigen oder speichern
]

=== 5.6 Spark SQL vs. DataFrame-API

#tip-box[
*Wann Spark SQL, wann DataFrame-API?*
- *Spark SQL:* Wenn du komplexe SQL-Abfragen kennst; gut für ad-hoc Exploration; `spark.sql("SELECT ...")`
- *DataFrame-API:* Wenn du programmatisch transformieren willst; besser für ML-Pipelines; `df.filter(...).groupBy(...)`
- *Beide sind funktional äquivalent!* Der Catalyst Optimizer optimiert beide gleich.
]

=== 5.7 Spark vs. Hadoop MapReduce

| Merkmal | Hadoop MapReduce | Apache Spark |
|---|---|---|
| Speicher | Disk-basiert | In-Memory |
| Geschwindigkeit | Langsam (Disk-I/O) | 10-100× schneller |
| Echtzeit | Nein | Ja (Streaming) |
| ML/Iterativ | Schlecht | Gut |
| API | Java-only | Scala, Java, Python, R |
| Zustand | Legacy | Aktuell Standard |

---

== 6. Cloud Computing und Cloud Platforms

=== 6.1 Definition Cloud Computing

*NIST-Definition:* Ein Modell für den bequemen, bedarfsorientierten Netzzugang zu einem gemeinsam genutzten Pool konfigurierbarer Rechenressourcen (Netze, Server, Speicher, Anwendungen, Dienste), die mit minimalem Verwaltungsaufwand schnell bereitgestellt und freigegeben werden können.

*Kernprinzip:* *Elastizität* — Ressourcen nach Bedarf hochfahren und wieder freigeben. Zahlen nur für das, was genutzt wird.

=== 6.2 Historische Entwicklung Cloud & Datenbanken

- *2003–2006:* Google-Paper (GFS, MapReduce, Bigtable) → Grundlage von Hadoop; AWS-Gründung
- *2007–2010:* NoSQL-"Revolution", CAP-Theorem, erste DBaaS (Amazon RDS)
- *2010–2015:* Cloud Data Warehouses (Redshift, BigQuery), Apache Spark
- *2015–2019:* Compute/Storage-Trennung als Architekturprinzip, Snowflake, Serverless, HTAP
- *2019–2022:* Data Lakehouse, Open Formats (Apache Iceberg, Delta Lake), Data Mesh
- *2022–2024:* Vector Databases, RAG, Edge-DBs, AI-Integration
- *2025+:* Rückkehr zu On-Premises?

*Fazit der Geschichte:* SQL wurde mehrfach totgesagt und lebt jedes Mal stärker wieder auf. Die eigentliche Revolution war die *Trennung von Compute und Storage* als Architekturprinzip.

=== 6.3 Technologischer Wandel seit 2000

- *"RAM is King":* Arbeitsspeicher ist die primäre Datenquelle; Festplatte = Fallback
- Netzwerk-Durchsatz wird kontinuierlich besser
- Multi-Core CPUs sind Commodity (normale Ware)
- Volume *und* Velocity werden immer wichtiger

=== 6.4 Wichtige Cloud Platforms

*Grosse Anbieter:*
- *Amazon Web Services (AWS)* — Marktführer
- *Microsoft Azure* — starke Enterprise-Präsenz
- *Google Cloud Platform (GCP)* — ML/AI-Stärken, BigQuery
- *Google Earth Engine (GEE)* — Geo/Raster-Analyse

*Spezialisierte Plattformen:*
- *Databricks* — kommerzielle Plattform auf Apache Spark
- *Snowflake* — kommerzielles Cloud Data Warehouse
- *Google BigQuery* — serverless, columnar, Google Cloud
- *Amazon Redshift* — AWS Data Warehouse, columnar
- *ClickHouse* — Open Source, columnar

=== 6.5 Cloud vs. On-Premises: Vor- und Nachteile

#formula-box[
*Entscheidungsrahmen Cloud vs. On-Prem*

*Vorteile Cloud gegenüber On-Premises:*
1. Skalierbarkeit und Flexibilität (elastisch)
2. Geringere Initialkosten (kein Hardware-Kauf)
3. Schnelles Prototyping (hochfahren, testen, wegwerfen)
4. Weniger IT-spezialisiertes Personal nötig
5. Grosse Unternehmen: erzwingt Modernisierung von Architektur und Prozessen

*Nachteile Cloud gegenüber On-Premises:*
1. Man muss sich trotz Werbung weiterhin um Technik, Integration und Betrieb kümmern
2. Verlust physischer Kontrolle über Daten
3. Datenschutz-Risiken (GDPR-Compliance schwerer sicherzustellen)
4. "Lift and Shift" ist kurzfristig günstiger, langfristig aber teurer (Cloud-native Anpassungen nötig)
5. Fehlende Standards für Daten-Migration zwischen Cloud-Anbietern
6. *Vendor Lock-in* — Abhängigkeit vom Cloud-Anbieter
]

#warn-box[
*Häufiger Denkfehler: "Cloud = kein Aufwand"*
Die Cloud-Werbung suggeriert, man müsse sich um nichts kümmern. In der Praxis: Technik, Integration, Sicherheit und Betrieb bleiben Aufgaben des Nutzers. Nur die Hardware-Verwaltung entfällt.

*Häufiger Denkfehler: "Lift and Shift spart langfristig Geld"*
Schnelle Migration in die Cloud ("Lift and Shift") ist anfangs günstig, aber ohne Anpassung an Cloud-native Prinzipien (z.B. AWS Lambda, Container) nutzt man die Cloud-Vorteile nicht aus — und zahlt mehr als nötig.
]

#cheat-box[
*Wann Cloud, wann On-Prem?*
- Prototyping, schnell starten → *Cloud*
- Sensible Daten, GDPR-kritisch → *On-Prem* bevorzugen
- Unregelmässige Lastspitzen → *Cloud* (Elastizität)
- Stabile, vorhersagbare Last → *On-Prem* oft günstiger
- Startup ohne IT-Team → *Cloud*
- Multi-Cloud oder Wechsel geplant → *Vendor Lock-in* beachten!

*Die Kernfrage ist nicht Cloud vs. On-Prem, sondern:*
_die richtige Workload am richtigen Ort_ — das ist die eigentliche Kernkompetenz im modernen Data Engineering.
]

---

== 7. PySpark Praxis: Vollständiges Lösungsrezept für Übungsaufgaben

#formula-box[
*Allgemeines Rezept für PySpark-Aufgaben (Databricks)*

*Schritt 1: Umgebung aufsetzen*
```python
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("Aufgabe").getOrCreate()
```
In Databricks ist die SparkSession oft schon als `spark` vorhanden.

*Schritt 2: Daten laden*
```python
# CSV laden
df = spark.read.format("csv") \
    .option("header", "true") \
    .option("inferSchema", "true") \
    .load("/pfad/zur/datei.csv")

# Parquet laden
df = spark.read.parquet("/pfad/zur/datei.parquet")
```

*Schritt 3: Daten erkunden*
```python
df.printSchema()        # Schema anzeigen
df.show(5)              # erste 5 Zeilen
df.count()              # Anzahl Zeilen
df.describe().show()    # Statistiken
```

*Schritt 4a: Abfragen mit Spark SQL*
```python
df.createOrReplaceTempView("meine_tabelle")
result = spark.sql("""
    SELECT spalte1, COUNT(*) as anzahl
    FROM meine_tabelle
    WHERE spalte2 > 100
    GROUP BY spalte1
    ORDER BY anzahl DESC
""")
result.show()
```

*Schritt 4b: Abfragen mit DataFrame-API*
```python
from pyspark.sql.functions import col, count, avg, desc

result = df \
    .filter(col("spalte2") > 100) \
    .groupBy("spalte1") \
    .agg(count("*").alias("anzahl")) \
    .orderBy(desc("anzahl"))

result.show()
```

*Schritt 5: Ergebnis speichern (optional)*
```python
result.write.format("parquet").save("/ausgabe/pfad")
```
]

#tip-box[
*Woran erkenne ich, ob Spark SQL oder DataFrame-API verlangt ist?*
- Aufgabe zeigt `spark.sql(...)` → Spark SQL
- Aufgabe zeigt `.filter()`, `.groupBy()`, `.agg()` → DataFrame-API
- Beide sind äquivalent! Wenn nicht vorgegeben: wähle die, die du besser kennst
- In Databricks: beide im selben Notebook verwendbar
]

#warn-box[
*Typische Fehler in PySpark-Aufgaben:*
1. *Lazy Evaluation vergessen:* `df.filter(...)` allein gibt nichts aus. Immer Action (`show()`, `count()`, etc.) aufrufen!
2. *`createOrReplaceTempView` vergessen:* Vor `spark.sql(...)` muss der DataFrame als temporäre View registriert sein.
3. *Pandas-Syntax verwenden:* `df["spalte"]` kann in Spark funktionieren, aber `col("spalte")` ist idiomatisch und sicherer.
4. *Schema-Fehler:* Bei `inferSchema=False` sind alle Typen Strings. Dann: `.cast("integer")` etc. nötig.
5. *Grossen `collect()` auf Cluster:* `collect()` bringt ALLE Daten zum Driver — bei Big Data gefährlich (OutOfMemory)!
]

---

== 8. Zusammenfassung: Konzept-Landkarte

#cheat-box[
*Schnellübersicht: Was ist was?*

*Big Data Merkmale:*
- 4 V's → Volume, Variety, Velocity, Veracity
- 5. V → Value (Geschäftswert)

*Datengrössen:*
- Small → RAM → Pandas, R
- Medium → Disk → DuckDB, lokaler Spark
- Big → Cluster → Apache Spark, Flink

*Scale Up vs. Scale Out:*
- Scale Up → In-Memory Column Stores (SAP HANA, DuckDB)
- Scale Out → MapReduce, Apache Spark

*Query Processing Styles:*
- Volcano → ein Tupel nach dem anderen
- Vectorized → Batches/Arrays (SIMD) → moderner, schneller

*MapReduce = Map + Shuffle + Reduce:*
- Map: $(k_"in", v_"in")$ → $(k_"mid", v_"mid")$
- Shuffle: Gruppierung nach $k_"mid"$
- Reduce: $(k_"mid", [v_1, v_2, ...])$ → $(k_"out", v_"out")$

*Apache Spark Kernbegriffe:*
- Driver + Executors
- Lazy Evaluation → Action löst Ausführung aus
- Immutable DataFrames
- Catalyst Optimizer
- Spark SQL ≡ DataFrame-API (gleiche Performance)

*Cloud:*
- Vorteile: Elastizität, niedrige Einstiegskosten, Prototyping
- Nachteile: Vendor Lock-in, GDPR, langfristig teurer, Schein-Einfachheit
- Kernfrage: richtige Workload am richtigen Ort
]