// Auto-generated by RAG system on 2026-04-23
// Week 4 — do not edit the header

#import "../../template.typ": tip-box, warn-box, formula-box, cheat-box

== Chapter 4: Machine Learning Basics (Part 1)

=== Definition & Grundkonzepte

#tip-box[
*Die goldene ML-Definition:*
Ein ML-Algorithmus verbessert die *Performance P* eines Computers bei einer *Aufgabe T* durch *Erfahrung E*.

- *T* (Task): z.B. $hat(y)$ aus $bold(x)$ vorhersagen
- *P* (Performance): z.B. MSE auf Testdaten
- *E* (Experience): Trainingsdaten
]

=== Lineare Regression

#formula-box[
*Lineares Modell mit Bias-Term:*
$ hat(y) = bold(w)^T bold(x) + b $

*Bias-Term-Trick* — füge Spalte von 1en zu $bold(X)$ hinzu:
$ bold(X) = mat(x_(1,1), dots.h, 1; x_(2,1), dots.h, 1; dots.v, , dots.v) $
Dann: $hat(y) = bold(w)^T bold(x)$ (kein separates $b$ nötig)

*Mean Squared Error:*
$ "MSE"_"train" = 1/m sum_(i=1)^m (hat(y)^((i)) - y^((i)))^2 $

*Analytische Lösung* (nur für lin. Regression möglich!):
$ hat(bold(w)) = arg min_(bold(w)) "MSE"_"train" quad arrow.r quad nabla_bold(w) "MSE" = 0 "lösen" $
]

#warn-box[
*Prüfungsfalle:* Der *Bias-Term* $b$ im Modell $hat(y) = bold(w)^T bold(x) + b$ ist *nicht dasselbe* wie der statistische *Bias* eines Schätzers! Zwei völlig verschiedene Konzepte mit demselben Wort.
]

=== Capacity, Overfitting & Underfitting

#formula-box[
*i.i.d.-Annahmen* (Independent & Identically Distributed):
- Datenpunkte sind *unabhängig* voneinander
- Training- und Testdaten kommen aus *derselben* Verteilung $p_"data"$

*Folgerung:*
$ EE["MSE"_"train"] = EE["MSE"_"test"] $

*Ziel der Optimierung — zwei Bedingungen:*
$ 1. quad "MSE"_"train" "klein" $
$ 2. quad "Gap" = "MSE"_"test" - "MSE"_"train" "klein" $
]

#tip-box[
*Capacity = „Flexibilität" des Modells*

| Situation | Training-Fehler | Test-Fehler | Problem |
|---|---|---|---|
| Zu kleine Capacity | groß | groß | *Underfitting* |
| Passende Capacity | klein | klein | ✓ Optimal |
| Zu große Capacity | $≈ 0$ | sehr groß | *Overfitting* |

*Faustregel:* Training-Fehler sinkt *immer* mit Capacity. Test-Fehler hat U-Form!

*Beispiel Polynome:* Linear ($n=2$ Param.) → Quadratisch ($n=3$) → Grad 9 ($n=10$)
]

#warn-box[
*Bayes Error / Irreducible Error:* Selbst ein perfekter Klassifikator hat $"MSE"_"test" > 0$, weil Messfehler, fehlende Kausalzusammenhänge etc. unvermeidbar sind. Man kann den Bayes Error *nicht* durch bessere Modelle reduzieren!
]

=== No Free Lunch Theorem

#tip-box[
*No Free Lunch Theorem* (gemittelt über alle möglichen Datenverteilungen):
Kein ML-Algorithmus ist universell besser als ein anderer.

*Konsequenz (positiv!):* Wir müssen unseren Algorithmus auf unser spezifisches Problem zuschneiden — dann können wir den optimalen Algorithmus finden.
]

=== Regularisierung

#formula-box[
*Definition Regularisierung:*
Jede Modifikation des Lernalgorithmus, die den *Generalisierungsfehler* reduziert, aber *nicht* den Trainingsfehler.

*Beispiel: Weight Decay (L2-Regularisierung):*
$ hat(bold(w)) = arg min_(bold(w)) ["MSE"_"train" + lambda bold(w)^T bold(w)] $

| $lambda$ | Capacity | Effekt |
|---|---|---|
| $0$ | hoch | keine Regularisierung |
| $in (0, infinity)$ | mittel | kontrollierte Flexibilität |
| $arrow infinity$ | $approx 0$ | $bold(w)^T bold(w) arrow 0$ erzwungen |
]

#tip-box[
*DL-Philosophie:*
1. Baue ein sehr großes, flexibles Modell (hohe Capacity)
2. Regularisiere es gezielt

→ In der Praxis erfolgreicher als Capacity direkt zu optimieren!
]

=== Hyperparameter & Validation Sets

#formula-box[
*Dataset-Split (typisch):*
$ "Full Dataset" = underbrace(60%, "Training") + underbrace(20%, "Validation") + underbrace(20%, "Test") $

*Verwendung:*
- *Training Set*: Lernen der Parameter $bold(theta)$
- *Validation Set*: Wahl der Hyperparameter (z.B. $lambda$, Polynomgrad)
- *Test Set*: Finale Schätzung des Generalisierungsfehlers
]

#warn-box[
*Prüfungsfalle — Hyperparameter-Selektion:*
- Training Set für Hyperparameter? → *Nein!* → wählt immer höchste Capacity
- Test Set für Hyperparameter? → *Nein!* → Test Set darf *nie* für Entscheidungen benutzt werden — nur zur finalen Evaluation!
- *Lösung:* Immer Validation Set verwenden!
]

=== Schätzer, Bias & Varianz

#formula-box[
*Point Estimator:*
$ hat(bold(theta))_m = bold(g)(x^((1)), dots, x^((m))) $
basierend auf $m$ i.i.d. Datenpunkten.

*Bias eines Schätzers:*
$ "bias"(hat(theta)_m) = EE[hat(theta)_m] - theta $

*Unverzerrt (unbiased):* $EE[hat(theta)_m] = theta$

*Asymptotisch unverzerrt:* $lim_(m -> infinity) EE[hat(theta)_m] = theta$

*Varianz und Standardfehler:*
$ "Var"(hat(theta)_m) = EE[(hat(theta)_m - EE[hat(theta)_m])^2] $
$ "SE"(hat(theta)_m) = sqrt("Var"(hat(theta)_m)) $

*MSE eines Schätzers (Bias-Varianz-Zerlegung):*
$ "MSE"(hat(theta)_m) = "Bias"(hat(theta)_m)^2 + "Var"(hat(theta)_m) $
]

#formula-box[
*Wichtige Schätzer-Beispiele:*

*Bernoulli-Verteilung* ($P(x=1) = theta$):
$ hat(theta)_m = 1/m sum_(i=1)^m x^((i)) quad arrow.r quad "unbiased!" quad "Bias" = 0 $

*Gauß-Verteilung — Mittelwert* ($EE[x] = mu$):
$ hat(mu)_m = 1/m sum_(i=1)^m x^((i)) quad arrow.r quad "unbiased!" $

*Gauß-Verteilung — Varianz (naive Schätzung):*
$ hat(sigma)^2_m = 1/m sum_(i=1)^m (x^((i)) - hat(mu)_m)^2 quad arrow.r quad "BIASED!" $
$ "bias"(hat(sigma)^2_m) = -sigma^2/m quad (= -(m-1)/m sigma^2 - sigma^2... ) $

*Unbiased Sample Variance:*
$ hat(sigma)^2_m = 1/(m-1) sum_(i=1)^m (x^((i)) - hat(mu)_m)^2 quad arrow.r quad "unbiased!" $

*Standardfehler des Mittelwerts:*
$ "SE"(hat(mu)_m) = sigma / sqrt(m) $
]

#tip-box[
*Konsistenz eines Schätzers:*
$ hat(theta)_m arrow.r^p theta quad "für" quad m -> infinity $
Das bedeutet: (asymptotisch) unverzerrt + Standardfehler $-> 0$

*Merkhilfe Standardfehler:* $"SE" = sigma / sqrt(m)$ → *mehr Daten = kleinerer Fehler* ($sqrt(m)$-Gesetz)

*95%-Konfidenzintervall:*
$ "CI" = [mu - 2sigma, mu + 2sigma] $
]

=== Bias-Varianz Trade-Off

#formula-box[
*Zerlegung des Generalisierungsfehlers:*
$ underbrace("MSE"(hat(theta)_m), "Generalisierungsfehler") = underbrace("Bias"(hat(theta)_m)^2, "Systematischer Fehler") + underbrace("Var"(hat(theta)_m), "Zufälliger Fehler") $
]

#tip-box[
*Trade-Off-Tabelle:*

| Capacity | Bias | Varianz | Problem |
|---|---|---|---|
| niedrig | *hoch* | niedrig | Underfitting |
| mittel | mittel | mittel | ✓ Optimal |
| hoch | niedrig | *hoch* | Overfitting |

*Ziel:* Mittlere Capacity mit optimalem Bias-Varianz-Gleichgewicht finden — typischerweise via Validation Set und Regularisierung.
]

=== Übungs-Cheat-Sheet

#cheat-box[
*Schnellantworten für Multiple Choice:*

*Ziel ML:* Kleiner Test-/Generalisierungsfehler (nicht Trainingsfehler!)

*Overfitting:* großer Test-Fehler + kleiner Train-Fehler → Capacity ↓ oder Daten ↑ oder Regularisierung ↑

*Underfitting:* großer Test- UND Train-Fehler → Capacity ↑

*Overfitting tritt auf wenn:*
- Trainingsdaten klein
- Regularisierungsterm klein ($lambda$ klein)
- Trainingsfehler < Bayes Error

*Regularisierung reduziert:* Generalisierungsfehler + Test-Fehler (aber *nicht* Training-Fehler direkt)

*Dataset-Nutzung:*
- Training → Parameter lernen
- Validation → Hyperparameter wählen
- Test → finale Evaluation (nur einmal!)

*Unbiased Variance:* Teile durch $(m-1)$, nicht $m$!

*Bias-Korrektur für |x|-Schätzer auf $[-0.8, 1.2]$:*
$ "bias" = EE[|x|] - mu = 0.52 - 0.2 = 0.32 $
Korrigierter Schätzer: $hat(mu) = 1/m sum |x^((i))| - 0.32$

*Unbiased Max-Schätzer* für $"Uniform"[0, theta]$:
$ hat(theta) = (m+1)/m dot max(x^((1)), dots, x^((m))) $
]