// Auto-generated by RAG system on 2026-05-09
// Week 4 — do not edit the header

#import "../../template.typ": tip-box, warn-box, formula-box, cheat-box

== Woche 4: Spatial Data Analytics — PostGIS, Funktionen & Geodatenbanken

= Überblick

Diese Woche dreht sich alles um *PostGIS* als räumliche Datenbankerweiterung: Wie man eine Geodatenbank aufbaut, Daten lädt, räumliche Abfragen schreibt und Raumanalysen durchführt. Der rote Faden ist das *EVAP-Prinzip*: Eingabe → Verarbeitung → Analyse → Präsentation.

---

== 1. Das EVAP-Prinzip bei Geodaten

*Kernidee:* Jede Geodatenanalyse folgt demselben vierstufigen Ablauf — von der leeren Datenbank bis zur Visualisierung.

#formula-box[
*EVAP-Ablauf für Geodaten:*

1. *Eingabe (E):* Leere Datenbank erstellen, PostGIS-Extension aktivieren, Tabellen mit Geometrie-Spalten anlegen
2. *Verarbeitung/Laden (V):* Geodaten importieren (QGIS DB-Manager, `ogr2ogr`, `shp2pgsql`, manuelle INSERTs)
3. *Analyse (A):* SQL-Abfragen mit PostGIS-Funktionen ausführen
4. *Präsentation (P):* Ergebnisse in QGIS, geojson.io oder anderen GIS-Tools visualisieren

*Beispiel:* Schweizer Gemeindegrenzen analysieren:
- E: `CREATE DATABASE gisdb;` + `CREATE EXTENSION postgis;`
- V: GeoPackage via `ogr2ogr` laden
- A: `SELECT name FROM gemeinden WHERE ST_Intersects(geom, fluss.geom);`
- P: Ergebnis in QGIS als Layer darstellen
]

#tip-box[
*Woran erkenne ich EVAP-Aufgaben?*
- Aufgabe verlangt das Aufsetzen einer Geodatenbank → Schritt E
- Datei (`.gpkg`, `.json`, `.shp`) soll importiert werden → Schritt V
- Eine räumliche Frage soll beantwortet werden → Schritt A
- Ergebnis soll auf einer Karte erscheinen → Schritt P

*Wichtig bei Geodaten speziell:*
- Schritt E: `GEOMETRY`-Spalte braucht Type Modifier + EPSG-Code
- Schritt V: Bulk-Tools nötig (grosse Datenmengen)
- Schritt P: Koordinatenzahlen alleine sagen nichts — immer visualisieren!
]

---

== 2. PostGIS einrichten

*Kernidee:* PostGIS ist eine Erweiterung von PostgreSQL, die Geodatentypen, räumliche Funktionen und einen speziellen Index (GiST/R-Baum) hinzufügt.

#formula-box[
*PostGIS-Datenbank aufsetzen — Rezept:*

1. Datenbank erstellen:
```sql
CREATE DATABASE gisdb;
```
oder in Shell: `createdb -U postgres gisdb`

2. Zur Datenbank wechseln und Extension aktivieren:
```sql
\c gisdb
CREATE EXTENSION postgis;
```
oder in Shell: `psql -U postgres -d gisdb -c "CREATE EXTENSION postgis;"`

3. Installation prüfen:
```sql
SELECT postgis_full_version();
```
(sollte eine Zeile mit Versionsinformation zurückgeben)

4. Tabelle mit Geometrie-Spalte erstellen:
```sql
CREATE TABLE tabellenname (
  id INT PRIMARY KEY,
  name TEXT,
  geom GEOMETRY('GEOMETRIETYP', EPSG_CODE)
);
```

5. Räumlichen Index erstellen:
```sql
CREATE INDEX idx_tabellenname_geom
ON tabellenname
USING gist(geom);
```

*Beispiel — Eisenbahntabelle für CH:*
```sql
CREATE TABLE eisenbahn (
  id INT4 PRIMARY KEY,
  name TEXT,
  geom GEOMETRY('LINESTRING', 2056)
);
CREATE INDEX idx_eisenbahn_geom ON eisenbahn USING gist(geom);
```
]

#tip-box[
*Woran erkenne ich, dass ich PostGIS-Setup brauche?*
- Aufgabe sagt: "erstellen Sie eine Geodatenbank"
- Aufgabe arbeitet mit Geometrie-Typen in PostgreSQL
- Fehlermeldung "type geometry does not exist" → Extension fehlt!

*Type Modifier Syntax:*
```
GEOMETRY('POINT', 4326)      -- Punkt in WGS84
GEOMETRY('LINESTRING', 2056) -- Linie in CH1903+
GEOMETRY('POLYGON', 21781)   -- Fläche in CH1903
GEOMETRY                     -- ohne Einschränkung (flexibel, aber weniger sicher)
```
]

#warn-box[
*Häufige Fehler beim PostGIS-Setup:*
- `AddGeometryColumn(...)` ist *veraltet* — stattdessen Type Modifier in `CREATE TABLE` verwenden
- Extension muss *pro Datenbank* aktiviert werden, nicht global
- Ohne räumlichen GiST-Index werden räumliche Abfragen bei grossen Datenmengen sehr langsam
- Spaltenname: oft `geom`, manchmal `geometry` oder `the_geom` — konsistent bleiben!
]

---

== 3. Geodatentypen (Vektoren)

*Kernidee:* Vektorgeometrien beschreiben Raumobjekte als Punkte, Linien oder Flächen — mit einem klaren Typ-Hierarchie-System.

=== 3.1 Basis-Geometrietypen

```
GEOMETRY (abstrakter Obertyp)
├── POINT
├── LINESTRING
├── POLYGON
├── MULTIPOINT
├── MULTILINESTRING
├── MULTIPOLYGON
└── GEOMETRYCOLLECTION
```

#tip-box[
*Welcher Typ für welches Objekt?*
- Einzelner Ort, Adresse, Gipfel → `POINT`
- Strasse, Fluss, Grenze (Linie) → `LINESTRING`
- Gemeindegebiet, See, Gebäudefläche → `POLYGON`
- Mehrere Punkte zusammen → `MULTIPOINT`
- Mehrere Linien zusammen → `MULTILINESTRING`
- Mehrere Flächen zusammen (z.B. Kanton mit Enklaven) → `MULTIPOLYGON`
- Gemischte Geometrien → `GEOMETRYCOLLECTION`
]

=== 3.2 WKT — Well Known Text

*Kernidee:* WKT ist die lesbare Textdarstellung von Geometrien, die PostGIS versteht.

```
POINT(lon lat)                       -- Einzelpunkt
LINESTRING(x1 y1, x2 y2, x3 y3)     -- Linie mit Stützpunkten
POLYGON((x1 y1, x2 y2, x3 y3, x1 y1)) -- Fläche (geschlossen!)
```

#warn-box[
*Koordinatenreihenfolge — der häufigste Fehler überhaupt!*

- Menschen sagen: "lat/lon" (Breitengrad/Längengrad), z.B. "47.22, 8.81" für Rapperswil
- PostGIS/WKT erwartet: *lon/lat* (Längengrad zuerst!), also `POINT(8.81 47.22)`
- Merkhilfe: *"Länge lang"* — Längengrade gehen von Pol zu Pol (lang), Breitengrade quer (breit)
- In EPSG:4326: `POINT(Längengrad Breitengrad)` = `POINT(8.818 47.226)` für Rapperswil

*Beispiel für Rapperswil:*
- GeoAdmin/Maps zeigt: 47.226°N, 8.818°E (lat zuerst)
- PostGIS WKT: `POINT(8.818 47.226)` (lon zuerst!)
]

---

== 4. Geodaten-Konstruktoren

*Kernidee:* Konstruktoren wandeln Text- oder Koordinaten-Eingaben in interne PostGIS-Geometrieobjekte um.

#formula-box[
*Wichtige Konstruktoren — Rezept:*

```sql
-- Aus WKT-Text (mit SRID):
ST_GeomFromText('POINT(lon lat)', EPSG_CODE)
ST_GeometryFromText('LINESTRING(x1 y1, x2 y2)', EPSG_CODE)

-- Aus einzelnen Koordinaten:
ST_MakePoint(lon, lat)       -- dann mit ST_SetSRID kombinieren
ST_SetSRID(ST_MakePoint(lon, lat), EPSG_CODE)
ST_Point(lon, lat, EPSG_CODE) -- neuere Variante

-- Geography-Typ (für echte Kugelberechnungen):
ST_GeogFromText('SRID=4326;POINT(lon lat)')

-- Geometrie als Text ausgeben:
ST_AsText(geom)              -- gibt WKT zurück
ST_AsEWKT(geom)              -- gibt WKT mit SRID zurück
ST_AsGeoJSON(geom)           -- gibt GeoJSON zurück
```

*Beispiel — Punkt für Rapperswil einfügen:*
```sql
INSERT INTO ort(id, name, geom)
VALUES (
  100,
  'Rapperswil',
  ST_GeometryFromText('POINT(8.818 47.226)', 4326)
);
```

*Beispiel — Linie einfügen:*
```sql
INSERT INTO uster(id, name, geom)
VALUES (
  100,
  'Uster',
  ST_GeometryFromText('LINESTRING(8.81 47.22, 8.82 47.23)', 4326)
);
```
]

#tip-box[
*Wann welchen Konstruktor?*
- Habe WKT-String + SRID → `ST_GeomFromText('...', srid)`
- Habe nur Koordinaten → `ST_SetSRID(ST_MakePoint(lon, lat), srid)`
- Will Geography (Kugelkoordinaten) → `ST_GeogFromText('SRID=4326;POINT(...)')`
- Will Ergebnis als lesbaren Text → `ST_AsText(geom)` in SELECT
]

---

== 5. Koordinatenreferenzsysteme (EPSG-Codes)

*Kernidee:* Jede Koordinate braucht ein Referenzsystem — ohne EPSG-Code sind Koordinaten bedeutungslos. Viele Fehler entstehen durch falsches oder gemischtes CRS.

#cheat-box[
*Die wichtigsten EPSG-Codes:*

| EPSG | Name | Einheit | Verwendung |
|------|------|---------|-----------|
| 4326 | WGS84 | Grad (°) | GPS, GeoJSON, OpenStreetMap |
| 3857 | Web-Mercator | Meter | Google Maps, OpenStreetMap Tiles |
| 2056 | CH1903+/LV95 | Meter | Aktuelle CH-Landeskarte |
| 21781 | CH1903/LV03 | Meter | Ältere CH-Daten |

*Faustregel:*
- Distanz in Metern berechnen → Daten in metrisches CRS transformieren (2056 für CH)
- Daten aus dem Web/GPS → wahrscheinlich EPSG:4326
- Schweizer Amtsdaten → oft EPSG:2056 oder 21781
]

#warn-box[
*CRS-Fehler — häufigste Probleme:*
- `ST_Distance` in EPSG:4326 gibt Ergebnis in *Grad*, nicht in Metern!
  → Immer erst `ST_Transform(geom, 2056)` für CH-Berechnungen in Metern
- Zwei Tabellen mit verschiedenem CRS können nicht direkt verglichen werden
  → Eine der Geometrien transformieren: `ST_Transform(geom, ziel_epsg)`
- Wenn `ST_Intersects` nichts findet obwohl es sollte → CRS prüfen!
]

#formula-box[
*CRS-Transformation — Rezept:*

```sql
-- Geometrie in anderes CRS transformieren:
ST_Transform(geom, ziel_epsg)

-- Beispiel: Distanz in Metern berechnen (CH):
SELECT ST_Distance(
  ST_Transform(a.geom, 2056),
  ST_Transform(b.geom, 2056)
) AS distanz_meter
FROM tabelle_a a, tabelle_b b
WHERE a.name = 'Bern' AND b.name = 'Zürich';

-- Beispiel: Punkt in CH-Koordinaten aus WGS84:
SELECT ST_Transform(
  ST_GeomFromText('POINT(8.81642 47.22541)', 4326),
  21781
) AS geom_ch;
```
]

---

== 6. Metrische Funktionen (Zahl zurück)

*Kernidee:* Diese Funktionen messen geometrische Eigenschaften und geben Zahlen zurück — Distanz, Länge, Fläche.

=== 6.1 Distanz

#formula-box[
*Distanz berechnen — Rezept:*

```sql
-- Distanz in CRS-Einheiten (Meter wenn metrisches CRS):
ST_Distance(geom1, geom2)

-- Distanz auf Kugeloberfläche (immer Meter, für lat/lon geeignet):
ST_DistanceSphere(geom1, geom2)

-- Allgemeines Muster für Distanz zweier Orte (in Metern, CH):
SELECT
  a.name AS ort_a,
  b.name AS ort_b,
  ST_Distance(
    ST_Transform(a.geom, 2056),
    ST_Transform(b.geom, 2056)
  ) AS distanz_meter
FROM orte a, orte b
WHERE a.name = 'Bern' AND b.name = 'Zürich';
```

*Beispiel — Übung 5.1, Distanz Bern–Zürich:*
```sql
SELECT ST_Distance(
  ST_Transform(a.geom, 2056),
  ST_Transform(b.geom, 2056)
) AS distanz_m
FROM orte a, orte b
WHERE a.name = 'Bern' AND b.name = 'Zürich';
```

*Variante mit festem Referenzpunkt (aus WKT):*
```sql
SELECT name,
  round(
    ST_DistanceSphere(
      geom,
      ST_GeomFromText('POINT(8.816511 47.223064)', 4326)
    )::numeric, 0
  ) AS distanz_meter
FROM beers
ORDER BY distanz_meter;
```
]

=== 6.2 Länge und Fläche

```sql
ST_Length(geom)    -- Länge einer Linie (in CRS-Einheiten)
ST_Area(geom)      -- Fläche eines Polygons (in CRS-Einheiten²)
```

#tip-box[
*Wann `ST_Distance` vs. `ST_DistanceSphere`?*
- Daten in metrischem CRS (2056, 21781): `ST_Distance` direkt → Ergebnis in Metern
- Daten in EPSG:4326 (Grad): `ST_DistanceSphere` → Ergebnis immer in Metern
- Oder: `ST_Transform` auf metrisches CRS, dann `ST_Distance`
- Für präzise Berechnungen in CH: `ST_Transform(..., 2056)` + `ST_Distance`
]

---

== 7. Räumliche Filter-Funktionen (Boolean zurück)

*Kernidee:* Diese Funktionen testen topologische Beziehungen zwischen Geometrien und geben `TRUE`/`FALSE` zurück — sie werden in `WHERE`-Klauseln eingesetzt.

#formula-box[
*Wichtige räumliche Filter — Rezept:*

```sql
-- Schneidet/überlappt (am häufigsten verwendet!):
ST_Intersects(g1, g2)        -- TRUE wenn gemeinsame Punkte

-- Innerhalb einer Distanz:
ST_DWithin(g1, g2, distanz)  -- TRUE wenn Abstand <= distanz

-- Gleichheit:
ST_Equals(g1, g2)            -- TRUE wenn geometrisch identisch

-- Berühren (nur Rand):
ST_Touches(g1, g2)           -- TRUE wenn nur Rand berührt

-- Schneidet (kreuzt):
ST_Crosses(g1, g2)           -- TRUE wenn Linie durch Fläche

-- Enthält/Liegt in:
ST_Contains(g1, g2)          -- g1 enthält g2 vollständig
ST_Within(g1, g2)            -- g2 liegt in g1

-- Bounding-Box-Operator (schnell, für Index):
g1 && g2                     -- TRUE wenn Bounding Boxes überlappen
```

*Allgemeines Muster — "Alle X die Bedingung Y erfüllen":*
```sql
SELECT a.name
FROM tabelle_a a
JOIN tabelle_b b ON ST_Intersects(a.geom, b.geom)
WHERE b.name = 'Referenzobjekt';
```
]

#tip-box[
*Welche Funktion wann?*
- *Normalfall* (Überschneidung jeder Art): `ST_Intersects` ← bevorzugen!
- *Umkreissuche* (alle X innerhalb d Meter): `ST_DWithin`
- *Angrenzende Gebiete*: `ST_Intersects` (Grenzen berühren sich) oder `ST_Touches`
- *Punkt liegt in Polygon*: `ST_Intersects` oder `ST_Within`
- *Linie fliesst durch Gemeinde*: `ST_Intersects`

`ST_Intersects` ist dem `ST_Within`, `ST_Contains`, `ST_Covers` *normalerweise vorzuziehen*, weil es den räumlichen Index nutzt und die häufigste topologische Beziehung prüft.
]

#warn-box[
*Häufiger Denkfehler bei räumlichen Filtern:*
- `ST_Intersects(a, b)` im JOIN ist *nicht dasselbe* wie ein kartesisches Produkt mit WHERE — JOIN ist effizienter
- Bei `ST_DWithin` muss die Distanz in den *CRS-Einheiten* der Geometrie angegeben werden! Mit EPSG:4326 sind das Grad, nicht Meter → transformieren!
- `ST_Disjoint` ist das Gegenteil von `ST_Intersects` — selten gebraucht
]

---

== 8. Räumliche Abfrage-Muster (Rezepte für Übungsaufgaben)

=== 8.1 Umkreissuche: Alle Objekte innerhalb eines Radius

*Kernidee:* "Alle Orte im Umkreis von X km um Punkt P" ist eine klassische räumliche Abfrage.

#formula-box[
*Umkreissuche — Rezept:*

```sql
-- Variante 1: ST_DWithin (empfohlen, nutzt Index)
SELECT a.name
FROM tabelle a
WHERE ST_DWithin(
  a.geom,
  ST_Transform(ST_GeomFromText('POINT(lon lat)', 4326), ziel_epsg),
  radius_in_meter
);

-- Variante 2: Mit CTE für Referenzpunkt
WITH referenz AS (
  SELECT ST_Transform(
    ST_GeomFromText('POINT(lon lat)', 4326),
    ziel_epsg
  ) AS geom
)
SELECT a.name,
  ST_Distance(a.geom, r.geom)::int AS distanz_m
FROM tabelle a
JOIN referenz r ON ST_DWithin(a.geom, r.geom, radius_in_meter)
ORDER BY distanz_m;
```

*Beispiel — Übung 5.3: Orte im Umkreis von 10 km um HSR:*
```sql
-- HSR in CH1903: Easting=704472, Northing=231216
SELECT name
FROM orte
WHERE ST_DWithin(
  geom,
  ST_SetSRID(ST_MakePoint(704472, 231216), 21781),
  10000  -- 10 km in Metern (Daten in EPSG:21781)
);
```

*Beispiel — Übung 4: Orte im Umkreis mit Distanzangabe:*
```sql
WITH mylocation AS (
  SELECT ST_Transform(
    ST_GeomFromText('POINT(8.81642 47.22541)', 4326),
    21781
  ) AS geom
)
SELECT
  o.name,
  ST_AsText(o.geom, 0) AS koordinaten,
  ST_Distance(o.geom, m.geom)::int AS distanz_m
FROM orte o
JOIN mylocation m ON ST_DWithin(o.geom, m.geom, 10000)
ORDER BY distanz_m;
```
]

=== 8.2 Angrenzende/Überlappende Objekte finden

*Kernidee:* "Alle Gemeinden die an X angrenzen" — zwei Tabellen räumlich verknüpfen.

#formula-box[
*Nachbarschaftsabfrage — Rezept:*

```sql
-- Alle Objekte aus tabelle_a, die räumlich tabelle_b berühren/schneiden:
SELECT a.name
FROM tabelle_a a
JOIN tabelle_b b ON ST_Intersects(a.geom, b.geom)
WHERE b.name = 'Referenzname'
  AND a.name != 'Referenzname';  -- Selbst ausschliessen!
```

*Beispiel — Übung 5.2: Gemeinden angrenzend an Rapperswil-Jona:*
```sql
SELECT a.name
FROM gemeinden a
JOIN gemeinden b ON ST_Intersects(a.geom, b.geom)
WHERE b.name = 'Rapperswil-Jona'
  AND a.name != 'Rapperswil-Jona';
```
]

#warn-box[
*Selbstbezug vergessen:* Wenn man eine Tabelle mit sich selbst join't (Nachbarn in derselben Tabelle), muss man `AND a.name != b.name` oder `AND a.id != b.id` einfügen — sonst wird das Objekt sich selbst als Nachbar zurückgegeben!
]

=== 8.3 Objekte in Pufferzone

*Kernidee:* "Alle Orte innerhalb von X km um einen Fluss/eine Linie" — Buffer erzeugen, dann schneiden.

#formula-box[
*Puffer-Abfrage — Rezept:*

```sql
-- Variante 1: ST_DWithin (direkter, effizienter)
SELECT a.name
FROM tabelle_a a
JOIN tabelle_b b ON ST_DWithin(a.geom, b.geom, radius_meter)
WHERE b.name = 'Referenzlinie';

-- Variante 2: Expliziter Buffer (wenn Buffer-Geometrie auch benötigt wird)
SELECT a.name
FROM tabelle_a a
JOIN tabelle_b b ON ST_Intersects(
  a.geom,
  ST_Buffer(b.geom, radius_meter)
)
WHERE b.name = 'Referenzlinie';
```

*Beispiel — Übung 5.4: Orte in 2-km-Pufferzone um Emme:*
```sql
SELECT o.name
FROM orte o
JOIN fluesse f ON ST_DWithin(o.geom, f.geom, 2000)
WHERE f.name = 'Emme';
```

*Beispiel — Übung 5.5: Gemeinden durch die Emme fliesst:*
```sql
SELECT g.name
FROM gemeinden g
JOIN fluesse f ON ST_Intersects(g.geom, f.geom)
WHERE f.name = 'Emme';
```
]

---

== 9. Geometrische Verarbeitungs-Funktionen (Geometrie zurück)

*Kernidee:* Diese Funktionen erzeugen neue Geometrien aus bestehenden — sie sind das Werkzeug der Raumanalyse.

=== 9.1 Puffer (Buffer)

```sql
ST_Buffer(geom, distanz_in_crs_einheiten)
```

Erzeugt eine Pufferzone um eine Geometrie. Distanz in den Einheiten des CRS!

=== 9.2 Verschneidung (Intersection/Overlay)

#formula-box[
*Verschneidungs-Funktionen — Rezept:*

```sql
-- Gemeinsamer Teil (Schnittmenge):
ST_Intersection(g1, g2)

-- Vereinigung:
ST_Union(g1, g2)

-- Differenz (g1 minus g2):
ST_Difference(g1, g2)

-- Symmetrische Differenz (alles ausser Schnittmenge):
ST_SymDifference(g1, g2)
```

*Wichtiger Hinweis:* Immer `ST_Intersects` in WHERE-Bedingung kombinieren, damit keine leeren Geometrien erzeugt werden und der Index genutzt wird:

```sql
SELECT
  g1.name,
  ST_Intersection(g1.geom, g2.geom) AS schnitt_geom
FROM tabelle_1 g1, tabelle_2 g2
WHERE ST_Intersects(g1.geom, g2.geom);
```

*Beispiel — Übung 6.5: Flugschneise (gepuffert) mit Gemeinden verschneiden:*
```sql
SELECT
  g.name,
  ST_Intersection(
    ST_Buffer(f.geom, 2000),
    g.geom
  ) AS schnitt_geom
FROM flugschneise f, gemeinden g
WHERE ST_Intersects(ST_Buffer(f.geom, 2000), g.geom);
```

*Beispiel — Differenz (Teile ausserhalb eines Radius):*
```sql
SELECT
  ST_Transform(
    ST_Difference(
      ST_Transform(geom, 2056),
      ST_Buffer(ST_Transform(ST_Centroid(geom), 2056), 3000)
    ),
    4326
  ) AS ausserhalb_geom
FROM gemeinden
WHERE name = 'Uster';
```
]

=== 9.3 Weitere geometrische Funktionen

```sql
ST_Centroid(geom)           -- Schwerpunkt/Mittelpunkt
ST_Envelope(geom)           -- Minimales umgebendes Rechteck (Bounding Box)
ST_ConvexHull(geom)         -- Konvexe Hülle
ST_PointOnSurface(geom)     -- Garantierter Punkt auf/in der Fläche
```

#tip-box[
*`ST_Centroid` vs. `ST_PointOnSurface`:*
- `ST_Centroid` kann *ausserhalb* der Geometrie liegen (z.B. bei Hufeisenform)
- `ST_PointOnSurface` liegt *immer innerhalb* der Geometrie — für Point-on-Polygon-Abfragen verwenden
]

#warn-box[
*Geometrische Funktionen können unerwartete Typen zurückgeben!*
- `ST_Intersection` zweier Polygone kann POINT, LINESTRING oder POLYGON zurückgeben
- `ST_Union` mehrerer Polygone kann MULTIPOLYGON zurückgeben
- Immer mit `ST_GeometryType(geom)` prüfen wenn unklar
- Cast mit `::geometry` wenn nötig
]

---

== 10. Daten laden: Werkzeuge

*Kernidee:* Geodaten kommen in verschiedenen Formaten — die richtigen Import-Werkzeuge kennen ist Voraussetzung für jede Analyse.

#cheat-box[
*Import-Werkzeuge im Überblick:*

| Werkzeug | Format | Verwendung |
|----------|--------|-----------|
| QGIS DB-Manager | GeoPackage, Shapefile, GeoJSON | Kleine/mittlere Datenmengen, GUI |
| `ogr2ogr` | Alle Formate (GDAL) | Grosse Daten, Kommandozeile |
| `shp2pgsql` | Shapefile → SQL | Älteres Tool, immer noch verbreitet |
| Manuelles INSERT | WKT | Einzelne Objekte, Tests |
| Overpass API / PostPASS | OSM-Daten | OpenStreetMap-Abfragen |

*`ogr2ogr` Befehl für GeoPackage → PostGIS:*
```
ogr2ogr -f PostgreSQL PG:"dbname='gisdb' user='postgres' password='postgres'" -overwrite Schweiz.gpkg
```
]

---

== 11. OpenStreetMap und PostPASS

*Kernidee:* OpenStreetMap ist die grösste freie Geodaten-Quelle — PostPASS bietet SQL-Zugang zu weltweiten OSM-Daten via PostGIS-Schema.

=== 11.1 OSM-Datenmodell

#tip-box[
*OSM physisches Schema (Nodes, Ways, Relations):*
- *Nodes* = Punkte mit Koordinaten + optionale Tags
- *Ways* = geordnete Liste von Nodes (ohne eigene Koordinaten)
- *Relations* = Gruppierung von Nodes/Ways/Relations
- *Tags* = Key-Value-Paare für Attribute (z.B. `amenity=restaurant`)

*Vorsicht:* Flächen in OSM = geschlossene Ways oder Relations — kein eigenständiger Flächentyp!
]

=== 11.2 PostPASS-Schema

PostPASS bietet ein GIS-freundliches Schema:

```
postpass_point    -- OSM Nodes mit Tags
postpass_line     -- OSM Ways als Linien (Strassen, etc.)
postpass_polygon  -- Geschlossene Ways als Flächen
postpass_pointpolygon-- View: Points + Polygone kombiniert (für gemischte Suchen)
```

Gemeinsame Attribute aller PostPASS-Tabellen:
- `osm_type` & `osm_id` — interner OSM-Identifikator
- `tags` — vom Typ `json` (Key-Value-Paare)
- `geom` — vom Typ `GEOMETRY` in EPSG:4326

#formula-box[
*PostPASS SQL-Abfrage — Rezept:*

```sql
-- Grundmuster: Objekte nach Tag filtern + Bounding Box
SELECT
  osm_id,
  coalesce(tags->>'name', '?') AS name,
  tags->>'attribut_key' AS attribut,
  ST_PointOnSurface(geom) AS geom
FROM postpass_pointpolygon
WHERE tags->>'amenity' = 'restaurant'
  AND geom && {{bbox}};

-- Tags-Array-Suche (wenn Wert mehrere mit ';' getrennte Werte hat):
WHERE string_to_array(tags->>'cuisine', ';') @> '{kebab}'
```

*Beispiel — Restaurants mit Kebab-Küche in Bounding Box:*
```sql
SELECT
  osm_id,
  coalesce(tags->>'name', '?') AS name,
  tags->>'cuisine' AS cuisine,
  ST_PointOnSurface(geom) AS geom
FROM postpass_pointpolygon
WHERE tags->>'amenity' IN ('fast_food', 'restaurant')
  AND string_to_array(tags->>'cuisine', ';') @> '{kebab}'
  AND geom && {{bbox}};
```
]

#tip-box[
*JSON-Tags in PostPASS abfragen:*
- `tags->>'key'` gibt den Wert als Text zurück (null wenn nicht vorhanden)
- `coalesce(tags->>'name', '?')` gibt '?' zurück wenn kein Name vorhanden
- `tags->>'amenity' IN ('restaurant', 'cafe')` für mehrere Werte
- `string_to_array(tags->>'key', ';') @> '{wert}'` wenn Wert mit Semikolon getrennt ist (OSM-Konvention)
]

---

== 12. Spatial Relationships — Konzept

*Kernidee:* Räumliche Beziehungen zwischen Objekten können direkt aus der Geometrie abgeleitet werden — ohne explizite Modellierung einer Beziehungstabelle.

=== 12.1 Typen räumlicher Beziehungen

```
Nähe (Proximity):     Distanz zwischen zwei Objekten
Nachbarschaft:        Grenzen aneinander (touching/adjacent)
Containment:          Ein Objekt liegt in einem anderen
Überschneidung:       Objekte haben gemeinsame Fläche
```

=== 12.2 Klassifikation von Raumanalysefunktionen (nach Keller)

#cheat-box[
*Funktionsklassen und Rückgabetypen:*

| Klasse | Rückgabe | Beispiele |
|--------|----------|-----------|
| Management/Constructor | Geometrie | `ST_MakePoint`, `ST_GeomFromText` |
| Output/Conversion | Text/JSON | `ST_AsText`, `ST_AsGeoJSON` |
| Measurement | Zahl | `ST_Length`, `ST_Area`, `ST_Distance` |
| Relationship/Filter | Boolean | `ST_Intersects`, `ST_DWithin`, `ST_Equals` |
| Spatial Aggregate | Geometrie | `ST_Union` (aggregiert mehrere) |
| Processing | Geometrie | `ST_Buffer`, `ST_Intersection`, `ST_Difference` |

*Entscheidungsregel:*
- Brauche ich ein JA/NEIN? → Relationship-Funktion (WHERE-Klausel)
- Brauche ich eine Zahl? → Measurement-Funktion (SELECT oder ORDER BY)
- Brauche ich eine neue Geometrie? → Processing-Funktion (SELECT)
]

---

== 13. Räumliche Indexe

*Kernidee:* Ohne räumlichen Index muss PostgreSQL bei jeder Abfrage alle Geometrien prüfen — mit GiST-Index werden nur geometrisch nahe Objekte berücksichtigt.

#formula-box[
*GiST-Index erstellen — Rezept:*

```sql
CREATE INDEX indexname
ON tabellenname
USING gist(geom);

-- Konvention für Indexname: idx_tabellenname_geom
CREATE INDEX idx_gemeinden_geom
ON gemeinden
USING gist(geom);
```

*Wie der Index funktioniert:*
- GiST = Generalized Search Tree
- Implementiert als R-Baum (R-tree): mehrdimensionale, dynamische, balancierte Datenstruktur
- Speichert Bounding Boxes der Geometrien hierarchisch
- `ST_Intersects`, `ST_DWithin`, `&&`-Operator nutzen den Index automatisch
]

#tip-box[
*Wann wird der Index genutzt?*
- `ST_Intersects(a.geom, b.geom)` → nutzt Index ✓
- `a.geom && b.geom` → nutzt Index, nur Bounding Box ✓ (schneller, weniger präzise)
- `ST_Distance(a.geom, b.geom) < 1000` → nutzt Index *nicht* automatisch → `ST_DWithin` bevorzugen!

*Beste Praxis:* Immer `ST_DWithin` statt `ST_Distance(...) < d` für gefilterte Abfragen.
]

---

== 14. Geo-Normen und Datenformate

*Kernidee:* Geodaten kommen in vielen Formaten — die wichtigsten kennen und einordnen können.

#cheat-box[
*Vektor-Formate im Überblick:*

| Format | Typ | Status | Hinweis |
|--------|-----|--------|---------|
| Shapefile | Vektor | Veraltet | Immer noch verbreitet; viele Einschränkungen |
| GeoJSON | Vektor | Aktuell | W3C-Standard; direkt in Browser nutzbar |
| GeoPackage | Vektor+Raster | Aktuell | SQLite-basiert; OGC-Standard; empfohlen |
| KML | Vektor | Aktuell | XML; Google-Ursprung; OGC |
| Interlis | Vektor | CH-spezifisch | Amtliche CH-Daten |
| WFS | Webservice | Veraltet (→ OGC API) | XML-basiert |
| OGC API Features | Webservice | Aktuell | REST + GeoJSON; WFS-Nachfolger |

*Raster-Formate:*

| Format | Hinweis |
|--------|---------|
| GeoTIFF | Standard für Rasterdaten; enthält CRS-Info |
| WMS | Web Map Service; Bilder als Kacheln |
| OGC API Maps | WMS-Nachfolger |
]

---

== 15. Offene Geodatenquellen

*Kernidee:* Der "Raumbezug als universeller Fremdschlüssel" erlaubt die Verknüpfung beliebiger Datensätze über Koordinaten — freie Datenquellen kennen ist prüfungsrelevant.

#cheat-box[
*Wichtige freie Geodatenquellen:*

*Schweiz:*
- `map.geo.admin.ch` — Swisstopo, offizielle CH-Geodaten
- `opendata.swiss` — Schweizer Open Government Data Portal
- Bundesamt für Statistik — statistische Geodaten
- `GeoHarvester.ch` — aggregiert CH-Geodaten

*International:*
- `osm.org` / Overpass Turbo — OpenStreetMap, weltweit, frei
- PostPASS (`postpass.geofabrik.de`) — SQL-Zugang zu OSM-Daten
- NASA SRTM — Höhenmodell weltweit
- `datasetsearch.research.google.com` — Google Dataset Search
- `giswiki.ch/Freie_Geodaten` — Sammlung freier Geodaten

*API (teils Freemium):*
- Google Maps API
- OpenMapTiles API
]

---

== 16. Vollständige Beispiel-Queries (Übungsreferenz)

=== Übung 4: Orte im Umkreis von 10 km (mit CTE)

```sql
WITH mylocation AS (
  SELECT ST_Transform(
    ST_GeomFromText('POINT(8.81642 47.22541)', 4326),
    21781
  ) AS geom
)
SELECT
  o.name,
  ST_AsText(o.geom, 0) AS koordinaten,
  ST_Distance(o.geom, m.geom)::int AS distanz_m
FROM orte o
JOIN mylocation m ON ST_DWithin(o.geom, m.geom, 10000)
ORDER BY distanz_m;
```

*Was passiert hier:*
1. CTE `mylocation`: Punkt aus WGS84-Koordinaten wird in CH1903 (21781) transformiert
2. `ST_DWithin`: filtert Orte innerhalb 10 km (= 10000 m)
3. `ST_Distance`: berechnet genaue Distanz in Metern
4. `::int`: castet auf Integer (keine Dezimalstellen)
5. `ORDER BY distanz_m`: sortiert nach Nähe

=== Übung 5.2: Angrenzende Gemeinden

```sql
SELECT a.name
FROM gemeinden a
JOIN gemeinden b ON ST_Intersects(a.geom, b.geom)
WHERE b.name = 'Rapperswil-Jona'
  AND a.name != 'Rapperswil-Jona';
```

=== Übung 5.3: Orte im Umkreis (feste Koordinaten)

```sql
SELECT name
FROM orte
WHERE ST_DWithin(
  geom,
  ST_SetSRID(ST_MakePoint(704472, 231216), 21781),
  10000
);
```

=== Übung 5.4: Orte in Pufferzone um Fluss

```sql
SELECT DISTINCT o.name
FROM orte o
JOIN fluesse f ON ST_DWithin(o.geom, f.geom, 2000)
WHERE f.name = 'Emme';
```

=== Übung 5.5: Gemeinden durch die der Fluss fliesst

```sql
SELECT DISTINCT g.name
FROM gemeinden g
JOIN fluesse f ON ST_Intersects(g.geom, f.geom)
WHERE f.name = 'Emme';
```

=== Übung 6.5: Flugschneise gepuffert × Gemeinden verschneiden

```sql
SELECT
  g.name,
  ST_Intersection(
    ST_Buffer(f.geom, 2000),
    g.geom
  ) AS schnitt_geom
FROM flugschneise f
JOIN gemeinden g ON ST_Intersects(ST_Buffer(f.geom, 2000), g.geom);
```

#tip-box[
*Attribute die SQL-Keywords sind — immer in Anführungszeichen:*
```sql
SELECT "name", "date", "type" FROM ...
--       ↑ name ist kein Keyword aber Konvention
--              ↑ date ist SQL-Keyword → muss gequotet werden!
```
`DISTINCT` nicht vergessen wenn JOIN mehrere Treffer pro Objekt erzeugen kann!
]

---

== 17. Zusammenfassung: Entscheidungsbaum für räumliche Abfragen

#cheat-box[
*Wenn die Aufgabe lautet... dann benutze...*

- "Alle X *in einem Umkreis* von d km um P"
  → `ST_DWithin(x.geom, p.geom, d_in_meter)` + CRS prüfen!

- "Alle X *die an* Y *angrenzen*"
  → `ST_Intersects(x.geom, y.geom)` + Selbstbezug ausschliessen

- "Alle X *durch die* Y *fliesst/geht*"
  → `ST_Intersects(x.geom, y.geom)`

- "Alle X *in einer Pufferzone* von d km um Y"
  → `ST_DWithin(x.geom, y.geom, d)` oder `ST_Intersects(x.geom, ST_Buffer(y.geom, d))`

- "*Distanz* zwischen A und B"
  → `ST_Distance(ST_Transform(a.geom, 2056), ST_Transform(b.geom, 2056))`

- "*Schnittfläche* von A und B"
  → `ST_Intersection(a.geom, b.geom)` WHERE `ST_Intersects(a.geom, b.geom)`

- "*Distanz in Metern* bei EPSG:4326-Daten"
  → Entweder `ST_DistanceSphere(g1, g2)` oder `ST_Distance(ST_Transform(g1,2056), ST_Transform(g2,2056))`

- "Koordinaten aus *WKT-Text* erstellen"
  → `ST_GeomFromText('POINT(lon lat)', epsg)`

- "Geometrie in *anderen EPSG* umrechnen"
  → `ST_Transform(geom, ziel_epsg)`
]