// Auto-generated by RAG system on 2026-04-23
// Week 4 — do not edit the header

#import "../../template.typ": tip-box, warn-box, formula-box, cheat-box

== Week 4: Machine Learning Basics — Generalisierung, Bias, Varianz

= Lineare Regression als Einstieg

*Kernidee:* Wir suchen Parameter $bold(w)$, die eine lineare Abbildung von Eingabe $bold(x)$ auf Ausgabe $y$ beschreiben — und das so, dass das Modell auf _neuen_ Daten gut funktioniert, nicht nur auf den Trainingsdaten.

Das Modell lautet:

$ hat(y) = bold(w)^T bold(x) + b $

Mit Bias-Trick (Spalte aus Einsen zu $bold(X)$ hinzufügen) wird das zu:

$ hat(y) = bold(w)^T bold(x) $

*Performance-Maß — Mean Squared Error (MSE):*

$ "MSE"_"train" = frac(1, m) sum_(i=1)^m (hat(y)^((i)) - y^((i)))^2 $

$ "MSE"_"test" = frac(1, m') sum_(i=1)^m' (hat(y)^((i)) - y^((i)))^2 $

wobei $m$ die Anzahl Trainingsbeispiele ist und $m'$ die Anzahl Testbeispiele.

#tip-box[
*Woran erkenne ich: Lineare Regression?*
- Aufgabe sagt "lineares Modell", "Regression", "Vorhersage von $y$ aus $x$"
- Gesucht: Parameter $bold(w)$ (und evtl. $b$)
- Performance-Maß: MSE

*Analytische Lösung:* Nur für lineare Regression möglich — Gradient des MSE berechnen, null setzen, nach $bold(w)$ auflösen:
$ hat(bold(w)) = arg min_(bold(w)) "MSE"_"train" $
In Deep Learning: immer Gradient Descent!
]

#warn-box[
*Häufiger Denkfehler: Bias-Term verwechseln*

Der "Bias" $b$ im linearen Modell ($hat(y) = bold(w)^T bold(x) + b$) ist *nicht dasselbe* wie der statistische "Bias" eines Schätzers! Es sind zwei völlig verschiedene Konzepte mit demselben Wort.

- $b$ im Modell = Achsenabschnitt / Intercept
- Bias des Schätzers = systematische Abweichung vom wahren Wert (siehe unten)
]

= I.I.D.-Annahme und warum $"MSE"_"train"$ sinnvoll ist

*Kernidee:* Wenn Trainings- und Testdaten aus der _gleichen_ Verteilung stammen und unabhängig sind, dann ist der erwartete Trainingsfehler gleich dem erwarteten Testfehler.

*I.I.D. = Independent and Identically Distributed:*
- *Unabhängig:* Jedes Datenpunkt beeinflusst keinen anderen
- *Identisch verteilt:* Alle Datenpunkte kommen aus derselben Verteilung $p_"data"$

Unter I.I.D.-Annahme gilt:

$ EE["MSE"_"train"] = EE["MSE"_"test"] $

*Deshalb:* Wenn wir $"MSE"_"train"$ minimieren, minimieren wir im Erwartungswert auch $"MSE"_"test"$. Das ist die fundamentale Rechtfertigung für maschinelles Lernen.

= Kapazität, Overfitting und Underfitting

*Kernidee:* Die "Kapazität" eines Modells bestimmt, wie flexible Funktionen es darstellen kann. Zu wenig Kapazität → Underfitting. Zu viel → Overfitting. Das Ziel ist der goldene Mittelweg.

#formula-box[
*Zwei Wege zu kleinem $"MSE"_"test"$:*

Aus $EE["MSE"_"test"] = EE["MSE"_"train"] + "Lücke"$ folgt:

1. $"MSE"_"train"$ klein machen (genug Kapazität)
2. Lücke zwischen $"MSE"_"train"$ und $"MSE"_"test"$ klein halten (nicht zu viel Kapazität)

*Underfitting:* Modell zu simpel
- $"MSE"_"train"$ groß
- $"MSE"_"test"$ groß
- Lösung: Kapazität erhöhen

*Overfitting:* Modell zu komplex
- $"MSE"_"train" approx 0$
- $"MSE"_"test"$ groß
- Lösung: Kapazität reduzieren (z.B. Regularisierung)
]

*Beispiel — Polynomielle Regression:*

| Modell | Parameter | Kapazität |
|--------|-----------|-----------|
| $hat(y) = w_1 x$ | 1 | gering |
| $hat(y) = w_1 x + w_2 x^2 + b$ | 3 | mittel |
| $hat(y) = w_1 x + ... + w_9 x^9 + b$ | 10 | hoch |

Trainings-Fehler fällt monoton mit steigender Kapazität. Test-Fehler folgt einer U-Kurve mit einem Minimum bei optimaler Kapazität.

*Bayes-Fehlerrate (irreduzibler Fehler):*

Selbst ein perfektes Modell mit Kenntnis von $p_"data"$ erzielt nicht $"MSE"_"test" = 0$, weil Messrauschen und fehlende Kausalbeziehungen existieren. Dieser Fehler heißt *Bayes-Fehlerrate* und ist eine untere Schranke für jeden Algorithmus.

= Regularisierung

*Kernidee:* Statt die optimale Kapazität zu suchen, baut man ein zu großes Modell und zwingt es dann durch einen Strafterm, einfachere Lösungen zu bevorzugen.

*Definition:*
#tip-box[
Regularisierung ist jede Modifikation eines Lernalgorithmus, die den *Generalisierungsfehler* (aber nicht den Trainingsfehler) reduziert.
]

*Beispiel — Weight Decay (L2-Regularisierung):*

Statt nur $"MSE"_"train"$ zu minimieren:

$ hat(bold(w)) = arg min_(bold(w)) "MSE"_"train" + lambda bold(w)^T bold(w) $

- $lambda = 0$: Kein Effekt, hohe Kapazität
- $lambda arrow.r infinity$: $bold(w)^T bold(w) arrow.r 0$, keine Flexibilität
- Optimales $lambda$: irgendwo dazwischen

#cheat-box[
*Regularisierung — Entscheidungsregeln:*

- Wenn $lambda$ groß → Modell einfacher → mehr Bias, weniger Varianz → Gefahr: Underfitting
- Wenn $lambda$ klein → Modell flexibel → weniger Bias, mehr Varianz → Gefahr: Overfitting
- $lambda$ ist ein *Hyperparameter* → wird auf dem *Validierungsset* optimiert, NICHT auf Test- oder Trainingsdaten!
]

= Hyperparameter und Datensatz-Splits

*Hyperparameter:* Parameter des Lernalgorithmus, die _nicht_ durch das Training gelernt werden (z.B. Polynomgrad, $lambda$).

*Warum brauchen wir drei Datensätze?*

- *Trainingset:* Lernen der Modellparameter $bold(w)$
- *Validierungsset:* Auswahl der Hyperparameter (z.B. $lambda$)
- *Testset:* Finale Schätzung des Generalisierungsfehlers — nur einmal benutzt!

#warn-box[
*Testset darf NIEMALS zur Modellauswahl benutzt werden!*

Wenn du Hyperparameter auf dem Testset optimierst, schummelt das Modell — es hat diese Daten "gesehen" und der gemessene Fehler ist kein ehrlicher Schätzer für neue Daten mehr.

Typische Aufteilung: 60% Training / 20% Validierung / 20% Test
]

= Schätzer, Bias und Varianz

*Kernidee:* Maschinelles Lernen ist ein Schätzproblem — wir schätzen Parameter aus endlich vielen Daten. Bias und Varianz beschreiben, wie gut unser Schätzer dabei ist.

*Notation:*
- $theta$: wahrer (unbekannter) Parameterwert
- $hat(theta)_m$: Schätzer basierend auf $m$ Datenpunkten
- $hat(theta)_m = g(x^((1)), ..., x^((m)))$: irgendeine Funktion der Daten

== Bias eines Schätzers

$ "bias"(hat(theta)_m) = EE[hat(theta)_m] - theta $

- *Unverzerrt (unbiased):* $"bias"(hat(theta)_m) = 0$ für alle $m$
- *Asymptotisch unverzerrt:* $lim_(m arrow.r infinity) "bias"(hat(theta)_m) = 0$

#formula-box[
*Rezept: Bias eines Schätzers berechnen*

1. Schreibe den Schätzer $hat(theta)_m$ explizit auf
2. Berechne $EE[hat(theta)_m]$ (Erwartungswert über alle möglichen Datensätze)
   - Linearität des Erwartungswerts ausnutzen: $EE[frac(1,m) sum x^((i))] = frac(1,m) sum EE[x^((i))]$
   - Wenn i.i.d.: alle $EE[x^((i))]$ sind gleich = wahrer Mittelwert
3. Berechne $"bias" = EE[hat(theta)_m] - theta$
4. Falls Bias = 0: Schätzer ist unverzerrt ✓

*Beispiel — Bernoulli-Parameter:* Schätzer ist Stichprobenmittel $hat(theta)_m = frac(1,m) sum_(i=1)^m x^((i))$.

$ EE[hat(theta)_m] = frac(1,m) sum_(i=1)^m EE[x^((i))] = frac(1,m) dot m dot theta = theta $

$ arrow.r "bias" = theta - theta = 0 quad checkmark $
]

== Varianz und Standardfehler

$ "Var"(hat(theta)_m) = EE[(hat(theta)_m - EE[hat(theta)_m])^2] $

$ "SE"(hat(theta)_m) = sqrt("Var"(hat(theta)_m)) $

*Standardfehler des Stichprobenmittels* (bei Normalverteilung mit Streuung $sigma$):

$ "SE"(hat(mu)_m) = frac(sigma, sqrt(m)) $

*Interpretation:* Je mehr Datenpunkte ($m$ groß), desto kleiner der Standardfehler → bessere Schätzung.

== Beispiel: Gausssche Varianz-Schätzer

*Naiver Schätzer* (biased):

$ hat(sigma)^2_m = frac(1,m) sum_(i=1)^m (x^((i)) - hat(mu)_m)^2 $

Bias davon: $ "bias"(hat(sigma)^2_m) = -frac(sigma^2, m) $

*Unbiased Schätzer* (korrigiert):

$ tilde(sigma)^2_m = frac(1, m-1) sum_(i=1)^m (x^((i)) - hat(mu)_m)^2 $

#tip-box[
*Woran erkenne ich, welchen Varianzschätzer ich nehmen soll?*
- Teiler $m$: biased (systematisch zu klein), aber asymptotisch unbiased
- Teiler $m-1$: unbiased (Bessel-Korrektur)
- In Prüfungsaufgaben: wenn "unbiased" gefordert → immer $m-1$!
]

== Konsistenz

Ein Schätzer ist *konsistent*, wenn:

$ lim_(m arrow.r infinity) hat(theta)_m arrow.r theta quad "in Wahrscheinlichkeit" $

Das bedeutet konkret:
1. Asymptotisch unverzerrt: Bias $arrow.r 0$ für $m arrow.r infinity$
2. Standardfehler $arrow.r 0$ für $m arrow.r infinity$

= Bias-Varianz-Tradeoff

*Kernidee:* Der mittlere quadratische Fehler eines Schätzers zerfällt in zwei Teile — systematischen Fehler (Bias) und Streuung (Varianz). Man kann selten beide gleichzeitig minimieren.

*MSE eines Schätzers* (nicht zu verwechseln mit MSE der Regression!):

$ EE[(hat(theta)_m - theta)^2] = "Bias"(hat(theta)_m)^2 + "Var"(hat(theta)_m) $

*Herleitung-Intuition:*

$ EE[(hat(theta) - theta)^2] = EE[(hat(theta) - EE[hat(theta)] + EE[hat(theta)] - theta)^2] $
$ = "Var"(hat(theta)) + "Bias"(hat(theta))^2 $

#cheat-box[
*Bias-Varianz-Tradeoff — Entscheidungsregeln:*

- Niedrige Kapazität → hoher Bias, niedrige Varianz → Underfitting
- Hohe Kapazität → niedriger Bias, hohe Varianz → Overfitting
- Optimale Kapazität → bester Tradeoff → minimaler Generalisierungsfehler

Wenn Aufgabe fragt: "Modell A hat Bias 2, Varianz 1; Modell B hat Bias 0.5, Varianz 4 — welches ist besser?"

→ MSE(A) = $2^2 + 1 = 5$, MSE(B) = $0.5^2 + 4 = 4.25$ → Modell B ist besser
]

= Aufgaben-Lösungsrezepte für die Prüfung

#formula-box[
*Aufgabe: Bias eines Schätzers bestimmen*

Gegeben: Verteilung auf Intervall $[a, b]$, Schätzer $hat(mu)_m$

1. Wahren Mittelwert berechnen: $mu = frac(a+b, 2)$
2. Erwartungswert des Schätzers berechnen: $EE[hat(mu)_m]$
   - Linearität: Erwartungswert rein-/rausziehen
   - Integral über die Verteilung auswerten
3. Bias $= EE[hat(mu)_m] - mu$
4. Falls Bias $= 0$ → unbiased ✓

*Beispiel: Uniform$[-0.8, 1.2]$, Schätzer = Stichprobenmittel*

$ mu = frac(-0.8 + 1.2, 2) = 0.2 $
$ EE[hat(mu)_m] = frac(1,m) sum_(i=1)^m EE[x^((i))] = frac(1,m) dot m dot 0.2 = 0.2 $
$ "bias" = 0.2 - 0.2 = 0 quad arrow.r "unbiased" $

*Gleiche Verteilung, aber Schätzer nimmt Betrag:*
$ hat(mu)_m = frac(1,m) sum_(i=1)^m abs(x^((i))) $
$ EE[abs(x)] = integral_(-0.8)^0 (-x) frac(1,2) d x + integral_0^(1.2) x frac(1,2) d x = 0.16 + 0.36 = 0.52 $
$ "bias" = 0.52 - 0.2 = 0.32 quad arrow.r "biased!" $
]

#formula-box[
*Aufgabe: Biased Schätzer korrigieren*

Gegeben: Schätzer $hat(theta)$ mit bekanntem Bias $b = EE[hat(theta)] - theta$

Methode 1 (wenn Bias bekannt): $ hat(theta)_"korr" = hat(theta) - b $

Methode 2 (strukturell, ohne Bias-Berechnung): Verschiebe Daten so, dass alle Werte positiv sind:
$ hat(mu)_"korr" = frac(1,m) sum_(i=1)^m (abs(x^((i))) + C) - C $
wobei $C > abs(a)$ (größer als Betrag der unteren Grenze)

*Optionale Aufgabe: Max-Schätzer für Uniform$[0, theta]$*

$ hat(theta) = max(x^((1)), ..., x^((m))) $
$ EE[hat(theta)] = frac(m, m+1) theta $
$ arrow.r "bias" = frac(m, m+1) theta - theta = -frac(theta, m+1) $
$ hat(theta)_"korr" = frac(m+1, m) max(x^((1)), ..., x^((m))) quad checkmark $
]

= No Free Lunch Theorem

*Kernidee:* Gemittelt über _alle_ möglichen Datenverteilungen ist kein Lernalgorithmus besser als ein anderer.

*Was das in der Praxis bedeutet:* Wir müssen unseren Algorithmus auf die _spezifische_ Art von Daten zuschneiden. Es gibt keinen universell besten Algorithmus.

*Konsequenz für Deep Learning:* Wir schneidern den Algorithmus auf realistische Daten zu (Bilder, Sprache, etc.) — und das funktioniert sehr gut für diese Domänen.

#tip-box[
*Übersicht: Welches Konzept bei welcher Aufgabe?*

| Aufgabentyp | Konzept | Schlüsselaktion |
|-------------|---------|-----------------|
| "Ist Schätzer X unbiased?" | Bias | $EE[hat(theta)] - theta$ berechnen |
| "Vergleiche zwei Modelle" | Bias-Varianz | $"Bias"^2 + "Var"$ für beide |
| "Modell fittet Training, aber nicht Test" | Overfitting | Kapazität reduzieren / Regularisierung |
| "Modell fittet weder Training noch Test" | Underfitting | Kapazität erhöhen |
| "Welchen $lambda$ für Weight Decay?" | Hyperparameter | Validierungsset verwenden |
| "Warum Validierungsset?" | Testset-Integrität | Testset ist tabu für Modellauswahl |
]