// Auto-generated by RAG system on 2026-05-09
// Week 3 — do not edit the header

#import "../../template.typ": tip-box, warn-box, formula-box, cheat-box

Looking at the errors, I can see two issues:
1. Lines 61-64: The `*E*`, `*V*`, `*A*`, `*P*` pattern with bold single letters is causing "unclosed delimiter" errors because Typst interprets `*E*` as bold markup, and when combined with the list items, something is going wrong. Actually, looking more carefully, the issue might be that `*E*rfassung` etc. are fine in normal text but the error points to position 2 (the `*`). Let me re-examine - the error says "unclosed delimiter" at the `*` character position. This suggests the `*` bold markers are somehow unclosed. But they look balanced... The real issue might be something earlier on line 60 or before that causes a parsing problem cascading.

2. Line 548: `#tip-box[` has an unclosed bracket - the content at the very end is cut off: `2. Vektor oder Raster? (best` - the tip-box is never closed!

Let me fix both issues - the tip-box needs to be closed, and I'll check if the bold markers on lines 61-64 need escaping. Since the errors show unclosed delimiter at position 2 (the `*`), and looking at the list items `- *E*rfassung`, these should be fine in Typst. The cascade might be from the unclosed tip-box at the end. Let me just close the tip-box and see.

== Woche 3: Spatial Data Analytics — Einführung

=== Überblick und Lernziele

Nach dieser Woche kannst du:
- Erklären, was Geodaten sind und warum sie besonders sind
- Koordinatenreferenzsysteme unterscheiden und korrekt einsetzen
- Vektor- vs. Rasterdaten unterscheiden und ihre Vor-/Nachteile nennen
- GIS-Architekturen und Produkte einordnen
- GIS-Dateiformate erkennen und das richtige wählen
- Einfache räumliche Analysen mit Vektordaten durchführen (Übungsaufgabe: Autobahn)

---

=== 1. Was ist Spatial Data Analytics?

*Kernidee:* Daten mit geografischem Bezug werden mit speziellen Methoden analysiert, um räumliche Muster, Verteilungen und Beziehungen zu erkennen — also die Frage "Wo?" mit "Was?" und "Wann?" zu verbinden.

*Geodatenanalyse* untersucht Daten mit einer geografischen/räumlichen Komponente mittels:
- visueller Methoden (Karten, Dashboards)
- analytischer Methoden (räumliche Abfragen, Joins)
- statistischer Methoden (Clusterung, Hotspot-Analysen, Zeitreihenmodelle)

#tip-box[
*Woran erkenne ich eine Spatial-Analytics-Aufgabe?*
- Die Aufgabe enthält Koordinaten, Adressen, oder Begriffe wie "in der Nähe von", "innerhalb von", "überschneidet"
- Es geht um Karten, Layer, Polygone, Linien oder Punkte
- Es wird nach räumlichen Beziehungen gefragt (z.B. Puffer, Verschneidung, Distanz)
]

*Typische Anwendungen:*
- Klimaforschung: Hitzeinsel-Analyse
- Verkehr: Routing, Flottenmanagement, selbstfahrende Autos
- eGovernment: Stadtplanung, Ressourcenverwaltung
- Gesundheit: Krankheitslokalisation
- Logistik: "Geo-Targeted Marketing"

#cheat-box[
*Spatial Analytics Entscheidungsbaum:*
- Frage "Wo ist X?" → Geocoding / Punktdaten
- Frage "Was ist in der Nähe von Y?" → Pufferanalyse
- Frage "Welche Objekte überschneiden sich?" → Verschneidung (Intersection)
- Frage "Wie komme ich von A nach B?" → Routing / Netzwerkanalyse
- Frage "Wo gibt es Häufungen?" → Cluster-/Hotspot-Analyse
]

---

=== 2. Geoinformationssysteme (GIS)

*Kernidee:* Ein GIS ist ein spezialisiertes Informationssystem für Geodaten — es deckt den gesamten Lebenszyklus von Geodaten ab: Erfassen, Verwalten, Analysieren und Präsentieren.

==== Definition und EVAP-Prinzip

Ein GIS ist ein Informationssystem zur:
- #strong[E]rfassung (Eingabe)
- #strong[V]erwaltung (Speicherung)
- #strong[A]nalyse
- #strong[P]räsentation (Darstellung)

...aller Daten, die einen Teil der Erdoberfläche und die darauf befindlichen Einrichtungen beschreiben.

#formula-box[
*EVAP-Prinzip anwenden:*
1. *Erfassung*: GPS/GNSS (outdoor), WLAN/Bluetooth/SLAM (indoor), Digitalisierung, Fernerkundung
2. *Verwaltung*: Geodatenbank (PostgreSQL+PostGIS, Oracle, MySQL, DuckDB) mit Geodatentypen, Funktionen, 2D-Indexen
3. *Analyse*: Räumliche Abfragen, Verschneidungen, Puffer, Routing
4. *Präsentation*: Karte, Businessgrafik, Tabelle, Webkarte

*Beispiel:* Kebab-Restaurants in Rapperswil finden:
- E: OSM-Daten (Koordinaten + Tags)
- V: PostGIS-Datenbank mit Geometriespalte
- A: SQL-Abfrage mit ST_Distance / Bounding Box Filter
- P: Webkarte mit Leaflet oder GeoJSON auf geojson.io
]

==== Datenschutz-Hinweis (Indoor-Lokalisierung)

#warn-box[
*Datenschutz bei Geodaten:* Studie von Montjoye et al. zeigt: nur *4 räumlich-zeitliche Datenpunkte* (Zeit + Ort) reichen, um 95% aller Menschen in einem "anonymen" Datensatz eindeutig zu identifizieren. Indoor-Lokalisierung (ARKit/ARCore) liefert tausende solcher Punkte pro Minute — scheinbar anonyme Bewegungsdaten sind faktisch personenbezogen.
]

---

=== 3. Koordinatenreferenzsysteme (KRS/CRS)

*Kernidee:* Die Erde ist eine Kugel (genauer: ein Geoid/Ellipsoid), Bildschirme und Karten sind flach — eine Projektion bildet die gekrümmte Oberfläche auf eine 2D-Ebene ab. Jedes Koordinatensystem hat einen standardisierten EPSG-Code.

==== Abstraktionshierarchie

$ "Geoid" arrow.r "Erdellipsoid" arrow.r "Lokales Ellipsoid" arrow.r "Projektion" arrow.r "2D-Koordinaten" $

*Synonyme:* KRS, KBS, CRS (coordinate reference system), SRS (spatial reference system), SRID (spatial reference system ID)

==== Die drei wichtigsten Koordinatensysteme

#formula-box[
*Die drei Standard-CRS im Überblick:*

*1. WGS84 — EPSG:4326 ("GPS-Koordinaten")*
- Art: geozentrisch, geografisch, in Grad
- Format: Breitengrad/Längengrad (lat/lon) — Reihenfolge: erst N, dann E
- Beispiel: 47.223, 8.817 (Rapperswil)
- Verwendung: GPS, GeoJSON-Standard, Datenaustausch

*2. Web Mercator — EPSG:3857 ("Online-Karten")*
- Art: kartesisch (eben), metrisch
- Beispiel: 981523, 5978698
- Verwendung: Google Maps, OpenStreetMap, alle Online-Karten
- Problem: Flächenverzerrung in hohen Breitengraden → nicht für militärische/präzise Anwendungen

*3. CHLV95 — EPSG:2056 ("Schweizer Koordinaten")*
- Art: kartesisch-metrisch, Landesvermessung CH
- Format: 7-stellige Koordinaten, E/N
- Beispiel: 2'704'404, 1'231'247
- Verwendung: Alle offiziellen Schweizer Geodaten (swisstopo etc.)
]

#tip-box[
*CRS erkennen und unterscheiden:*
- Koordinaten mit Dezimalgrad (z.B. 47.2, 8.8) → WGS84 (EPSG:4326)
- 6-7-stellige Zahlen in Millionen (z.B. 981523) → Web Mercator (EPSG:3857)
- 7-stellige Koordinaten mit "2'7xx'xxx" / "1'2xx'xxx" → CHLV95 (EPSG:2056)
- Faustregel: lat/lon-Koordinaten immer auf 5 Stellen runden (nicht 16-stellig speichern!)
- Tool: https://map.geo.admin.ch zeigt Koordinaten in allen Systemen
]

#warn-box[
*Häufige Fehler bei Koordinatensystemen:*
- *lon/lat vs. lat/lon verwechseln*: GeoJSON verwendet [lon, lat] (X, Y), GPS-Geräte oft lat, lon — immer prüfen!
- *Falsches CRS in der DB*: ST_Transform() vergessen → räumliche Abfragen liefern falsche Ergebnisse
- *Web Mercator für Flächenberechnungen*: Mercator verzerrt Flächen stark → für genaue Berechnungen WGS84 oder CHLV95 verwenden
- *SRID nicht gesetzt*: PostGIS-Geometrie ohne SRID ist unbrauchbar für räumliche Joins
]

==== CRS-Transformation in PostGIS

```sql
-- Transformation von beliebigem CRS nach WGS84 (für Visualisierung)
SELECT ST_Transform(geom, 4326) AS geom_wgs84
FROM meine_tabelle;
```

---

=== 4. Geodaten — Typen und Besonderheiten

*Kernidee:* Geodaten sind Daten mit Raumbezug. Sie sind komplexer als normale Daten, weil sie spezielle Datenstrukturen, Formate und Konsistenzbedingungen erfordern.

==== Formen von Geodaten

Geodaten können vorliegen als:
- Geografische *Namen* (z.B. "Garnhänke Rapperswil")
- *Adressen* (Post-/Gebäudeadressen)
- *Codes* (z.B. Pluscode "6RF8+94")
- *Geometrien*: Punkte (Koordinaten), Linien (LineString), Flächen (Polygon)
- *Pixel/Voxel* (Rasterdaten)

==== Warum sind Geodaten besonders?

- *Komplexe Datenstruktur* → viele Formate
- *Komplexe Konsistenzbedingungen* (reale Welt ist kompliziert)
- *Grosser Erfassungsaufwand* (terrestrisch, Luftbild, LiDAR)
- *Grosse Datenmengen* (Big Data: Google Earth Engine = Petabytes)
- *Metadaten* notwendig: CRS, Auflösung, Qualität, Semantik

==== Geo-Metadaten

Zu Geodaten gehören immer Metadaten:
- *Koordinatensystem* (SRID/EPSG-Code)
- *Metrik/Masseinheiten* (Grad oder Meter?)
- *Granularität/Auflösung* (Auflösung am Boden in cm/px)
- *Semantik* ("Was ist ein Gebäude?" — administrative Definition!)

---

=== 5. Vektor- vs. Rasterdaten

*Kernidee:* Es gibt zwei grundlegende Arten, geografische Phänomene digital zu repräsentieren — als diskrete Vektorobjekte oder als kontinuierliches Rasterfeld.

==== Zwei Modellsichten

*Diskrete Entitäten-/Objekte-Sicht:*
- Räumlich begrenzte Objekte (z.B. ein Gebäude, eine Strasse)
- Natürlich als Vektordaten modelliert

*Kontinuierliche Felder-Sicht:*
- Überall im Raum gibt es einen Wert (z.B. Luftdruck, Temperatur)
- Natürlich als Rasterdaten modelliert

==== Vektordaten

Vektordaten bestehen aus:
- *Geometrie*: Punkt (Point), Linie (LineString), Fläche (Polygon) — mit Koordinaten
- *Topologie*: Nachbarschaftsbeziehungen (wichtig für Navigation, Routing)
- *Sachdaten* (Attribute/Thematische Daten): z.B. Name, Kategorie, Länge

*Typische Struktur (Feature Class):*
- Eine Tabelle mit *genau einem Geometrie-Attribut* + beliebig viele Sachdaten-Attribute

==== Rasterdaten

- Zusammengehörige Menge von (Farb-)Pixeln mit Raumbezug (georeferenziert)
- Erfasst durch CCD/CMOS-Sensoren (Scanner, Kameras, Satelliten)
- Format: GeoTIFF (Standard)
- Jeder Pixel hat einen (Farb-)Wert

#cheat-box[
*Vektor vs. Raster — wann was?*

| Kriterium | Vektordaten | Rasterdaten |
|---|---|---|
| Objekttyp | diskrete Objekte | kontinuierliche Felder |
| Einzeln ansprechbar? | Ja | Nein (nur Pixel) |
| Skalierbar? | Ja (verlustfrei) | Nein (verpixelt) |
| Darstellung | langsamer (berechnet) | schneller |
| Herstellung | teurer | billiger |
| Typisches Format | GeoJSON, GeoPackage | GeoTIFF |
| Beispiel | Strasse, Gebäude, POI | Luftbild, Temperaturkarte |
| Übung in diesem Kurs | Hauptthema ✓ | kurz (Google Earth Engine) |
]

---

=== 6. GIS-Prinzipien der Geoinformationsverarbeitung

==== Ebenenprinzip / Layerprinzip

*Kernidee:* Geodaten werden in thematischen Schichten (Layers) organisiert. Das gemeinsame Koordinatensystem erlaubt den Lagevergleich zwischen unabhängigen Datenquellen — das ist die eigentliche Stärke von GIS.

```
GIS
├── Layer: BEVÖLKERUNG
├── Layer: KLIMADATEN
├── Layer: LANDNUTZUNG
├── Layer: VERMESSUNG
└── Layer: VERSORGUNGSNETZE
```

*Koordinaten ermöglichen vertikalen Lagevergleich* — man kann Objekte aus verschiedenen Layern räumlich verknüpfen ohne explizite Fremdschlüssel.

==== Raumbezug als universeller Fremdschlüssel

*Kernidee:* Koordinaten ersetzen in GIS den klassischen Datenbank-Fremdschlüssel. Jedes Objekt mit denselben Koordinaten (im selben CRS) kann mit jedem anderen Objekt verknüpft werden — auch wenn die Daten aus völlig unterschiedlichen Quellen stammen.

#tip-box[
*Räumlicher Join (Spatial Join):*
Statt `WHERE a.id = b.fk_id` wird verknüpft mit räumlichen Prädikaten:
- `ST_Intersects(a.geom, b.geom)` — überschneiden sich?
- `ST_Within(a.geom, b.geom)` — a liegt innerhalb von b?
- `ST_DWithin(a.geom, b.geom, distanz)` — a liegt maximal X Meter von b entfernt?

*Data Enrichment:* Adressen + Koordinaten = Geocoding; Punkte + Bezirksgrenzen = sozioökonomische Daten zuweisen.
]

==== Grafik-View-Prinzip

- Geodaten sind in der Datenbank *grafiklos* gespeichert (nur Koordinaten + Attribute)
- Die Grafik (Styling: Farbe, Breite, Beschriftung) wird *real-time* aus der DB extrahiert und gerendert
- Trennung: Daten ≠ Darstellung (wie bei Web: HTML ≠ CSS)

*Beispiel Autobahn A1:*
- Daten: `{type: LineString, coordinates: [...], name: "A1"}`
- Grafik: `{Farbe: Grün, Breite: 3mm, Beschriftung: "A1", Schrift: Helvetica}`

==== Massstabsabhängige Darstellung (GIS-Zoom)

- Bei kleinem Massstab (weit weg gezoomt): wenige, vereinfachte Objekte
- Bei grossem Massstab (nah herangezoomt): mehr Details, mehr Objekte
- Automatische Generalisierung: Gebäude werden zu Punkten, Linien vereinfacht

==== Mengenabhängige Darstellung

- Viele Punkte auf einer Karte → *Point Clustering* (Punkte werden zu Cluster-Symbolen gruppiert)
- Verhindert "überladene" Karten bei grossen Datensätzen

---

=== 7. GIS-Dateiformate

*Kernidee:* Geodaten existieren in vielen Formaten — die Wahl des Formats hängt von Verwendungszweck, Komplexität der Geometrie und Interoperabilität ab.

==== Vektorformate

#cheat-box[
*Welches Format wählen?*

*GeoJSON* — Standard für Web und Datenaustausch
- Textbasiert (JSON), menschenlesbar
- Struktur: `FeatureCollection` → `features[]` → `{geometry, properties}`
- Koordinaten immer in WGS84 (EPSG:4326), Reihenfolge: [lon, lat]
- Validierung: geojson.io oder http://geojsonlint.com
- ⚠ Koordinaten auf 5 Stellen runden (nicht 16-stellig!)

*GeoPackage (.gpkg)* — Standard für Desktop-GIS
- SQLite-Datenbank als Datei
- Binärformat; unterstützt Vektor- UND Rasterdaten
- Nachfolger des Shapefile (empfohlen!)

*Shapefile (.shp + .dbf + ...)* — Legacy-Format
- Mind. 2 Dateien: Geometrie (.shp) + Sachdaten (.dbf)
- Weit verbreitet aber veraltet → vermeiden! (http://switchfromshapefile.org)

*CSV* — nur für Punkte
- Geeignet wenn Attribute `lat` und `lon` vorhanden
- Für Linien/Polygone: WKT-String-Spalte verwenden (z.B. `"LINESTRING(10 10, 20 20)"`)

*DXF* — für reine Geometrie/CAD
- Kein Sachdaten-Support; von AutoCAD
- Nur wenn CAD-Austausch nötig

*GeoParquet* — für Big Data
- Erweiterung von Apache Parquet (spaltenorientiert)
- Effiziente Komprimierung, schnelle Abfragen auf grossen Datensätzen
]

==== Rasterformate

- *GeoTIFF* → Standard für Raster-Geodaten-Austausch (georeferenziert)
- *PNG/JPG* → nur mit Zusatzdatei "Worldfile" georeferenziert
- *PDF* → für Drucker, nicht für GIS-Verarbeitung

==== WKT (Well-Known Text) — Geometrie als Text

```
Punkt:   POINT(8.817 47.223)
Linie:   LINESTRING(8.81 47.22, 8.82 47.23, 8.83 47.24)
Fläche:  POLYGON((8.81 47.22, 8.82 47.22, 8.82 47.23, 8.81 47.22))
```

---

=== 8. GIS-Architekturen und Produkte

*Kernidee:* GIS-Systeme sind aufgeteilt in ein *Basissystem* (Werkzeugkasten mit GIS-Funktionen) und *Fachschalen* (domänenspezifische Applikationen darüber).

==== Desktop-GIS

*QGIS* (Open Source, GPL)
- Windows, macOS, Linux
- Empfohlen für diese Vorlesung
- Mobile Variante: QField

*ArcGIS* (kommerziell, ESRI)
- ArcGIS Pro (Desktop) + ArcGIS Online (Cloud)
- Marktführer im professionellen Bereich

==== Geodatenbanken

Alle bekannten DBMS unterstützen Geodaten:
- *PostgreSQL + PostGIS* (Open Source, empfohlen)
- Oracle Spatial, MS SQL Server (kommerziell)
- MySQL/MariaDB, DuckDB, SQLite/GeoPackage

Geodatenbanken bieten:
- Geodatentypen (Geometry, Geography)
- Räumliche Funktionen (`ST_*`)
- Spezielle 2D-Indexe (R-Tree / GiST-Index)

==== Web Mapping (No-Code bis Low-Code)

*Für Datenanalysten/Journalisten:*
- *Datawrapper* — beliebt bei Journalisten, einfach
- *uMap* — Open Source, basiert auf OSM
- *Felt* — "Google Docs für Karten"
- *map.geo.admin.ch* — Schweizer Behördendaten

*Für Software Engineers (JS/Python):*
- JavaScript: Leaflet, MapLibre (beide empfohlen), OpenLayers
- Python Backend: GeoPandas, Shapely, OSMnx
- Jupyter: matplotlib + Overpass-API

==== Geovisualisierung für SQL-Entwickler

```sql
-- In pgAdmin 4: Geometry Viewer Button
-- Voraussetzung: Geometrie muss in EPSG:4326 sein!
SELECT ST_Transform(geom, 4326) AS geom
FROM meine_tabelle;
```

---

=== 9. OpenStreetMap und PostPASS

*Kernidee:* OpenStreetMap (OSM) ist die grösste freie Geodatenbank der Welt — mit über 100 Mio. Nutzern, Milliarden Gebäuden und 70 Mio. Points-of-Interest. PostPASS ermöglicht SQL-Abfragen direkt auf OSM-Daten.

==== OSM-Datenstruktur

OSM speichert Geodaten als *Tags* (Key-Value-Paare):
- `amenity=restaurant` — ein Restaurant
- `amenity=fast_food` + `cuisine=kebab` — ein Kebab-Imbiss
- `amenity=drinking_water` — ein Trinkwasserbrunnen

==== PostPASS-Abfrage (Praxis-Rezept)

#formula-box[
*Rezept: OSM-Daten mit PostPASS abfragen*

1. URL: https://overpass-turbo.eu mit PostPASS-Header
2. Header: `{{data:sql,server=https://postpass.geofabrik.de/api/0.2/}}`
3. SQL schreiben mit OSM-Tabellen und PostGIS-Funktionen

*Allgemeines Query-Muster:*
```sql
SELECT
    osm_id,
    tags->>'name'       AS name,
    tags->>'[tag-key]'  AS attribut,
    ST_PointOnSurface(geom) AS geom
FROM postpass_pointpolygon
WHERE tags->>'amenity' IN ('[kategorie1]', '[kategorie2]')
AND tags->>'[filter-key]' = '[filter-wert]'
AND geom && {{bbox}};
```

*Erklärung der Schlüsselelemente:*
- `tags->>'key'` → extrahiert Wert aus JSON-Tags-Spalte
- `ST_PointOnSurface(geom)` → konvertiert Polygone zu Punkten (für einheitliche Darstellung)
- `{{bbox}}` → Template-Variable für sichtbaren Kartenausschnitt (wird zu `ST_MakeEnvelope(...)`)
- `geom && {{bbox}}` → Bounding-Box-Filter (schnell, nutzt Index)
- `string_to_array(tags->>'cuisine', ';') @> '{kebab}'` → prüft ob 'kebab' in einer ';'-getrennten Liste vorkommt
- Kein Semikolon am SQL-Ende!

*Beispiel: Kebab-Restaurants in Sichtbereich*
```sql
SELECT
    osm_id,
    tags->>'name'    AS name,
    tags->>'cuisine' AS cuisine,
    ST_PointOnSurface(geom) AS geom
FROM postpass_pointpolygon
WHERE tags->>'amenity' IN ('fast_food', 'restaurant')
AND string_to_array(tags->>'cuisine', ';') @> '{kebab}'
AND geom && {{bbox}}
```
]

#tip-box[
*OSM-Tags für die Übung (Brunnen):*
- `amenity=drinking_water` — Trinkwasserbrunnen
- `amenity=fountain` — Zierbrunnen
- `amenity=water_point` — Wasserstelle
- `man_made=water_well` — Brunnen/Quelle
- `man_made=water_tap` — Wasserhahn

*OSM-Tags finden:* tagfinder.osm.ch
]

---

=== 10. Lösungsrezept für die Übungsaufgabe "Raumanalyse Vektordaten: Autobahn"

*Kernidee der Übung:* Vektordaten (Autobahnen aus OSM) werden geladen, visualisiert und räumlich analysiert — typische Operationen: Filtern, Puffer erzeugen, Verschneiden, Attribute berechnen.

#formula-box[
*Allgemeines Rezept: Räumliche Vektoranalyse in QGIS*

*Schritt 1: Daten beschaffen*
- OSM-Daten über Overpass API oder PostPASS herunterladen
- Format prüfen (GeoJSON, GeoPackage, Shapefile)
- CRS prüfen (meist WGS84/EPSG:4326 aus OSM)

*Schritt 2: Daten in QGIS laden und prüfen*
- Layer hinzufügen (`Layer > Datei hinzufügen`)
- Attributtabelle öffnen — welche Spalten gibt es?
- CRS des Layers prüfen (rechts unten im QGIS-Fenster)

*Schritt 3: Daten filtern/selektieren*
- Nach Attributen filtern: `Rechtsklick Layer > Eigenschaften > Abfrage-Generator`
- Beispiel Autobahn: `"highway" = 'motorway'`

*Schritt 4: Räumliche Analyse*
- *Puffer*: `Vektor > Geoverarbeitungswerkzeuge > Puffer`
  - Eingabe: Linienlayer
  - Distanz: z.B. 500m (→ CRS muss metrisch sein!)
- *Verschneidung* (Intersection): `Vektor > Geoverarbeitungswerkzeuge > Verschneidung`
  - Welche Objekte liegen innerhalb des Puffers?
- *Längenberechnung*: `Feldrechner` → `$length` (in CRS-Einheiten)

*Schritt 5: Ergebnis visualisieren*
- Styling anpassen (Farbe, Linienbreite, Beschriftung)
- Als Karte exportieren oder als GeoJSON speichern

*Schritt 6: Ergebnis interpretieren*
- Was zeigt die Analyse? Welche Schlüsse können gezogen werden?
]

#warn-box[
*Häufige Fehler bei Vektordatenanalysen:*
- *CRS-Mismatch*: Zwei Layer mit verschiedenen CRS werden nicht korrekt überlagert → immer auf gleiches CRS reprojizieren (in QGIS: `Rechtsklick > Layer CRS > Auf CRS reprojizieren`)
- *Distanz in Grad statt Meter*: Puffer mit 500 in WGS84 = 500 Grad = falsch! → Zuerst auf metrisches CRS (z.B. EPSG:2056 oder EPSG:3857) umprojizieren
- *Topologiefehler*: Ungültige Geometrien (self-intersecting Polygone) → `Vektor > Geometriewerkzeuge > Geometrien reparieren`
- *Attribut-Encoding*: Umlaute werden falsch dargestellt → UTF-8 Encoding sicherstellen
]

---

=== 11. Datenquellen für Geodaten

#cheat-box[
*Wichtige Geodatenquellen:*

| Quelle | Inhalt | Lizenz |
|---|---|---|
| OpenStreetMap (OSM) | Weltweit; POIs, Strassen, Gebäude | ODbL (frei) |
| swisstopo / map.geo.admin.ch | Schweiz; amtliche Geodaten | meist frei |
| Overture Maps | MS, Amazon, TomTom; Karten | offen |
| Google Maps / Earth Engine | Weltweit; Raster + POIs | kommerziell |
| Geoportal Kantone/Gemeinden | CH; Pläne, Zonen | variiert |

*Zugang zu OSM-Daten:*
- Overpass API / overpass-turbo.eu (für kleine Abfragen)
- PostPASS (für SQL-Abfragen, Kursumgebung)
- Geofabrik.de (Dump-Downloads nach Land/Region)
- OSMnx (Python-Library)
]

---

=== Zusammenfassung: Konzeptlandkarte