// Auto-generated by RAG system on 2026-04-23
// Week 3 — do not edit the header

#import "../../template.typ": tip-box, warn-box, formula-box, cheat-box

== Woche 3: Numerische Berechnung & Gradientenbasierte Optimierung

= Überblick

Diese Woche verbindet zwei Themen: *numerische Stabilität* (was kann beim Rechnen auf dem Computer schiefgehen?) und *gradientenbasierte Optimierung* (wie minimiert man eine Verlustfunktion?). Das Herzstück des Deep Learning — das Trainieren eines Netzes — ist ein Optimierungsproblem, das mit diesen Werkzeugen gelöst wird.

---

== 1. Numerische Probleme

=== 1.1 Quantisierung und Rundungsfehler

*Kernidee:* Computer können keine beliebigen reellen Zahlen speichern — nur endlich viele diskrete Werte. Jede Zahl wird auf den nächsten darstellbaren Wert gerundet.

Bei $b$ Bits und Wertebereich $[-R/2, R/2]$ gilt:

$ Q = frac(R, 2^b) $

Schrittweite $Q$: je kleiner, desto genauer. Akkumulierte Rundungsfehler über viele Operationen können erheblich sein.

=== 1.2 Underflow und Overflow

*Kernidee:* Zu kleine Zahlen werden zu $0$ gerundet (Underflow), zu grosse zu $infinity$ (Overflow). Beides kann Folgeberechnungen zerstören.

#warn-box[
*Underflow:* $x arrow.r 0$, dann bricht $1/x$ oder $log(x)$ zusammen (Division durch Null / $log(0) = -infinity$).

*Overflow:* $x arrow.r infinity$, dann ist jede weitere Rechenoperation undefiniert.

*Typischer Denkfehler:* "Underflow ist harmlos, weil die Zahl einfach null wird." — Falsch! Die *Folgeoperationen* sind das Problem.
]

=== 1.3 Stabilisierung der Softmax-Funktion

*Kernidee:* Die Softmax-Funktion für $K$ Klassen:

$ "softmax"(bold(x))_i = frac(exp(x_i), sum_(j=1)^K exp(x_j)) $

ist anfällig für Over- und Underflow, wenn alle $x_i = c$ mit sehr grossem oder sehr kleinem $c$.

#tip-box[
*Erkennungsmerkmal:* Aufgabe fragt nach numerischer Stabilität der Softmax — oder man implementiert sie von Hand ohne Framework.

*Stabilisierung:* Subtrahiere $k = max_i(x_i)$ von allen Eingaben:

$ "softmax"(bold(x))_i = frac(exp(x_i - k), sum_j exp(x_j - k)) $

*Warum funktioniert das?*
- Der grösste Exponent wird zu $exp(0) = 1$ — kein Overflow.
- Alle anderen Exponenten sind negativ — kein Overflow.
- Der Nenner ist mindestens $1$ — kein $0/0$-Problem.
- Das Ergebnis ist mathematisch identisch (kürzen von $exp(k)$).
]

#warn-box[
*log-Softmax braucht separate Stabilisierung!* Auch nach der Softmax-Stabilisierung kann $log("softmax"(bold(x))_i)$ noch underflowgefährdet sein, weil stabilisierte Softmax-Werte nahe $0$ liegen können. Moderne Frameworks (PyTorch, TensorFlow) behandeln das automatisch.
]

=== 1.4 Poor Conditioning (Schlechte Konditionierung)

*Kernidee:* Eine schlecht konditionierte Funktion verstärkt kleine Fehler in der Eingabe zu grossen Fehlern im Output.

*Konditionszahl einer Matrix $bold(A)$:*

$ kappa(bold(A)) = frac(lambda_max, lambda_min) $

wobei $lambda_max$ und $lambda_min$ der grösste bzw. kleinste Eigenwert von $bold(A)$ sind.

#cheat-box[
- $kappa approx 1$ $arrow.r$ gut konditioniert, Fehler bleiben gleich gross
- $kappa >> 1$ (z.B. $> 10000$) $arrow.r$ schlecht konditioniert, Fehler werden verstärkt
- $bold(A)$ und $bold(A)^(-1)$ haben (unter vernünftigen Annahmen) dieselbe Konditionszahl
]

---

== 2. Gradientenbasierte Optimierung

=== 2.1 Kernidee

*Training = Minimierung einer Verlustfunktion.* Wir minimieren die Kreuzentropie zwischen der empirischen Datenverteilung $hat(p)_"data"$ und der Modellverteilung $p_"model"(bold(theta))$:

$ min_(bold(theta)) H(hat(p)_"data", p_"model"(bold(theta))) $

Das Werkzeug dafür: Gradientenabstieg.

=== 2.2 Skalarfall: Ableitung und Gradient Descent

Für $f: RR arrow.r RR$:

- *Ableitung* $f'(x)$ = Steigung der Funktion an Stelle $x$
- Negative Ableitung $arrow.r$ Funktion fällt in positive Richtung
- Nullstelle der Ableitung $arrow.r$ kritischer Punkt

*Update-Regel (Gradient Descent, 1D):*

$ x^((i)) = x^((i-1)) - epsilon dot f'(x^((i-1))) $

=== 2.3 Vektorfall: Gradient

Für $f: RR^n arrow.r RR$, Vektor-Eingabe $bold(x)$:

$ nabla_(bold(x)) f(bold(x)) = mat(frac(partial f(bold(x)), partial x_1); frac(partial f(bold(x)), partial x_2); dots.v; frac(partial f(bold(x)), partial x_n)) $

*Update-Regel (Gradient Descent, n-dimensional):*

$ bold(x)^((i)) = bold(x)^((i-1)) - epsilon dot nabla_(bold(x)) f(bold(x)^((i-1))) $

#tip-box[
*Woran erkenne ich Gradient Descent in einer Aufgabe?*
- "Suche ein Minimum mit der Methode des steilsten Abstiegs"
- "Führe $k$ Iterationen durch, Startpunkt $bold(x)^((0))$, Lernrate $epsilon$"
- Gegeben: Verlustfunktion $f(bold(x))$, Startpunkt, Lernrate
]

#formula-box[
*Rezept: Steepest Descent (Gradientenabstieg)*

+ Berechne den Gradienten $nabla_(bold(x)) f(bold(x))$ analytisch (alle partiellen Ableitungen)
+ Setze Startpunkt $bold(x)^((0))$ ein
+ Berechne $nabla_(bold(x)) f(bold(x)^((0)))$
+ Update: $bold(x)^((1)) = bold(x)^((0)) - epsilon dot nabla_(bold(x)) f(bold(x)^((0)))$
+ Wiederhole Schritte 3–4 für $k$ Iterationen

*Beispiel:* $f(bold(x)) = x_1^2 + x_2^2$, $bold(x)^((0)) = mat(2; 1)$, $epsilon = 0.1$

Gradient: $nabla f = mat(2 x_1; 2 x_2)$

Am Startpunkt: $nabla f(bold(x)^((0))) = mat(4; 2)$

Update: $bold(x)^((1)) = mat(2; 1) - 0.1 dot mat(4; 2) = mat(1.6; 0.8)$
]

=== 2.4 Lernrate $epsilon$

#cheat-box[
- $epsilon$ zu klein $arrow.r$ Konvergenz sehr langsam
- $epsilon$ zu gross $arrow.r$ Überspringen des Minimums, Divergenz möglich
- Optimale Lernrate: problem- und datenabhängig, wird später automatisch gelernt
]

=== 2.5 Richtungsableitung

*Kernidee:* Statt partiell entlang Achsen abzuleiten — Ableitung in *beliebiger Richtung* $bold(u)$ (Einheitsvektor):

$ frac(partial f(bold(x) + alpha bold(u)), partial alpha) = bold(u)^T nabla_(bold(x)) f(bold(x)) $

*In welche Richtung soll man gehen, um $f$ am stärksten zu verkleinern?*

Mit $bold(a)^T bold(b) = norm(bold(a)) norm(bold(b)) cos(theta)$ und $norm(bold(u)) = 1$:

$ min_(bold(u)) bold(u)^T nabla f = min_(bold(u)) norm(nabla f) cos(theta) $

Minimum bei $cos(theta) = -1$, also $theta = 180°$ $arrow.r$ *entgegen dem Gradienten*.

#tip-box[
- *Gradient* = Richtung des steilsten Anstiegs
- *Negativer Gradient* = Richtung des steilsten Abstiegs
- Gradient Descent folgt immer dem negativen Gradienten
]

=== 2.6 Kritische Punkte

Kritische Punkte (stationäre Punkte): $nabla_(bold(x)) f(bold(x)) = bold(0)$

Gradient Descent terminiert an kritischen Punkten, kann aber in lokalen Minima oder Sattelpunkten stecken bleiben.

---

== 3. Jacobi-Matrix

*Kernidee:* Verallgemeinerung des Gradienten auf vektorwertige Funktionen $f: RR^m arrow.r RR^n$.

$ bold(J) = mat(frac(partial f_1, partial x_1), frac(partial f_1, partial x_2), dots, frac(partial f_1, partial x_m); frac(partial f_2, partial x_1), frac(partial f_2, partial x_2), dots, frac(partial f_2, partial x_m); dots.v, dots.v, dots.down, dots.v; frac(partial f_n, partial x_1), frac(partial f_n, partial x_2), dots, frac(partial f_n, partial x_m)) $

Dimension: $n times m$ (Zeile $i$ = Gradient von $f_i(bold(x))$).

#tip-box[
*Wann brauche ich die Jacobi-Matrix?*
- Funktion hat Vektor-Eingabe *und* Vektor-Ausgabe
- Typische Anwendung: Ableitung der Softmax-Funktion, Backpropagation
]

---

== 4. Hessian-Matrix

=== 4.1 Definition

*Kernidee:* Die Hessian-Matrix enthält alle zweiten partiellen Ableitungen von $f: RR^n arrow.r RR$ — sie ist die Jacobi-Matrix des Gradienten.

$ bold(H)(f)(bold(x)) = mat(frac(partial^2 f, partial x_1^2), frac(partial^2 f, partial x_1 partial x_2), dots, frac(partial^2 f, partial x_1 partial x_n); frac(partial^2 f, partial x_2 partial x_1), frac(partial^2 f, partial x_2^2), dots, frac(partial^2 f, partial x_2 partial x_n); dots.v, dots.v, dots.down, dots.v; frac(partial^2 f, partial x_n partial x_1), frac(partial^2 f, partial x_n partial x_2), dots, frac(partial^2 f, partial x_n^2)) $

Die Hessian-Matrix ist *symmetrisch* $arrow.r$ reelle Eigenwerte, Eigenzerlegung möglich:

$ bold(H) = bold(V) bold(Lambda) bold(V)^T $

wobei $bold(V)$: Matrix der Eigenvektoren, $bold(Lambda)$: Diagonalmatrix der Eigenwerte $lambda_i$.

=== 4.2 Krümmung und Eigenwerte

*Zweite Richtungsableitung in Richtung $bold(d)$:*

$ bold(d)^T bold(H) bold(d) $

- Falls $bold(d)$ ein Eigenvektor: $bold(d)^T bold(H) bold(d) = lambda$ (Eigenwert = Krümmung in dieser Richtung)
- Für beliebige Richtung: $bold(d)^T bold(H) bold(d) = sum_i cos^2(theta_i) lambda_i$

$ "Maximale Krümmung" = lambda_max "in Richtung" bold(v)_max $
$ "Minimale Krümmung" = lambda_min "in Richtung" bold(v)_min $

=== 4.3 Zweiter Ableitungstest

#formula-box[
*Rezept: Kritischen Punkt klassifizieren*

+ Berechne Gradient $nabla f(bold(x))$ und setze $= bold(0)$
+ Löse das Gleichungssystem $arrow.r$ kritische Punkte $bold(c)_i$
+ Berechne Hessian $bold(H)(f)(bold(x))$
+ Setze jeden kritischen Punkt $bold(c)_i$ in $bold(H)$ ein
+ Bestimme Eigenwerte von $bold(H)(f)(bold(c)_i)$
+ Klassifiziere nach Tabelle unten

*Beispiel (2D):* $f(bold(x)) = x_1^2 + x_2^2$

Gradient: $nabla f = mat(2x_1; 2x_2) = bold(0)$ $arrow.r$ kritischer Punkt $bold(c) = mat(0; 0)$

Hessian: $bold(H) = mat(2, 0; 0, 2)$, Eigenwerte: $lambda_1 = lambda_2 = 2 > 0$ $arrow.r$ *lokales Minimum*
]

#cheat-box[
*Zweiter Ableitungstest — Entscheidungstabelle:*

#table(
  columns: (auto, auto, auto),
  [*Kritischer Punkt*], [*1D: $f''(x)$*], [*nD: Eigenwerte von $bold(H)$*],
  [Lokales Minimum], [$> 0$], [Alle positiv],
  [Lokales Maximum], [$< 0$], [Alle negativ],
  [Sattelpunkt], [$= 0$ (inconclusive)], [Gemischt (mind. ein pos., ein neg.)],
  [Inconclusive], [$= 0$], [Alle gleich vorzeichig, mind. einer $= 0$],
)
]

#warn-box[
*Häufiger Fehler:* Wenn ein Eigenwert $= 0$ ist und die anderen alle positiv (oder alle negativ), ist der Test *nicht conclusive*. Man muss höhere Ableitungen analysieren oder die Funktion direkt auswerten.

*Sattelpunkte in hohen Dimensionen:* Bei $n = 1'000'000$ Parametern hat $bold(H)$ eine Million Eigenwerte. Schon *ein* negativer Eigenwert macht den Punkt zum Sattelpunkt — kein Minimum!
]

=== 4.4 Globales Minimum finden

#tip-box[
*Vorgehen:*
+ Alle kritischen Punkte bestimmen (Gradient = 0)
+ Typ bestimmen (Hessian-Eigenwerte)
+ Nur lokale Minima als Kandidaten behalten
+ Funktionswert $f(bold(c)_i)$ für alle lokalen Minima berechnen
+ Kleinster Wert = globales Minimum

*Sattelpunkte und Maxima können ignoriert werden* — sie können nie das globale Minimum sein.
]

---

== 5. Newton's Method (Zweiter-Ordnung-Optimierung)

*Kernidee:* Statt nur den Gradienten zu nutzen, benutze auch die Hessian-Matrix um den Schritt zu skalieren — berücksichtigt die lokale Krümmung.

*Update-Regel Newton's Method:*

$ bold(x)^((i)) = bold(x)^((i-1)) - bold(H)(f)(bold(x)^((i-1)))^(-1) nabla_(bold(x)) f(bold(x)^((i-1))) $

#formula-box[
*Rezept: Newton's Method*

+ Berechne Gradient $nabla f(bold(x))$ analytisch
+ Berechne Hessian $bold(H)(f)(bold(x))$ analytisch
+ Setze aktuellen Punkt $bold(x)^((i-1))$ ein
+ Berechne $bold(H)^(-1) nabla f$ (Hessian invertieren, mit Gradient multiplizieren)
+ Update: $bold(x)^((i)) = bold(x)^((i-1)) - bold(H)^(-1) nabla f$
+ Wiederholen

*Beispiel (diagonal Hessian, 2D):*

$ bold(H) = mat(h_(11), 0; 0, h_(22)) arrow.r bold(H)^(-1) = mat(frac(1, h_(11)), 0; 0, frac(1, h_(22))) $

Update für jede Komponente separat:

$ x_1^((i)) = x_1^((i-1)) - frac(frac(partial f, partial x_1), frac(partial^2 f, partial x_1^2)) $
]

#warn-box[
*Newton's Method und Sattelpunkte:* Newton's Method konvergiert zu kritischen Punkten — das können auch Sattelpunkte oder lokale Maxima sein! In der Übung fand Newton's Method Sattelpunkte, während Gradient Descent das globale Minimum fand. Newton's Method ist *schneller* (konvergiert in weniger Schritten), aber nicht notwendigerweise zu einem Minimum.
]

#cheat-box[
*Vergleich Gradient Descent vs. Newton's Method:*

#table(
  columns: (auto, auto, auto),
  [*Eigenschaft*], [*Gradient Descent*], [*Newton's Method*],
  [Nutzt], [1. Ableitung (Gradient)], [1. + 2. Ableitung (Hessian)],
  [Lernrate], [Manuell $epsilon$], [Automatisch durch $bold(H)^(-1)$],
  [Konvergenz], [Langsamer], [Schneller (quadratisch)],
  [Sattelpunktgefahr], [Geringer], [Höher (wird angezogen)],
  [Rechenaufwand], [Niedrig],  [Hoch ($bold(H)$ invertieren)],
)
]

---

== 6. Taylor-Approximation zweiter Ordnung

*Kernidee:* Jede glatte Funktion kann lokal um einen Punkt $bold(x)^((0))$ durch ein Polynom approximiert werden.

*1D:*
$ f(x) approx f(x^((0))) + frac(f'(x^((0))), 1!) (x - x^((0))) + frac(f''(x^((0))), 2!) (x - x^((0)))^2 $

*n-dimensional:*
$ f(bold(x)) approx f(bold(x)^((0))) + (bold(x) - bold(x)^((0)))^T bold(g) + frac(1, 2) (bold(x) - bold(x)^((0)))^T bold(H) (bold(x) - bold(x)^((0))) $

mit $bold(g) = nabla_(bold(x)) f(bold(x)^((0)))$ (Gradient) und $bold(H) = bold(H)(f)(bold(x)^((0)))$ (Hessian).

=== Analyse eines Gradient-Descent-Schritts

Nach einem Schritt $bold(x)^((0)) - epsilon bold(g)$:

$ f(bold(x)^((0)) - epsilon bold(g)) approx f(bold(x)^((0))) underbrace(- epsilon bold(g)^T bold(g), "negativ, gut") + underbrace(frac(1, 2) epsilon^2 bold(g)^T bold(H) bold(g), "Krümmungsterm") $

#cheat-box[
*Wirkung des Krümmungsterms $bold(g)^T bold(H) bold(g)$:*

#table(
  columns: (auto, auto, auto),
  [*$bold(g)^T bold(H) bold(g)$*], [*Krümmung*], [*Effekt auf Schritt*],
  [$lt.eq 0$], [Null/negativ], [Grosses $epsilon$ möglich, Abstieg garantiert],
  [$> 0$, klein], [Schwach positiv], [Schritt verkleinert $f$, aber weniger als erwartet],
  [$> 0$, gross], [Stark positiv], [Kann $f$ sogar *erhöhen* — Gradient Descent versagt!],
)

*Optimales $epsilon$ (wenn $bold(g)^T bold(H) bold(g) > 0$):*
$ epsilon^* = frac(bold(g)^T bold(g), bold(g)^T bold(H) bold(g)) $
]

---

== 7. Konditionszahl der Hessian und Optimierung

*Kernidee:* Die Konditionszahl $kappa = lambda_max / lambda_min$ der Hessian-Matrix sagt aus, wie unterschiedlich stark die Krümmungen in verschiedene Richtungen sind.

#cheat-box[
- *Kleines $kappa$:* Ähnliche Krümmung überall $arrow.r$ grosses $epsilon$ wählbar, schnelle Konvergenz
- *Grosses $kappa$:* Sehr unterschiedliche Krümmungen $arrow.r$ $epsilon$ muss klein sein (wegen der stark gekrümmten Richtung) $arrow.r$ langsamer Fortschritt in flachen Richtungen
- Das ist "poor conditioning" in der Optimierung
]

---

== 8. Vollständiges Lösungsrezept für Optimierungsaufgaben

#formula-box[
*Vollständiges Rezept: Von Verlustfunktion zum Minimum*

*Gegeben:* Verlustfunktion $f(bold(x))$, Startpunkt $bold(x)^((0))$, Lernrate $epsilon$ (für GD) oder Methode (Newton)

+ *Gradient berechnen:* Alle partiellen Ableitungen $frac(partial f, partial x_i)$
+ *Hessian berechnen:* Alle zweiten partiellen Ableitungen $frac(partial^2 f, partial x_i partial x_j)$
+ *Kritische Punkte finden:* $nabla f(bold(x)) = bold(0)$ lösen (oft als entkoppeltes System, wenn Kreuzableitungen $= 0$)
+ *Typ bestimmen:* Hessian an jedem kritischen Punkt auswerten $arrow.r$ Eigenwerte prüfen
+ *Globales Minimum:* $f(bold(c)_i)$ für alle lokalen Minima berechnen $arrow.r$ kleinster Wert
+ *Iterative Suche (GD):* $bold(x)^((i)) = bold(x)^((i-1)) - epsilon nabla f(bold(x)^((i-1)))$
+ *Iterative Suche (Newton):* $bold(x)^((i)) = bold(x)^((i-1)) - bold(H)^(-1) nabla f(bold(x)^((i-1)))$
+ *Konvergenz prüfen:* Ist gefundener Punkt ein lokales/globales Minimum? (Vergleich mit bekannten kritischen Punkten)
]

#warn-box[
*Die häufigsten Fehler bei Optimierungsaufgaben:*

1. *Gradient falsch berechnet* — besonders bei Termen mit $x_1 x_2$: Kreuzableitungen nicht vergessen!
2. *Hessian nicht symmetrisch* — bei korrekter Rechnung muss $frac(partial^2 f, partial x_i partial x_j) = frac(partial^2 f, partial x_j partial x_i)$ gelten
3. *Inconclusive Test ignoriert* — wenn Eigenwert $= 0$, ist der Test nicht abgeschlossen
4. *Newton konvergiert zu Sattelpunkt* — nicht jeder kritische Punkt ist ein Minimum!
5. *Lernrate zu gross* — der Gradient kann in die richtige Richtung zeigen, aber der Schritt überspringt das Minimum
6. *Nur lokales Minimum gefunden* — Startpunkt bestimmt, wohin GD konvergiert; für globales Minimum: mehrere Startpunkte versuchen
]