// Auto-generated by RAG system on 2026-05-09
// Week 7 — do not edit the header

#import "../../template.typ": tip-box, warn-box, formula-box, cheat-box

== Woche 7: Data Integration — ETL/ELT

=== Überblick und Lernziele

Diese Woche behandelt die *Datenintegration* als zentrales Handwerk der Data Analytics. Der Student soll verstehen, was Datenintegration bedeutet, welche Konflikte dabei auftreten, wie ETL- und ELT-Prozesse funktionieren, und wie Tools wie OpenRefine, Apache Hop und dbt eingesetzt werden.

---

== 1. Informations- und Datenintegration: Grundbegriffe

=== 1.1 Definition und Motivation

*Kernidee:* Datenintegration bedeutet, Daten aus verschiedenen, heterogenen Quellen korrekt, vollständig und effizient zu einer einheitlichen Informationsmenge zusammenzuführen.

#tip-box[
*Woran erkenne ich dieses Konzept in einer Aufgabe?*
- Mehrere Datenquellen mit unterschiedlichen Formaten/Strukturen sollen zusammengeführt werden
- Frage nach "Vorteilen/Nachteilen" von Integrationsansätzen
- Frage nach typischen Problemen bei der Datenintegration
]

Die *Zeitrealität der Praxis:* Data Scientists verbringen mindestens 60–80% ihrer Zeit mit Daten finden, bereinigen und integrieren — nicht mit Modellierung. Das zeigt die zentrale Bedeutung dieses Themas.

*Bestandteile der Datenintegration* (alle prüfungsrelevant):

#formula-box[
*Funktionen der Datenintegration — Vollständige Liste:*

1. *Datenimport / Datenkonversion* — Einlesen aus verschiedenen Formaten (CSV, JSON, XML, XLSX)
2. *Datenvalidierung* — Prüfen ob Daten gültig und vollständig sind
3. *Datenbereinigung* — Entfernen von Duplikaten, ungültigen oder fehlenden Werten
4. *Datentransformation* — Schema-Abbildung, Typkonvertierung, Spalten aufteilen/zusammenführen
5. *Datenfusion (Conflation/Conciliation)* — Zusammenführen widersprüchlicher Darstellungen derselben Entität
6. *Datenaggregation* — Zusammenfassen aus mehreren Quellen (GROUP BY, SUM, COUNT)
7. *Datenfilterung* — Auswahl relevanter Datensätze (WHERE)
8. *Datenberechnung* — Hinzufügen berechneter Spalten
9. *Datenanreicherung* — Ergänzung durch externe Quellen (z.B. Geocoding, Web Scraping)
10. *Datenanonymisierung* — Schutz sensibler Daten
11. *Datengenerierung* — Synthetische Daten erzeugen
]

=== 1.2 Datenintegration: DWH vs. Machine Learning

#cheat-box[
*Wenn die Aufgabe fragt: "Unterschied DWH vs. ML bei der Datenintegration?"*

| Aspekt | Data Warehouse | Machine Learning |
|---|---|---|
| Ziel | Reporting, Historisierung | Exploration, Modelltraining |
| Schema | Fixiert, strukturiert | Flexibel, agil, Feature-Engineering |
| Aktualität | Periodisch (Batch) | Batch + Streaming/Near-Realtime |
| Datenqualität | Konsistenz, historische Genauigkeit | Genauigkeit, Aktualität, Bias, Feature-Qualität |
| Quellen | Primär strukturiert, intern | Divers, oft unstrukturiert, extern/intern |
| Technologien | Relationale DBs, ETL-Tools, SQL | Python/Pandas, Pipeline-Tools, SQL |
]

---

== 2. Vorgehensweisen und Konflikttypen bei der Datenintegration

=== 2.1 Top-Down vs. Bottom-Up

*Top-Down:* Das Zielschema ist vorgegeben (z.B. durch Standards). Man sucht Korrespondenzen zu den Quell-Schemata.

*Bottom-Up:* Ausgangspunkt sind die existierenden Quell-Schemata. Daraus wird ein integriertes Zielschema konstruiert, das möglichst den vollständigen Informationsgehalt aller Quellen enthält.

=== 2.2 Kriterien für Integrationsmethoden

#formula-box[
*Vier Qualitätskriterien nach Batini et al. (1986):*

1. *Vollständigkeit* — Das integrierte Schema muss alle Konzepte aller lokalen Schemata beinhalten; keine Information darf verloren gehen.

2. *Minimalität* — Reale Konzepte, die in mehreren lokalen Schemata vorkommen, dürfen nur *einmal* im integrierten Schema repräsentiert sein (keine Redundanz).

3. *Verständlichkeit* — Das integrierte Schema muss leicht verständlich und nachvollziehbar sein.

4. *Korrektheit* — Alle Informationen im integrierten Schema müssen in mindestens einem lokalen Schema semantisch äquivalent vorhanden sein; neu hinzugefügte Beziehungen dürfen nicht im Widerspruch zu bestehenden Schemata stehen.
]

=== 2.3 Klassifikation von Integrationskonflikten

#tip-box[
*Woran erkenne ich welche Konfliktart vorliegt?*

- *Semantischer Konflikt* → Unterschiedliche Mengen von Real-Welt-Objekten sind repräsentiert (z.B. "öffentliche Sitzbank" bedeutet in Quelle A und B verschiedene Dinge)
- *Beschreibungskonflikt* → Gleiche Objekte, aber unterschiedliche Attribute/Namen; *Homonyme* (gleicher Name, verschiedene Bedeutung) oder *Synonyme* (verschiedene Namen, gleiche Bedeutung); unterschiedliche Masseinheiten
- *Heterogenitätskonflikt* → Unterschiedliche Schemata, Modellierungskonstrukte oder Ausdruckskraft → Auflösung durch Schema-Transformation
- *Struktureller Konflikt* → Unterschiedliche Modellierung (z.B. Vererbung vs. flache Tabelle), fehlende Attribute, unterschiedliche Default-Werte
- *Datenkonflikt* → Falsche/veraltete Daten, unterschiedlich codierte Aufzählwerte
]

=== 2.4 Heterogenitätsarten

*Semantische Heterogenität:* Begriffe und Objektkonzepte meinen in verschiedenen Systemen verschiedenes.

*Modellierungsheterogenität:* Unterschiedliche Datenstrukturen, Datentypen, Regeln:
- Texttyp vs. spezifischer Datentyp
- Zeilenorientiert vs. geschachtelt (JSON)
- Unterschiedliche Attributnamen (Homonyme)

*Technisch-strukturelle Heterogenität:* Unterschiedliche Zugriffsmethoden, Datenformate (CSV, XML, JSON, binär), Kodierung (Little/Big Endian, EOL, UTF-8, String Escaping).

---

== 3. Data Warehouse: Architektur und Wartung

=== 3.1 Pro und Contra Data Warehouses

#cheat-box[
*Wenn gefragt: "Warum DWH?" oder "Warum nicht DWH?"*

*Pro DWH:*
- Abfragen stören die Quellsysteme nicht
- Anspruchsvolle Berechnungen (Data Mining, Bereinigung) möglich
- Zentraler, konsistenter Datenbestand

*Contra DWH:*
- Aufwändiges Design des physischen und logischen Datenbankschemas
- Daten sind oft nicht aktuell (träge oder Offline-Aktualisierung)
- Datensynchronisation bei Änderungen in den Quellen ist ein Problem

*Alternative: Virtuelle Datenintegration* — Daten bleiben in den Quellen, werden erst bei Abfrage abgerufen (kein Kopieren, aber höhere Abfragelatenz).
]

=== 3.2 DWH Wartungsansätze

*Aktualisieren-Kopieren (Full Refresh):* Gesamtaustausch aller Dateninhalte. Einfach, aber Aufwand wächst mit Datenvolumen.

*Inkrementelle Kopie:* Nur geänderte Daten werden aktualisiert. Effizienter, aber: Es müssen Vorkehrungen für *Update-Anomalien* getroffen werden, die durch asynchrone Verarbeitung entstehen.

#warn-box[
*Update-Anomalien:* Wenn Quellsystem und DWH nicht synchron sind, können Änderungen in der Quelle im DWH nicht oder falsch ankommen. Das DWH zeigt dann veraltete oder inkonsistente Daten — ein klassischer Fehler bei inkrementellen Kopien ohne Transaktionsschutz.
]

---

== 4. ETL — Extract, Transform, Load

=== 4.1 Grundidee und Prozessschritte

*Kernidee:* ETL ist der Standardprozess für die physische Zusammenführung von Daten aus heterogenen Quellen in ein Data Warehouse. Die Transformation geschieht *ausserhalb* des Ziel-DBMS, in einem separaten Tool oder Skript.

#formula-box[
*ETL-Prozess — Allgemeines Rezept:*

1. *Extract (Extrahieren):*
   - Selektion eines Ausschnitts der Daten aus den Quellsystemen
   - Bereitstellung in einer Staging Area (Zwischenspeicher)
   - Quellen können sein: relationale DBs, CSV/Excel, APIs, JSON/XML-Dateien

2. *Transform (Transformieren):*
   - Anpassung der Daten an Zielschema und Qualitätsanforderungen
   - Durchgeführt im ETL-Tool (z.B. mit JavaScript bei Kettle, Java bei Talend)
   - Alle Transformationsfunktionen werden hier angewendet (siehe Abschnitt 4.2)

3. *Load (Laden):*
   - Physisches Einbringen der transformierten Daten in das Data Warehouse
   - Inklusive eventuell notwendiger Aggregationen
   - Bei Rohdaten in Data Lakehouses: "Schema-on-Read" statt Schema-on-Write

*Merke:* ETL kann in jeder Programmiersprache selbst implementiert werden, aber Unternehmen nutzen meist spezialisierte ETL-Tools.
]

=== 4.2 Transformationsfunktionen — Vollständige Übersicht

#formula-box[
*Grundlegende Transformationen (alle mit SQL lösbar):*

- *String-Operationen:* Trimmen, Auffüllen, Gross-/Kleinschreibung, Tausendertrennzeichen löschen
- *Berechnungen:* Arithmetische/logische Operationen → neue Spalten ableiten (z.B. Alter aus Geburtsdatum)
- *Typumwandlung:* String → Integer, String → Datum, etc.
- *Felder hinzufügen:* Konstanten, eindeutige Bezeichner, Zeitstempel
- *Feldaufteilung (Split):* Ein Feld mit mehreren Werten → mehrere Spalten/Zeilen
- *Filtern und Löschen:* WHERE-Bedingungen; nicht benötigte Zeilen entfernen
- *Umbenennen und Löschen von Feldern:* Schema anpassen
- *Gruppieren und Aggregieren:* GROUP BY + SUM, AVG, COUNT, MAX, MIN
- *Kodierung/Dekodierung:* Kategorische → numerische Werte (für ML)
- *Deduplizierung:* Doppelte Datensätze identifizieren und entfernen
- *Datenmaskierung/Anonymisierung:* Sensible Daten schützen

*Anspruchsvollere Transformationen:*
- *Sortieren (SORT):* Zeilen nach einem oder mehreren Feldern ordnen
- *Verbinden (JOIN):* Zeilen aus zwei oder mehr Tabellen über gemeinsame Schlüssel verbinden
- *Pivotieren (PIVOT/UNPIVOT):* Zeilen → Spalten oder Spalten → Zeilen umstrukturieren
- *Verflachung:* Hierarchische Strukturen (JSON/XML) → flaches relationales Format
- *Zusammenführen/Merge:* Datensätze kombinieren ohne vollständige Schlüssel-Übereinstimmung
- *Datenanreicherung (Lookup):* Daten aus Nachschlagetabellen oder externen Quellen ergänzen

*Für ML-Datenmodelle zusätzlich:*
- *Fehlerbehandlung und Bereinigung:* Ausreisser identifizieren und korrigieren/entfernen
- *Normalisierung/Standardisierung:* Werte auf gemeinsame Skala bringen
- *Imputation:* Fehlende Werte durch Mittelwert/Median/Modus ersetzen
- *Fehlende Daten markieren:* Explizit als fehlend kennzeichnen statt löschen
]

=== 4.3 SQL-Rezepte für häufige ETL-Transformationen

#formula-box[
*Rezept: Tabelle kopieren*
```sql
CREATE TABLE ziel_tabelle AS
SELECT * FROM quell_tabelle;
```

*Rezept: Datentyp einer Spalte ändern (z.B. TEXT zu INT)*
```sql
ALTER TABLE meine_tabelle
  ALTER COLUMN spalte1 TYPE INT
  USING CAST(NULLIF(spalte1, '') AS INT);
```
Achtung: `NULLIF(spalte1, '')` wandelt leere Strings zuerst in NULL um, damit CAST nicht fehlschlägt.

*Rezept: Spalte aufteilen (Split)*
```sql
ALTER TABLE meine_tabelle
  ADD COLUMN vorname VARCHAR(255),
  ADD COLUMN nachname VARCHAR(255);

UPDATE meine_tabelle
SET vorname = split_part(vollname, ' ', 1),
    nachname = split_part(vollname, ' ', 2);
```
`split_part(string, trennzeichen, position)` — Position 1 = erstes Element.

*Rezept: CSV in PostgreSQL laden (COPY)*
```sql
COPY personen(Kunden_ID, Nachname, Vorname, Geburtsdatum)
FROM 'C:/daten/adressliste.csv'
DELIMITER ',' CSV HEADER;
```
Voraussetzung: Das Zielschema muss *exakt* zur CSV-Struktur passen.
]

#warn-box[
*Häufiger Fehler beim CSV-Import mit COPY:*
Das Datenbankschema muss *vor* dem Import angelegt werden und genau zu den Spalten der CSV-Datei passen — Reihenfolge, Datentyp und Anzahl der Spalten. Wenn das Schema nicht passt, schlägt COPY mit einem Fehler fehl. Lösung: Tools wie DBeaver, CSVKit oder Python/Pandas nutzen, die das Schema automatisch ableiten können.
]

---

== 5. ELT — Extract, Load, Transform

=== 5.1 Unterschied ETL vs. ELT

*Kernidee:* Bei ELT werden die Rohdaten zuerst in die Datenbank geladen (Staging DB), und die Transformation erfolgt *innerhalb* des DBMS mit SQL — kein separates Transformations-Tool nötig.

#cheat-box[
*Wenn Aufgabe fragt: "ETL oder ELT — was wählen und warum?"*

| Kriterium | ETL | ELT |
|---|---|---|
| Wo wird transformiert? | Im ETL-Tool (ausserhalb DBMS) | Im DBMS (mit SQL) |
| Sprache | JavaScript, Java, Python | SQL |
| Architektur | Komplexer (separates Tool) | Einfacher (nur DBMS) |
| Speicherplatz | Staging Area + Ziel | On-demand im DBMS |
| Delay | Kleiner Delay (Transform vor Load) | Transform verzögert bis Abfrage |
| Wann bevorzugt? | Legacy DWH, komplexe Transformationen | Cloud-DBMS, grosse Datenmengen, SQL-affine Teams |
]

=== 5.2 Reverse ETL

*Reverse ETL* ist der umgekehrte Prozess: Daten werden aus einem zentralen Data Warehouse zurück in operative Systeme (CRM, Marketing-Tools etc.) kopiert. Typisch wenn analytisch aufbereitete Daten operativ genutzt werden sollen.

---

== 6. Tools für die Datenintegration

=== 6.1 Übersicht der Tool-Kategorien

#cheat-box[
*Welches Tool für welche Aufgabe?*

- *Python/Pandas, Java, R:* Maximale Flexibilität, aber hoher Implementierungsaufwand
- *SQL / dbt:* Das "T" in ETL/ELT — Transformation mit SQL, Versionierung, Wiederverwendung
- *OpenRefine:* Interaktive Datenbereinigung und -exploration, No-Coding, ideal für CSV/Excel/JSON
- *Apache Hop:* Vollständiges ETL-Tool (Fork von Kettle), GUI-basiert, Java, Open Source
- *KNIME:* ETL + Machine Learning, visuelle Pipelines
- *AWS Glue / Azure Data Factory:* Cloud-native ETL-Plattformen
- *Apache AirFlow:* Schwerpunkt DataOps und Pipeline-Orchestrierung
- *FME:* Kommerziell, spezialisiert auf Geodaten
- *GDAL/OGR:* Open Source für Geodaten
]

=== 6.2 OpenRefine — Detaillierte Beschreibung

*Kernidee:* OpenRefine ist ein Desktop-Tool für interaktives Sichten, Bereinigen, Integrieren und Anreichern von Daten — ohne Programmierung, mit einer tabellenkalkulationsähnlichen GUI.

#formula-box[
*OpenRefine — Allgemeines Lösungsrezept für Datenbereinigung:*

1. *Daten importieren:* CSV, XLS, JSON, XML oder Datenbank → Projekt erstellen
2. *Daten sichten (Facets):* Text-Facets, Zahlen-Facets, Timeline-Facets einsetzen um Verteilungen und Ausreisser zu erkennen
3. *Inkonsistente Werte identifizieren:* Cluster-Funktion ("Cluster and Edit") nutzt Ähnlichkeitsalgorithmen um Varianten desselben Wertes zu finden (z.B. "Zürich", "Zuerich", "zürich")
4. *Werte bereinigen:* Direkt in der Zelle oder über Transformationen (GREL-Ausdrücke: `value.trim()`, `value.toLowercase()`, etc.)
5. *Spalten transformieren:* Umbenennen, aufteilen, zusammenführen, Typ zuweisen
6. *Filtern:* Text-Filter oder Facets zur Selektion von Teilmengen
7. *Datenanreicherung:* Reconciliation gegen Wikidata oder andere externe Quellen
8. *Export:* CSV, Excel, JSON, etc. exportieren

*Wichtige Eigenschaften:*
- Verändert *niemals* die Quelldaten (ausser man überschreibt explizit)
- Spalten haben *keinen* Datentyp — ausser man weist einen explizit zu
- Memory-/RAM-basiert → limitiert durch verfügbaren RAM
- Alle Operationen werden als *History* gespeichert und können als JSON-Skript exportiert/importiert werden (Reproduzierbarkeit!)
]

#tip-box[
*Woran erkenne ich, dass OpenRefine die richtige Wahl ist?*
- Aufgabe: "Bereinige diese CSV/Excel-Datei interaktiv"
- Aufgabe: "Finde und entferne Duplikate oder Tippfehler in den Werten"
- Aufgabe: "Standardisiere Schreibweisen (z.B. Ländernamen, Kategorien)"
- Aufgabe: "Reichere Daten mit externen Quellen an"
- Kein Coding gewünscht, einmalige oder explorative Bereinigung
]

#warn-box[
*Häufige Denkfehler bei OpenRefine:*
- OpenRefine hat *keinen* Undo über Sessions hinaus — aber die History-Funktion speichert alle Operationen als JSON. Diese JSON-Operationsliste kann auf neuen Daten wiederholt angewendet werden.
- Spalten haben *keinen automatischen Datentyp* — wenn man mit Zahlen rechnen will, muss man den Typ explizit zuweisen.
- OpenRefine ist RAM-basiert: bei sehr grossen Dateien (> wenige GB) gibt es Performanceprobleme.
]

=== 6.3 Apache Hop — Ausgewählte Transforms

*Kernidee:* Apache Hop ist ein GUI-basiertes ETL-Tool für visuelle Pipeline-Erstellung. Daten fliessen als Zeilen-Streams durch verkettete Transformations-Schritte.

*Wichtige Transforms in Apache Hop:*

- *Filter Rows:* Leitet Zeilen basierend auf einer Bedingung zu "true"- oder "false"-Ausgabe
- *Select Values:* Auswahl, Umbenennung, Konvertierung von Feldern (RegEx möglich)
- *Database Lookup:* Abfrage einer DB-Tabelle und Hinzufügen neuer Felder (= JOIN-ähnlich)
- *String Operations:* Kleinschreibung, Zeichenketten-Ersetzen
- *Value Mapper:* Ersetzt Werte basierend auf einer definierten Mapping-Tabelle
- *CSV Input / Text Output:* Einlesen und Schreiben von CSV-Dateien
- *Parquet Input / Output:* Einlesen und Schreiben von Parquet-Dateien

=== 6.4 dbt — data build tool

*Kernidee:* dbt ist ein Command-Line-Tool (und Cloud-Service) das *nur* das "T" in ETL/ELT übernimmt: Datentransformation durch SQL-Abfragen, mit Unterstützung für Testen, Versionierung und Wiederverwendung.

*Kernmerkmale:*
- Transformation rein durch SQL (+ Jinja-Templates für Parametrisierung)
- YAML für Konfiguration und Metadaten
- Unterstützt "SQL-Query-Dependencies" (welche Query hängt von welcher ab)
- Versionierung mit Git (im Gegensatz zu GUI-Tools)
- Als Desktop-Tool und als "dbt cloud" verfügbar
- Eingebettet in grössere Plattformen wie AirByte

---

== 7. Klassifikation von Datenfehlern

*Datenfehler* können auf verschiedenen Ebenen auftreten (nach Leser und Naumann 2006):

- *Syntaktische Fehler:* Falsche Datentypen, falsche Formatierung (z.B. Datum als "32.13.2024")
- *Semantische Fehler:* Wert ist syntaktisch korrekt, aber bedeutungslos (z.B. Alter = -5)
- *Strukturelle Fehler:* Fehlende Pflichtfelder, falsche Relationen zwischen Tabellen
- *Duplikate:* Dieselbe Entität mehrfach gespeichert, eventuell mit leichten Abweichungen

---

== 8. Datenfluss: Schematische Übersicht

#formula-box[
*Typischer Datenfluss in ein Data Warehouse:*

```
Quellsystem 1 ─┐
Quellsystem 2 ─┤─→ [Extract] → [Staging Area] → [Transform] → [Load] → Data Warehouse
Quellsystem 3 ─┘

Bei Data Lakehouse:
Quellsystem ──→ [Extract] → [Load RAW] → Data Lake (Rohdaten)
                                              ↓ (Schema-on-Read bei Abfrage)
                                         Analyseschicht
```

*Reverse ETL (umgekehrt):*
```
Data Warehouse → [Extract] → [Transform] → [Load] → Operative Systeme (CRM, etc.)
```
]

---

== 9. Zusammenfassung: Entscheidungsmatrix

#cheat-box[
*Schnell-Entscheidungen für Aufgaben und Prüfung:*

- Wenn *mehrere heterogene Quellen* → Datenintegration nötig, Konflikttypen prüfen
- Wenn *interaktive Bereinigung*, kein Code → *OpenRefine*
- Wenn *automatisierte Pipelines*, SQL-Transformation → *ELT mit dbt oder SQL*
- Wenn *komplexe Pipelines mit GUI* → *Apache Hop* (Open Source) oder Talend/SSIS (kommerziell)
- Wenn *Cloud-native* → AWS Glue, Azure Data Factory
- Wenn *Transformation ausserhalb DB* (mit Java/JS/Python) → *ETL*
- Wenn *Transformation innerhalb DB* (mit SQL) → *ELT*
- Wenn *Daten aus DWH zurück in operative Systeme* → *Reverse ETL*
- Wenn Frage nach Qualitätskriterien: Vollständigkeit, Minimalität, Verständlichkeit, Korrektheit (Batini et al.)
- Wenn Frage nach Konflikten: Semantisch, Beschreibung, Heterogenität, Strukturell, Daten
]