// Auto-generated by RAG system on 2026-05-09
// Week 10 — do not edit the header

#import "../../template.typ": tip-box, warn-box, formula-box, cheat-box

== Week 10: Preprocessing (2) & (3) — Noisy/Missing Data, Correlation, Normalization, Discretization, Data Reduction

= 1. Fehlende Daten (Missing Data)

*Kernidee:* Fehlende Werte können Analysen verzerren oder ineffizient machen — man muss verstehen _warum_ sie fehlen, bevor man sie behandelt.

== 1.1 Typen von fehlenden Daten

#tip-box[
*Woran erkenne ich den Typ?*
- *MCAR* (Missing Completely At Random): Fehlende Werte hängen weder von beobachteten noch von fehlenden Werten ab. Zufällig wie ein Geräteausfall. Test: Little's MCAR-Test.
- *MAR* (Missing At Random): Das Fehlen lässt sich durch _andere beobachtete_ Variablen erklären. z.B. Männer geben seltener Gewicht an — aber wenn man Geschlecht kennt, kann man das modellieren.
- *MNAR* (Missing Not At Random): Das Fehlen hängt vom fehlenden Wert selbst ab. z.B. sehr reiche Personen geben Einkommen nicht an. Schwierigster Fall — systematischer Bias.
]

*Konsequenzen:*
- *MCAR*: Kein Bias, nur Effizienzverlust (weniger Daten)
- *MAR*: Bias möglich, aber korrigierbar
- *MNAR*: Systematischer Bias — schwer zu korrigieren

== 1.2 Umgang mit fehlenden Werten

#formula-box[
*Strategien (von einfach zu komplex):*

1. *Löschen* — Tupel/Attribute mit fehlenden Werten entfernen (nur sinnvoll wenn wenige fehlen und MCAR)
2. *Manuelle Befüllung* — zeitaufwändig, erfordert Domänenwissen
3. *Globale Konstante* — ersetze durch "unknown" oder 0 (einfach, aber kann Algorithmen täuschen)
4. *Lagemass* — ersetze durch Mittelwert (numerisch), Median (bei Ausreissern), Modus (nominal)
5. *Regression* — schätze fehlenden Wert durch Regressionsmodell auf anderen Attributen
6. *Maximum Likelihood* — schätze Verteilungsparameter und impute basierend darauf
7. *Machine Learning Methoden* — modernster Ansatz (z.B. KNN-Imputation)
]

#warn-box[
*Häufiger Fehler:* Immer den Mittelwert nehmen. Bei schiefer Verteilung oder Ausreissern ist der *Median* besser. Bei nominalen Daten ist nur der *Modus* sinnvoll.
]

= 2. Noisy Data & Binning zur Glättung

*Kernidee:* Reale Daten = wahres Signal + zufälliger Fehler (Rauschen). Glättung reduziert Rauschen, indem lokale Mittelwerte oder Grenzen verwendet werden.

== 2.1 Binning-Methoden zur Glättung

#formula-box[
*Rezept: Smoothing by Bin Means*

1. Daten sortieren (aufsteigend)
2. In Bins der Tiefe $k$ aufteilen (equidepth: je $k$ Werte pro Bin)
3. Für jeden Bin: Mittelwert berechnen
4. Alle Werte im Bin durch den Bin-Mittelwert ersetzen

*Rezept: Smoothing by Bin Boundaries*

1. Daten sortieren
2. In Bins aufteilen
3. Jeden Wert durch die nächste Bin-Grenze (min oder max des Bins) ersetzen — je nachdem welche näher liegt

*Beispiel* (Vorlesungsdaten, Bin-Tiefe 3):

Daten: 4, 8, 15, 21, 21, 24, 25, 28, 34

- Bin 1: {4, 8, 15} → Mittelwert = $frac(4+8+15, 3) = 9$ → {9, 9, 9}
- Bin 2: {21, 21, 24} → Mittelwert = $frac(21+21+24, 3) = 22$ → {22, 22, 22}
- Bin 3: {25, 28, 34} → Mittelwert = $frac(25+28+34, 3) = 29$ → {29, 29, 29}

Grenzen-Glättung Bin 1: 4 → 4 (näher an min=4), 8 → 4 (näher an min=4), 15 → 15 (näher an max=15)
Resultat Bin 1: {4, 4, 15}
]

*Übungsaufgabe 1a — Rezept anwenden:*

Daten: 13, 15, 16, 16, 19, 20, 20, 21, 22, 22, 25, 25, 25, 25, 30, 33, 33, 35, 35, 35, 35, 36, 40, 45, 46, 52, 70 (27 Werte, Bin-Tiefe 3 → 9 Bins)

$
"Bin 1: " {13, 15, 16} arrow.r "Mittel" = frac(44,3) approx 14.67 arrow.r {14.67, 14.67, 14.67}
$
$
"Bin 2: " {16, 19, 20} arrow.r "Mittel" approx 18.33
$
... und so weiter für alle 9 Bins.

*Effekt:* Ausreisser wie "70" wird gedämpft (Bin 9: {46, 52, 70} → Mittel = 56).

#tip-box[
*Wann brauche ich Binning?*
- Aufgabe erwähnt "smoothing", "Rauschen reduzieren" oder "Ausreisser abmildern"
- Aufgabe gibt eine Liste von Zahlen und eine Bin-Tiefe (equidepth) oder Anzahl Bins
- Schlüsselwörter: "bin means", "bin boundaries", "equidepth", "equiwidth"
]

== 2.2 Ausreisser erkennen und behandeln

*Ausreisser* = Werte die weit vom erwarteten Bereich abweichen. Sie sind eine spezielle Form von Noise.

*Erkennungsmethoden:*
- *Statistisch (univariat):* Boxplot — Ausreisser ausserhalb $1.5 times "IQR"$ (IQR = Q3 − Q1)
- *Multivariat:* Cluster-Methoden, Distanzmetriken
- *Visuell:* Scatter Plots, Histogramme

*Behandlungsstrategien:*
- *Analysieren:* Sind Ausreisser das Ziel? (z.B. Betrugsdetekton)
- *Löschen:* Wenn sie einen kleinen Teil ausmachen und keinen Informationswert haben
- *Binning:* Neue Kategorie erstellen z.B. "≥ 300"
- *Imputation:* Wie fehlende Werte behandeln (nur bei Eingabefehler)

#warn-box[
*Niemals* Ausreisser blind löschen ohne zu verstehen woher sie kommen! Sie können der wertvollste Teil der Daten sein (z.B. Anomalie-Erkennung).
]

= 3. Korrelationsanalyse

== 3.1 Pearson Korrelationskoeffizient (für numerische Daten)

*Kernidee:* Misst die Stärke und Richtung des linearen Zusammenhangs zwischen zwei numerischen Variablen. Resultat immer zwischen −1 und +1.

#formula-box[
*Formel (Sample Pearson):*

$
r = frac(sum_(i=1)^n (x_i - overline(x))(y_i - overline(y)), sqrt(sum_(i=1)^n (x_i - overline(x))^2 dot sum_(i=1)^n (y_i - overline(y))^2))
$

*Variablen:*
- $x_i, y_i$: Beobachtungspaare
- $overline(x), overline(y)$: Mittelwerte der jeweiligen Variablen
- $n$: Anzahl Beobachtungen

*Rezept:*
1. Mittelwerte $overline(x)$ und $overline(y)$ berechnen
2. Für jedes Paar $(x_i, y_i)$: Abweichungen $(x_i - overline(x))$ und $(y_i - overline(y))$ berechnen
3. Zähler: Summe der Produkte der Abweichungen
4. Nenner: Wurzel aus (Summe der quadrierten Abweichungen von x) × (Summe der quadrierten Abweichungen von y)
5. Dividieren

*Beispiel* (Übungsaufgabe 2):

$overline(x) = frac(43+21+25+42+57+59, 6) = frac(247,6) approx 41.17$

$overline(y) = frac(99+65+79+75+87+81, 6) = frac(486,6) = 81$

Tabelle der Abweichungen:

| $x_i$ | $y_i$ | $x_i - overline(x)$ | $y_i - overline(y)$ | Produkt |
|--------|--------|----------------------|----------------------|---------|
| 43 | 99 | 1.83 | 18 | 32.94 |
| 21 | 65 | −20.17 | −16 | 322.72 |
| 25 | 79 | −16.17 | −2 | 32.34 |
| 42 | 75 | 0.83 | −6 | −4.98 |
| 57 | 87 | 15.83 | 6 | 94.98 |
| 59 | 81 | 17.83 | 0 | 0 |

Zähler $approx 32.94 + 322.72 + 32.34 - 4.98 + 94.98 + 0 = 478$

$r approx 0.5298$ → *moderate positive Korrelation*
]

#tip-box[
*Interpretation:*
- $r = 1$: perfekte positive lineare Korrelation
- $r = -1$: perfekte negative lineare Korrelation
- $r = 0$: kein linearer Zusammenhang
- $abs(r) gt.eq 0.7$: starke Korrelation
- $0.3 lt.eq abs(r) < 0.7$: moderate Korrelation
- $abs(r) < 0.3$: schwache Korrelation

*Achtung:* Korrelation ≠ Kausalität! (Eis-Konsum korreliert mit Ertrinkungstoten — weil beides im Sommer steigt.)
]

== 3.2 Chi-Quadrat-Test (für nominale Daten)

*Kernidee:* Prüft ob zwei nominale (kategoriale) Variablen statistisch unabhängig sind, indem beobachtete Häufigkeiten mit erwarteten Häufigkeiten (unter Unabhängigkeitsannahme) verglichen werden.

#formula-box[
*Formel:*

$
chi^2 = sum_i frac((O_i - E_i)^2, E_i)
$

*Variablen:*
- $O_i$: beobachteter Wert in Zelle $i$
- $E_i$: erwarteter Wert in Zelle $i$ (unter Unabhängigkeit)

*Erwarteter Wert:*
$
E_(i j) = frac("Zeilensumme"_i times "Spaltensumme"_j, "Gesamtsumme N")
$

*Rezept:*
1. Kontingenztabelle mit beobachteten Werten aufstellen
2. Randsummen (Zeile + Spalte) berechnen
3. Für jede Zelle: $E_(i j) = frac("Zeilensumme" times "Spaltensumme", N)$ berechnen
4. Für jede Zelle: $frac((O_(i j) - E_(i j))^2, E_(i j))$ berechnen
5. Alles summieren → $chi^2$-Wert
6. Freiheitsgrade: $"DOF" = (r-1)(c-1)$ wobei $r$ = Zeilen, $c$ = Spalten
7. Mit kritischem Wert aus Tabelle vergleichen: Wenn $chi^2 > chi^2_"krit"$ → abhängig

*Beispiel* (Übungsaufgabe 3):

Beobachtete Werte:
$
mat("", "Compact", "Luxury", "Summe";
"1 or less", 30, 0, 30;
"2 or 3", 20, 10, 30;
"more than 3", 10, 30, 40;
"Summe", 60, 40, 100)
$

Erwartete Werte ($E_(i j) = frac("ZS" times "SS", 100)$):
$
mat("", "Compact", "Luxury";
"1 or less", frac(30 times 60, 100) = 18, frac(30 times 40, 100) = 12;
"2 or 3", frac(30 times 60, 100) = 18, frac(30 times 40, 100) = 12;
"more than 3", frac(40 times 60, 100) = 24, frac(40 times 40, 100) = 16)
$

Chi-Quadrat:
$
chi^2 = frac((30-18)^2, 18) + frac((0-12)^2, 12) + frac((20-18)^2, 18) + frac((10-12)^2, 12) + frac((10-24)^2, 24) + frac((30-16)^2, 16)
$

$= 8 + 12 + 0.222 + 0.333 + 8.167 + 12.25 approx 40.97$

DOF = $(3-1)(2-1) = 2$, $alpha = 0.1$ → kritischer Wert $approx 4.605$

Da $40.97 >> 4.605$ → *Carsize und NrOfFines sind abhängig!*
]

#warn-box[
*Häufige Fehler beim Chi-Quadrat-Test:*
- DOF vergessen: $(r-1)(c-1)$, nicht $r times c$
- Erwartete Werte falsch berechnet: immer $frac("Zeilensumme" times "Spaltensumme", "Gesamtsumme N")$
- Test sagt "abhängig" → bedeutet *nicht* kausal abhängig, nur statistisch assoziiert
]

#cheat-box[
*Wann welcher Korrelationstest?*
- Numerische Daten, linearer Zusammenhang → *Pearson $r$*
- Nominale/kategoriale Daten → *Chi-Quadrat $chi^2$*
- Chi-Quadrat funktioniert auch für nicht-lineare Abhängigkeiten
]

= 4. Normalisierung

*Kernidee:* Attribute mit verschiedenen Einheiten/Skalen werden auf einen gemeinsamen Bereich gebracht, damit kein Attribut durch seinen Wertebereich künstlich übergewichtet wird.

*Wann nötig?* Bei Algorithmen die auf Distanzen oder Gewichten basieren: k-NN, Clustering, neuronale Netze, lineare Regression.

== 4.1 Min-Max-Normalisierung

#formula-box[
*Formel (auf $[0,1]$):*
$
v'_i = frac(v_i - min_A, max_A - min_A)
$

*Formel (auf beliebiges $[min_R, max_R]$):*
$
v'_i = frac(v_i - min_A, max_A - min_A) dot (max_R - min_R) + min_R
$

*Variablen:*
- $v_i$: zu normalisierender Wert
- $min_A, max_A$: Minimum und Maximum des Attributs $A$ im Datensatz
- $min_R, max_R$: gewünschter Zielbereich

*Rezept:*
1. $min_A$ und $max_A$ im Datensatz bestimmen
2. Formel einsetzen
3. Bei Zielbereich $[min_R, max_R]$: erweiterte Formel verwenden

*Beispiel* (Übungsaufgabe 6a):
Alter: min = 13, max = 70, zu normalisieren: $v_i = 35$

$
v'_i = frac(35 - 13, 70 - 13) = frac(22, 57) approx 0.386 quad [0,1]
$

Für $[-1, 1]$:
$
v'_i = 0.386 dot (1 - (-1)) + (-1) = 0.386 dot 2 - 1 approx -0.228 quad [-1,1]
$

*Wertebereich:* $[min_R, max_R]$ — frei wählbar, Standard $[0,1]$
]

== 4.2 Decimal Scaling

#formula-box[
*Formel:*
$
v'_i = frac(v_i, 10^j)
$

*$j$ bestimmen:* kleinste ganze Zahl sodass $max(abs(v'_i)) < 1$, d.h. $j = ceil(log_10(max(abs(v_i)) + 1))$

*Rezept:*
1. Betrag des grössten absoluten Werts im Attribut bestimmen
2. $j$ = Anzahl Stellen dieser Zahl (kleinstes $j$ so dass $max abs(v') < 1$)
3. Alle Werte durch $10^j$ teilen

*Beispiel* (Übungsaufgabe 6b):
Alter: $max(abs(A)) = 70$ → $j = 2$ (weil $70/100 = 0.70 < 1$, aber $70/10 = 7.0 gt.eq 1$)

$
v'_i = frac(35, 10^2) = frac(35, 100) = 0.35
$

*Wertebereich:* $(-1, 1)$
]

== 4.3 Z-Score Normalisierung (Standardisierung)

#formula-box[
*Formel:*
$
v'_i = frac(v_i - overline(A), sigma_A)
$

*Bei Ausreissern statt $sigma$ die mittlere absolute Abweichung (MAD) verwenden:*
$
v'_i = frac(v_i - overline(A), S'_A) quad "mit" quad S'_A = frac(1, N) sum_(k=1)^N abs(v_k - overline(A))
$

*Variablen:*
- $overline(A)$: Mittelwert des Attributs
- $sigma_A$: Standardabweichung des Attributs
- $S'_A$: mittlere absolute Abweichung

*Rezept:*
1. Mittelwert $overline(A)$ berechnen
2. Standardabweichung $sigma_A$ (gegeben oder berechnen)
3. Formel anwenden

*Beispiel* (Übungsaufgabe 6c):
$overline(A) = 29.96$, $sigma_A = 12.94$, $v_i = 35$

$
v'_i = frac(35 - 29.96, 12.94) = frac(5.04, 12.94) approx 0.389
$

*Wertebereich:* $(-infinity, +infinity)$ in Einheiten von Standardabweichungen. Typisch ca. $[-3, 3]$.
]

#cheat-box[
*Welche Normalisierung wann?*

- *Min-Max:* Wenn Min/Max bekannt und sinnvoll (z.B. Alter: 0–100). Sensibel gegenüber Ausreissern.
- *Decimal Scaling:* Schnell und einfach. Wenn nur eine Grössenordnung korrigiert werden soll.
- *Z-Score:* Wenn Min/Max unbekannt oder Ausreisser die Skalierung dominieren würden. Setzt ungefähr Normalverteilung voraus.
- Für Alter mit bekannten Grenzen 0–100: *Min-Max* bevorzugt
- Wenn dominante Ausreisser vorhanden: *Z-Score mit MAD*
]

#warn-box[
*Wertebereich-Verwirrung:*
- Min-Max $[0,1]$: $v'_i = frac(v_i - min_A, max_A - min_A)$ — Formel ohne $R$-Term
- Min-Max $[-1,1]$: $v'_i = frac(v_i - min_A, max_A - min_A) dot 2 - 1$ — Nicht $frac(v_i - min_A, max_A - min_A) dot (-1)$ addieren!
- Decimal Scaling: Bereich ist $(-1, 1)$, nicht $[0, 1]$!
- Z-Score: *kein* fixer Bereich — kann theoretisch jeden Wert annehmen
]

= 5. Diskretisierung (Discretization)

*Kernidee:* Kontinuierliche (numerische) Werte werden in diskrete Kategorien/Intervalle umgewandelt. Wichtig: Die Bins müssen so definiert sein, dass *jeder unbekannte Wert* eindeutig einem Bin zugewiesen werden kann.

== 5.1 Equidepth Binning (gleich viele Elemente pro Bin)

#formula-box[
*Rezept:*
1. Daten sortieren (aufsteigend)
2. Anzahl Bins $k$ festlegen
3. Elemente pro Bin: $m = frac(N, k)$ (aufrunden wenn nötig)
4. Grenzen nach jedem $m$-ten sortierten Wert setzen
5. *Grenzen adjazent und disjunkt* machen: letzte Grenze des Bins $i$ = erste Grenze des Bins $i+1$
6. Sinnvolle Labels vergeben
7. Grenzen über Trainingsdata hinaus erweitern (z.B. 0 und 100 für Alter)

*Beispiel* (Übungsaufgabe 8a, $N=12$, $k=3$):

Sortiert: 7, 7, 8, 9, 11, 12, 13, 22, 22, 36, 38, 64

$m = 12/3 = 4$ Elemente pro Bin

- Bin 1: {7, 7, 8, 9} → Grenze: $[0, 11)$ → Label "Children"
- Bin 2: {11, 12, 13, 22} → Grenze: $[11, 22)$ → Label "Youths"
- Bin 3: {22, 36, 38, 64} → Grenze: $[22, 100]$ → Label "Adults"

*Wichtig:* Einer der beiden Werte "22" landet in Bin 2, der andere in Bin 3 → daher obere Grenze von Bin 2 = $< 22$ (exklusiv), untere Grenze von Bin 3 = $gt.eq 22$ (inklusiv).
]

== 5.2 Equiwidth Binning (gleich breite Intervalle)

#formula-box[
*Rezept:*
1. Wertebereich bestimmen: $"Range" = max_A - min_A$
2. Breite pro Bin: $w = frac("Range", k)$
3. Bin-Grenzen: $min_A, min_A + w, min_A + 2w, ..., max_A$
4. Labels vergeben, Grenzen sinnvoll erweitern

*Beispiel* (Übungsaufgabe 8b, $k=3$):

$"Range" = 64 - 7 = 57$, $w = frac(57, 3) = 19$

- Bin 1: $[0, 26)$ → "young" (0 bis 7+19=26)
- Bin 2: $[26, 45)$ → "middle"
- Bin 3: $[45, 100]$ → "old"
]

== 5.3 Bin-Grenzen und Zuweisung unbekannter Instanzen

#tip-box[
*Die wichtigsten Regeln für Bin-Grenzen:*
1. *Disjunkt:* Kein Wert darf in zwei Bins fallen
2. *Adjazent:* Keine Lücken — jeder mögliche Wert muss einem Bin zugewiesen werden können
3. *Ausserhalb des Trainingsbereichs:* Sinnvolle Grenzen wählen (z.B. 0 und 100 für Alter), nicht einfach min/max der Trainingsdaten

*Für eine neue unbekannte Instanz:* Prüfe in welches Bin der Wert fällt (Grenzen inklusiv/exklusiv beachten).
]

*Anwendungsbeispiel* (Übungsaufgabe 8c):

| Alter | Equidepth | Equiwidth |
|-------|-----------|-----------|
| 8 | Children $[0,11)$ | young $[0,26)$ |
| 10 | Children | young |
| 22 | Adults $[22,100]$ | young $[0,26)$ |
| 45 | Adults | old $[45,100]$ |
| 6 | Children (ausserhalb, nächster Bin) | young |
| 70 | Adults | old |

#cheat-box[
*Equidepth vs. Equiwidth — Unterschied:*
- *Equidepth:* Jeder Bin hat _gleich viele Datenpunkte_. Grenzen basieren auf Datenpunkten.
- *Equiwidth:* Jeder Bin hat _gleiche Breite_. Grenzen basieren auf Wertebereich.
- Bei schiefer Verteilung: Equiwidth kann Bins mit sehr wenigen oder sehr vielen Punkten erzeugen.
]

== 5.4 Weitere Diskretisierungsmethoden

- *Histogramm-Analyse:* Rekursive Partitionierung basierend auf Histogramm → mehrstufige Konzepthierarchie
- *Clustering:* Clustering-Algorithmus auf Attributwerte anwenden → Cluster = Bins
- *Konzepthierarchien für Nominaldaten:* Verwandte Werte hierarchisch gruppieren (z.B. "Meadow Gold Milk" → "Milk" → "Dairy Products")

= 6. Data Reduction

== 6.1 Curse of Dimensionality

*Kernidee:* Mit steigender Anzahl Features wächst der Feature-Raum exponentiell — Daten werden spärlicher, Distanzmetriken verlieren ihre Aussagekraft.

*Konsequenzen:*
- Alle Distanzen konvergieren gegen den gleichen Wert (keine Unterscheidung mehr)
- k-NN, Clustering und andere distanzbasierte Methoden versagen
- Statistische Signifikanz wird schwerer zu erreichen

*Lösungen:* Dimensionsreduktion, Feature Selection

== 6.2 Sampling (Numerosity Reduction)

#formula-box[
*Drei Sampling-Methoden:*

*SRSWOR* (Simple Random Sample Without Replacement):
- Ziehe $s$ Tupel aus $N$ ohne Zurücklegen
- Jedes Tupel gleich wahrscheinlich, kann nur einmal vorkommen

*SRSWR* (Simple Random Sample With Replacement):
- Wie SRSWOR, aber jedes gezogene Tupel wird zurückgelegt
- Gleiche Tupel können mehrfach in der Stichprobe auftauchen

*Stratified Sampling:*
1. Datensatz in disjunkte Schichten (Strata) aufteilen
2. Aus jeder Schicht proportional eine SRS ziehen
3. Anteil aus Schicht $i$: $s_i = frac(N_i, N) dot s$

*Beispiel* (Übungsaufgabe 9, $s=5$, 27 Werte):

- youth (5 Werte): $frac(5, 27) dot 5 approx 0.93 arrow.r 1$ Wert
- middle-aged (20 Werte): $frac(20, 27) dot 5 approx 3.7 arrow.r 4$ Werte
- senior (2 Werte): $frac(2, 27) dot 5 approx 0.37 arrow.r 0$ Werte

Resultat: 1 aus youth + 4 aus middle-aged = 5 Samples
]

#warn-box[
*Bei Stratified Sampling:* Anteile müssen auf ganze Zahlen gerundet werden. Gesamtgrösse $s$ muss stimmen. Wenn durch Rundung die Summe nicht $s$ ergibt, grösste Nachkommastelle aufrunden.
]

== 6.3 Feature Selection

*Zwei Hauptansätze:*

*Filter-Ansatz (unsupervised):*
- Features werden _vor_ dem ML-Algorithmus ausgewählt
- Kriterien: statistische Masse (z.B. Varianz, Korrelation, Information Gain, Chi-Quadrat)
- Schnell, algorithmunabhängig

*Wrapper-Ansatz (supervised):*
- ML-Algorithmus als "Black Box" → suche bestes