// Auto-generated by RAG system on 2026-05-09
// Week 8 — do not edit the header

#import "../../template.typ": tip-box, warn-box, formula-box, cheat-box

== Woche 8: Data Integration — Datenaufbereitung, Duplikaterkennung & Apache Hop

=== Überblick der Themen

Diese Woche behandelt die *praktische Seite der Datenintegration*: Wie werden Daten bereinigt, Duplikate erkannt, fehlende Werte ergänzt und Daten angereichert? Als praktisches Tool steht *Apache Hop* im Mittelpunkt.

---

== Teil 1: Tools für die Datenintegration

=== Toolkategorien und Auswahlkriterien

#tip-box[
*Woran erkenne ich welche Toolkategorie gemeint ist?*

- Aufgabe fragt nach *Steuerung von Abläufen/Prozessen* → Datenflussmanagement (Airflow, NiFi)
- Aufgabe fragt nach *Transformation/Bereinigung* → Dataprocessing (OpenRefine, dbt, KNIME)
- Aufgabe fragt nach *beidem* → Hybrid (Apache Hop, FME, Informatica PowerCenter)
- Aufgabe fragt nach *Geodaten* → FME, Apache Hop, KNIME, Looker Studio
]

#cheat-box[
*Wenn Tool X, dann Kategorie Y:*

- Apache Airflow → Datenflussmanagement, Python, OSS, Batch + teilweise Echtzeit
- Apache NiFi → Datenflussmanagement, Java, OSS, Echtzeit + Batch, Web-GUI
- KNIME → Dataprocessing/Hybrid, Java, OSS+komm., Desktop+Web, Batch
- OpenRefine → Dataprocessing, Java, OSS, Desktop, Batch, No-Code, interaktiv
- dbt → Transformation in Data Warehouses, Python, OSS+komm., CI/CD-Integration
- IBM InfoSphere DataStage → Dataprocessing, kommerziell, Echtzeit+Batch, skalierbar
- Microsoft SSIS → Dataprocessing, .NET, kommerziell, Windows, Batch
- Apache Hop → Hybrid, Java, OSS, Desktop+Web+Batch, grafische ETL-Entwicklung
- FME by Safe Software → Hybrid, C++/Python, kommerziell, Geodaten-Spezialist
- Informatica PowerCenter → Hybrid, Java, kommerziell, Enterprise-Umgebungen
- Looker Studio → Transformation+Visualisierung, kommerziell, Cloud-only, Google
]

*Auswahl-Kriterien in der Praxis (Reihenfolge):*
1. *Kategorie* bestimmen: Datenflussmanagement, Dataprocessing oder Hybrid?
2. *Ökosystem* prüfen: Microsoft? IBM? Google? Open Source?
3. *Know-how* im Team vorhanden?
4. *Spezifische Anforderungen*: Geodaten? Echtzeit? Skalierung?

#warn-box[
Kommerzieller Support existiert auch für Open-Source-Produkte (z.B. KNIME). OSS ≠ kein Support.
]

---

== Teil 2: Datenaufbereitung und Datenreinigung

=== Begriffsabgrenzung

*Datenintegration* (Data Integration)
- Verschiedene Daten von vielen Quellen zu einem gemeinsamen Schema zusammenführen

*Datenaufbereitung* (Data Wrangling) — Teil der Datenintegration
- Reinigung, Transformation und Anreicherung von Rohdaten vor der Analyse

*Datenreinigung* (Data Cleaning / Cleansing / Scrubbing) — Teil der Datenaufbereitung
- Fehlerhafte, inkonsistente oder unvollständige Daten erkennen und korrigieren

#tip-box[
*Unterschied DW/DL vs. ML bei der Datenaufbereitung:*

| Merkmal | Data Warehouse / Data Lake | Machine Learning |
|---------|---------------------------|-----------------|
| Ziel | Bereitstellung für Analysen | Vorbereitung für Modelle |
| Richtung | Top-down (Zielschema vorgegeben) | Bottom-up (gemeinsamer Nenner) |
| Schwerpunkt | Aggregation, Schema-Optimierung | Feature Engineering, Dimensionsreduktion |
| Prozess | Einmalig, regelmässige Updates | Iterativ, kontinuierlich |
]

=== Datenfehler-Klassifikation

*Einfache vs. schwierige Fehler:*
- *Einfach*: Durch Betrachtung eines einzelnen Tupels erkennbar (z.B. falsches Datumsformat)
- *Schwierig*: Erst durch Vergleich mehrerer Tupel erkennbar (z.B. Duplikate)

*Systematische vs. unsystematische Fehler:*
- *Systematisch*: Regelmässig, daher leicht (maschinell) korrigierbar
- *Unsystematisch*: Unregelmässig, oft schwierig zu korrigieren

=== Data-Cleaning-Techniken

1. *Konvertierung und Normalisierung* — unterschiedliche Formate vereinheitlichen (Datum, Währung)
2. *Domänenunabhängige Bereinigung* — Schlüssel- und Attributvergleich, Deduplizierung
3. *Domänenspezifische Bereinigung* — z.B. mit Thesauri (Synonymwörterbücher)
4. *Regelbasierte Bereinigung* — Regeln definieren welche Daten geprüft/gefiltert/korrigiert werden

#cheat-box[
*Regelbasierte Bereinigung — zwei Entscheidungsfragen:*
- Auf welche Daten zielt die Regel? → Quelldaten oder Zieldaten?
- Welche Aktion? → Prüfung (Validation) / Filterung (Removal) / Korrektur (Correction)
]

---

== Teil 3: Duplikaterkennung und Zeichenkettenvergleich

=== Was sind Duplikate?

*Duplikate* = verschiedene Tupel in einer Relation, die dasselbe Realweltobjekt repräsentieren.

Synonyme: Dublettenerkennung, Record Linkage, Object Identification, Named Entity Resolution, Reference Reconciliation.

*Zwei zentrale Herausforderungen:*
- *Genauigkeit (Accuracy)*: Echte Duplikate finden, keine False Positives
- *Skalierbarkeit*: Effizient bei grossen Datenmengen

=== Exakte Duplikaterkennung mit SQL

#formula-box[
*Rezept: Exakte Duplikate finden und löschen*

1. Mit `ROW_NUMBER() OVER (PARTITION BY ...)` jedem Tupel eine Zeilennummer zuweisen — gleiche Werte in den Partition-Spalten erhalten Nummern 1, 2, 3, ...
2. Tupel mit `rownum > 1` sind Duplikate (der erste Treffer bleibt erhalten)
3. Duplikate löschen mit `DELETE ... USING ...`

*Beispiel (PostgreSQL):*

```sql
WITH duplicates AS (
  SELECT
    id,
    ROW_NUMBER() OVER(
      PARTITION BY spalte1, spalte2, spalte3
      ORDER BY id DESC
    ) AS rownum
  FROM tabelle
)
DELETE FROM tabelle USING duplicates
WHERE tabelle.id = duplicates.id
  AND duplicates.rownum > 1
RETURNING *;
```

- `PARTITION BY` definiert, welche Spalten für die Gleichheit verglichen werden
- `ORDER BY id DESC` bestimmt, welcher Datensatz behalten wird (höchste ID bleibt)
- `RETURNING *` zeigt die gelöschten Zeilen
]

#warn-box[
Exaktes Matching versagt bei Tippfehlern! `"Müller"` und `"Muller"` werden nicht als Duplikate erkannt. → Lösung: Ähnlichkeitsmasse verwenden.
]

=== Ähnlichkeitsmasse (Similarity Measures)

==== Kategorie 1: Edit-/Transpositionsbasierte Masse

*Levenshtein-Distanz (Edit-Distanz)*

Die Kernidee: Wie viele elementare Operationen brauche ich, um String $x$ in String $y$ umzuwandeln?

Erlaubte Operationen (je Kosten = 1):
- Löschen eines Zeichens
- Einfügen eines Zeichens
- Ersetzen eines Zeichens

$d("Muster", "Master") = 1$ (ein Ersetzen: u→a)

$d("Haus", "Maus") = 1$ (ein Ersetzen: H→M)

$d("kitten", "sitting") = 3$

*Interpretation:* Kleinere Distanz = höhere Ähnlichkeit.

#tip-box[
*Wann Edit-Distanz?*
- Kurze Strings mit Tippfehlern (Vor-/Nachnamen, Produktcodes)
- Wenn Zeichenreihenfolge wichtig ist
- PostgreSQL: `levenshtein()` Funktion verfügbar (fuzzystrmatch-Extension)
]

*Smith-Waterman*
- Sucht die *ähnlichsten Teilstrings* (lokale Ausrichtung statt globaler)
- Gut für: `"Prof. John R. Smith, Univ of Wisconsin"` vs. `"John R. Smith, Professor"` → findet `"John R. Smith"` als gemeinsamen Kern

*Jaro / Jaro-Winkler*
- Speziell für kurze Strings (Vor- und Nachnamen)
- Berücksichtigt Transpositionen und gemeinsame Zeichen

==== Kategorie 2: Token-/Mengenbasierte Masse

*Grundidee:* String nicht als Zeichenfolge, sondern als *Menge von Tokens* behandeln.

*Tokenisierung:*
- Nach Wörtern: `"david smith"` → `{"david", "smith"}`
- Nach n-Grammen (Teilstrings Länge n, z.B. n=3): `"david"` → `{##d, #da, dav, avi, vid, id#, d##}`
- Optional: Stoppwörter entfernen (das, und, von), Stemming anwenden

*Jaccard-Koeffizient* — sehr verbreitet!

$J(A, B) = frac(abs(A sect B), abs(A union B))$

Wobei $A$ und $B$ die Token-Mengen der beiden Strings sind.

- $J = 1$: identisch
- $J = 0$: kein gemeinsames Token
- $J = 0.5$: Hälfte der Tokens gemeinsam

*Beispiel:*
- $A = {"david", "smith"}$, $B = {"dave", "smith"}$
- $A sect B = {"smith"}$, $A union B = {"david", "smith", "dave"}$
- $J = frac(1, 3) approx 0.33$

*TF/IDF (Term Frequency / Inverse Document Frequency)*
- Mass aus dem Information Retrieval
- Häufige Tokens werden weniger gewichtet als seltene, charakteristische Tokens

==== Hybride und phonetische Masse

- *Generalized Jaccard*, *Soft TF/IDF*, *Monge-Elkan*: Kombinieren mehrere Ansätze
- *Soundex*: Phonetisches Mass — klingt es gleich? (`"Schmidt"` ≈ `"Schmid"`)

#cheat-box[
*Welches Ähnlichkeitsmass wählen?*

- Kurze Strings, Tippfehler in einzelnen Zeichen → *Levenshtein / Edit-Distanz*
- Kurze Namen, Transpositionen → *Jaro-Winkler*
- Lange Strings mit gemeinsamen Teilbereichen → *Smith-Waterman*
- Mehrwörtige Strings, Wortmengen → *Jaccard*
- Wenn häufige Wörter weniger zählen sollen → *TF/IDF*
- Klang wichtiger als Schreibweise → *Soundex*
]

---

== Teil 4: Datenabgleich (Data Matching)

=== Abgrenzung zu String Matching

| Merkmal | String Matching | Data Matching |
|---------|----------------|---------------|
| Einheit | Strings | Tupel / Datensätze |
| Beispiel | `"D. Smith"` vs. `"David Smith"` | `(D. Smith, 245-4367, Madison)` vs. `(David Smith, 608-245-4367, Madison WI)` |
| Technik | Ähnlichkeitsmasse auf Strings | Kombination von Feldern, domänenspezifisches Wissen |

*Typische Szenarien:*
- Zusammenführen zweier Datenbanken mit gleichem Schema
- Zusammenführen aus Quellen mit unterschiedlichen Schemata
- Abgleich einer Benutzerabfrage mit einem Datenelement

=== Vier Techniken zum Datenabgleich

1. *Rule-based Matching* — Experten definieren Regeln (z.B. `IF name_similarity > 0.8 AND zip = zip THEN match`)
2. *Learning-based Matching* — Maschinelles Lernen trainiert auf Beispiel-Matches
3. *Matching by Clustering* — Ähnliche Datensätze werden in Cluster gruppiert
4. *Probabilistic Matching (Bayes)* — Wahrscheinlichkeitsbasiert: Wie wahrscheinlich ist ein Match gegeben die Übereinstimmung bei Feld X?

---

== Teil 5: Datenanreicherung (Data Enrichment)

=== Kernidee

Datenanreicherung = bestehende Daten mit Daten Dritter aus externen Quellen zusammenführen, verknüpft über gemeinsame *Schlüsselattribute* (z.B. PLZ, Ortsname, Koordinaten).

=== Quellen für Anreicherungsdaten

1. *Open Government Data* — offene Behördendaten (Beispiel: PLZ-Liste der Schweizerischen Post)
2. *Open Public Data* (crowdsourced) — Wikipedia, Wikidata, OpenStreetMap, Flickr
3. *Open Corporate Data* — Firmendaten, z.B. Google Earth Engine

=== Anwendungsbeispiele

*Bereinigung via Anreicherung:*
- Gegeben: Kundenliste mit PLZ+Ort
- Referenz: Gebäudeadressen von Post / OpenStreetMap
- Methode: Fuzzy Match von Kundenliste mit Referenzdaten
- Resultat: Kontrollierte, korrigierte Kundenliste

*Geocodierung (eigentliche Anreicherung):*

#formula-box[
*Rezept: Geocodierung*

1. Ausgangsdaten haben Adressen (Strasse, PLZ, Ort) aber keine Koordinaten
2. Referenzdatenbank mit Adressen+Koordinaten bereitstellen (GWR, OpenStreetMap)
3. Adress-Standardisierer normalisiert beide Seiten (einheitliches Format)
4. Matcher verknüpft Quelladressen mit Referenzadressen (exakt oder fuzzy)
5. Koordinaten (Latitude/Longitude) werden dem Quelldatensatz hinzugefügt

*Ergebnis:*

Vorher: `Hauser, Pascal, Röschibachstr. 77, 8037 Zürich`

Nachher: `Hauser, Pascal, Röschibachstr. 77, 8037 Zürich, lat=47.393, lon=8.529`

Die Koordinaten erlauben anschliessend Kartenvisualisierungen.
]

---

== Teil 6: Synthetische Datengenerierung

=== Warum synthetische Daten?

- Echte Daten haben Lücken
- Zugang zu echten Daten eingeschränkt (Datenschutz, DSGVO)
- Echte Daten noch nicht vorhanden (neue Systeme)
- Tests benötigen reproduzierbare Daten

*Anwendungen:* ML-Modelltraining, Softwaretests, Datenbankoptimierung, Veröffentlichung offener Daten

=== Drei Typen synthetischer Daten

1. *Anonymized Data* — echte Daten, aber persönliche Merkmale maskiert/ersetzt
2. *Artificial Data* — künstlich erzeugt, basiert nicht auf echten Einzeldaten
3. *(Pure) Synthetic Data* — vollständig generiert, kein Bezug zu echten Daten

=== Synthetische Datengenerierung mit PostgreSQL SQL

#formula-box[
*Rezept: Synthetische Testdaten mit SQL generieren*

```sql
SELECT
  -- Zufällige ganze Zahl zwischen lower_bound und upper_bound
  round(random() * (upper_bound - lower_bound) + lower_bound)::int AS i,
  -- Zufällige Dezimalzahl zwischen 0 und 1
  random() AS d,
  -- Zufälliger String (via MD5-Hash)
  upper(substr(md5(random()::text), 1, upper_bound)) AS str,
  -- Zufälliger Boolean
  random() > 0.5 AS bool,
  -- Zufälliger Timestamp in einem Bereich
  '2023-04-04'::timestamp
    + (random() * interval '1 month')
    - interval '1 months' AS dt
FROM generate_series(1, 5) AS series,  -- 5 Zeilen erzeugen
LATERAL (SELECT 1 AS lower_bound, 4 AS upper_bound) AS bound
ORDER BY dt DESC;
```

*Schlüsselfunktionen:*
- `generate_series(start, end)` — erzeugt N Zeilen
- `random()` — Zufallszahl $in [0, 1)$
- `md5(random()::text)` — zufälliger Hash-String
- `LATERAL (SELECT ...)` — definiert benannte Konstanten (lower/upper bound)
]

=== PostgreSQL Anonymizer

Gehört zum Typ "Anonymized Data":

```sql
SECURITY LABEL FOR anon
ON COLUMN customer.lastname
IS 'MASKED WITH FUNCTION anon.fake_last_name()';
```

*Vier Maskierungsmodi:*

1. *Statische Maskierung* — PII dauerhaft aus der Datenbank entfernen (irreversibel)
2. *Dynamische Maskierung* — PII nur für bestimmte Benutzer verstecken (View-basiert)
3. *Generalisierung* — "verschwommene" Ansichten für Statistik und ML
4. *Anonyme Dumps* — maskierte Daten als SQL-Datei exportieren (gut für CI/CD)

=== Tools für synthetische Datengenerierung

| Tool | Sprache | Lizenz | Beschreibung |
|------|---------|--------|--------------|
| Faker (Python) | Python | MIT | Fake-Daten: Namen, Adressen, E-Mails |
| SDV (Synthetic Data Vault) | Python | Business Source | Tabellarische synthetische Daten |
| PostgreSQL Anonymizer | Ruby | PostgreSQL Lic. | Anonymisierung in PostgreSQL |
| PGFaker | TypeScript | MIT | Faker für PostgreSQL |
| pgsynthdata (OST) | Python | MIT | Syntax via `COMMENT ON COLUMN` |
| Plain SQL | SQL | — | `generate_series()` + `random()` |

---

== Teil 7: Apache Hop — Praktische ETL-Pipelines

=== Was ist Apache Hop?

Apache Hop ist ein *grafisches ETL/ELT-Tool* (Hybrid-Kategorie):
- Open Source, Java, sehr aktiv
- Desktop-GUI + Web-Variante + Batch-Tool
- Kombiniert Datenflussmanagement mit Dataprocessing
- Unterstützt zahlreiche Quellen und Ziele (CSV, JSON, Datenbanken, ...)

=== Grundkonzepte

*Projekt* = organisatorische Einheit, hat ein eigenes Verzeichnis (`Home folder`). Variable `${PROJECT_HOME}` zeigt auf dieses Verzeichnis.

*Pipeline* = gerichteter Graph von *Blöcken* (Transforms), verbunden durch *Hops* (Pfeile).

*Hops:*
- *Grüner Hop* = Datensätze, bei denen Bedingung erfüllt (True)
- *Oranger Hop* = Datensätze, bei denen Bedingung nicht erfüllt (False/Fehler)

=== Apache Hop Projekt erstellen

#formula-box[
*Rezept: Neues Projekt in Apache Hop anlegen*

1. Icon unten links anklicken → "Add project..." wählen
2. Name eingeben (z.B. `Sales`)
3. "Browse" neben "Home folder" → neues Verzeichnis erstellen, gleich wie Projektname benennen
4. Dialog "Create project lifecycle environment?" mit "No" schliessen
5. CSV-Dateien in das Projektverzeichnis kopieren
]

=== Wichtige Apache Hop Blöcke (Transforms)

==== CSV File Input — Daten einlesen

#formula-box[
*Rezept: CSV-Datei einlesen*

1. Block "CSV file input" in Pipeline einfügen
2. Einstellungen:
   - Filename: `${PROJECT_HOME}/dateiname.csv`
   - Delimiter: `,` (oder `;` je nach Datei)
   - Enclosure: `"`
   - "Lazy conversion?" Häkchen *entfernen* (sonst werden Typen nicht korrekt erkannt)
3. Button "Get Fields" klicken → Felder und Datentypen automatisch ermitteln
4. Datentypen prüfen und ggf. korrigieren (z.B. POSTALCODE → `String` statt Integer!)
5. Trim type auf `both` setzen für Felder, die als Lookup-Schlüssel dienen

*Wichtig:* Postleitzahlen immer als `String` einlesen (führende Nullen gehen sonst verloren, z.B. "0815" wird zu 815).
]

#warn-box[
*Häufiger Fehler: Lazy Conversion aktiviert lassen.* Dann werden Datentypen nicht korrekt erkannt und spätere Lookups schlagen fehl. Immer deaktivieren!

*Häufiger Fehler: Trim type vergessen.* Felder mit führenden/nachfolgenden Leerzeichen matchen beim Lookup nicht. Bei allen Join-/Lookup-Schlüsseln `Trim type = both` setzen.
]

==== Filter Rows — Datensätze aufteilen

#formula-box[
*Rezept: Datensätze nach Bedingung aufteilen*

1. Block "Filter rows" einfügen
2. Bedingung definieren (z.B. `POSTALCODE IS NULL` oder `POSTALCODE = ""`)
3. Grünen Hop → für erfüllte Bedingung (True)
4. Orangen Hop → für nicht erfüllte Bedingung (False)
5. Dummy-Blöcke am Ende zum Testen verwenden

*Anwendung:* Fehlende Werte erkennen, Datensätze in zwei Streams aufteilen
]

==== Stream Lookup — Fehlende Werte ergänzen

#formula-box[
*Rezept: Lookup (fehlende Werte aus Referenztabelle ergänzen)*

1. Referenzdaten (z.B. zipssorted.csv) separat einlesen
2. Block "Stream lookup" einfügen
3. Einstellungen:
   - "Lookup step": Welcher Block liefert die Referenzdaten?
   - "The key(s) to look up the value(s)": Schlüsselfelder aus Hauptdaten (z.B. CITY, STATE)
   - "Fields to retrieve": Welches Feld aus der Referenz soll hinzugefügt werden (z.B. POSTALCODE → als ZIP_RESOLVED)
4. Der Block fügt ein neues Feld hinzu (z.B. `ZIP_RESOLVED`)

*Achtung:* Datentypen der Schlüsselfelder müssen auf beiden Seiten identisch sein!
]

==== Select Values — Felder umbenennen und ersetzen

#formula-box[
*Rezept: Felder umbenennen, ersetzen, neu anordnen*

1. Block "Select values" einfügen
2. Reiter "Select & Alter":
   - "Get Fields to select" klicken → alle Felder werden eingetragen
   - Feld verschieben: `ZIP_RESOLVED` an Position von `POSTALCODE` schieben
   - `POSTALCODE` aus Liste entfernen
3. Reiter "Meta-data":
   - `ZIP_RESOLVED` umbenennen zu `POSTALCODE`

*Merke:* Select values kann drei Dinge:
- Felder auswählen/ausschliessen (Reiter "Select & Alter")
- Felder umbenennen (Reiter "Meta-data")
- Datentypen ändern (Reiter "Meta-data")
]

==== Append Streams — Streams zusammenführen

*Zweck:* Zwei Datenströme (z.B. Datensätze mit und ohne PLZ nach Ergänzung) wieder zusammenführen.
- "Head step": Datensätze die zuerst kommen sollen
- "Tail step": Datensätze die am Ende angefügt werden sollen

#warn-box[
`Append streams` setzt voraus, dass beide Streams *dasselbe Schema* haben (gleiche Felder, gleiche Typen). Bei unterschiedlichen Schemata zuerst mit `Select values` angleichen!
]

==== Value Mapper — Werte ersetzen

#formula-box[
*Rezept: Einzelne Feldwerte ersetzen*

1. Block "Value mapper" einfügen
2. Field name: Zu bereinigendes Feld (z.B. `COUNTRY`)
3. Mapping:
   - Source value: `United States`
   - Target value: `USA`
4. Default: Wert für nicht gemappte Einträge (leer = unverändert lassen)

*Anwendung:* Inkonsistente Bezeichnungen vereinheitlichen (klassische Datenbereinigung)
]

==== Number Range — Numerische Kategorisierung

#formula-box[
*Rezept: Numerischen Wert in Kategorie umwandeln*

1. Block "Number range" einfügen
2. Input field: Numerisches Quellfeld (z.B. `ORDER_AMOUNT`)
3. Output field: Name des neuen Feldes (z.B. `ORDER_SIZE`)
4. Bereiche definieren:
   - Lower bound | Upper bound | Value (Kategorie-Label)
   - z.B.: 0 | 100 | "small", 100 | 1000 | "medium", 1000 | ∞ | "large"

*Anwendung:* Bestellgrössen kategorisieren, Altersgruppen bilden, Preisklassen zuweisen
]

==== Table Output — In Datenbank schreiben

#formula-box[
*Rezept: Daten in Datenbank-Tabelle schreiben*

1. Datenbank vorher manuell erstellen (Apache Hop kann keine DB erstellen!):
   ```sql
   CREATE DATABASE sampledata;
   ```
2. Block "Table output" in Pipeline einfügen (ersetzt Dummy am Ende)
3. Datenbankverbindung konfigurieren:
   - Datenbank-Icon klicken
   - Typ, Host, Port, DB-Name, Benutzername, Passwort eingeben
   - "Test" klicken um Verbindung zu prüfen
4. Target Table: Tabellenname eingeben (z.B. `SALES_DATA`)
5. Button "SQL" klicken → zeigt CREATE TABLE Statement
6. "Execute" klicken → Tabelle wird erstellt
7. Pipeline ausführen
]

#warn-box[
Apache Hop kann *keine Datenbank erstellen* — nur Tabellen in bestehenden Datenbanken. Datenbank vorher im DBMS anlegen!
]

==== Formula — Berechnungen durchführen

#formula-box[
*Rezept: Neue berechnete Felder hinzufügen*

1. Block "Formula" einfügen
2. Felder ohne Sonderzeichen im Namen verwenden (erst mit "Select values" umbenennen, Klammern entfernen!)
3. Neues Feld definieren:
   - New field: Name des Ergebnisfeldes (z.B. `temp_celsius`)
   - Formula: mathematischer Ausdruck (z.B. `[kelvin] - 273.15`)
   - Return type: Datentyp des Ergebnisses

*Temperaturumrechnung (Beispiel Aufgabe 8):*
- Kelvin → Celsius: $T_C = T_K - 273.15$
- Kelvin → Fahrenheit: $T_F = (T_K - 273.15) times 1.8 + 32$

*Wichtig:* Falls nicht alle Datensätze einen Wert haben (NULL), Formel entsprechend absichern (NULL-Werte führen zu NULL im Ergebnis — das ist korrekt).
]

#warn-box[
*Häufiger Fehler:* Feldnamen mit Klammern `()` im Namen (z.B. `Boiling Point (K)`) verursachen Fehler in Formeln. *Zuerst* mit "Select values" → Reiter "Meta-data" umbenennen (z.B. `boiling_K`), *dann* Formula-Block verwenden!
]

==== Zusammenführen ungleicher Datensätze (Aufgabe 7)

#formula-box[
*Rezept: Zwei CSV-Dateien mit unterschiedlichen Schemata zusammenführen*

Wenn zwei Dateien nicht dasselbe Schema haben, vor `Append streams` angleichen:

*Für fehlende Felder:*
- Block "Add constants" oder "Set field value" → Standardwert hinzufügen
- Beispiel: Feld `ranking` fehlt in Datei A → mit Wert `0.0` ergänzen

*Für NULL-Werte:*
- Block "If field value is null" → NULL durch Standardwert ersetzen
- Beispiel: `alter` ist NULL → durch `0` ersetzen

*Für Feldumbenennung:*
- Block "Select values" → Reiter"Meta-data" → Feld umbenennen
- Beispiel: Feld `name` in Datei B → umbenennen zu `nachname`

*Reihenfolge:*
1. Datei A einlesen → fehlende Felder ergänzen + NULLs ersetzen
2. Datei B einlesen → Felder umbenennen
3. Beide Streams mit `Append streams` zusammenführen
4. Ausgabe als CSV (Block "Text file output") und JSON (Block "Json output")
]

=== Übersicht: Apache Hop Blöcke und ihre Verwendung

#cheat-box[
*Wenn Aufgabe X, dann Block Y:*

- CSV-Datei einlesen → *CSV file input*
- Datensätze nach Bedingung aufteilen → *Filter rows*
- Fehlenden Wert aus Referenztabelle nachschlagen → *Stream lookup*
- Feld umbenennen / entfernen / Typ ändern → *Select values*
- Zwei Streams zusammenführen (gleiches Schema) → *Append streams*
- Einzelne Feldwerte ersetzen (z.B. "United States" → "USA") → *Value mapper*
- Numerischen Wert kategorisieren (Bereiche) → *Number range*
- Berechnung / Formel auf Feld anwenden → *Formula*
- Fehlenden Feldwert mit Konstante füllen → *Add constants*
- NULL durch Standardwert ersetzen → *If field value is null*
- Daten in DB-Tabelle schreiben → *Table output*
- Daten als CSV schreiben → *Text file output*
- Daten als JSON schreiben → *Json output*
- Pipeline-Endpunkt zum Testen → *Dummy*
]

=== Typischer Pipeline-Aufbau in Apache Hop

#tip-box[
*Erkennungsmuster für Pipeline-Strukturen:*

*Einfaches Einlesen + Ausgabe:*
```
CSV file input → Dummy
```

*Filtern + Aufteilen:*
```
CSV file input → Filter rows →(grün)→ Dummy (OK)
                             →(orange)→ Dummy (fehlerhaft)
```

*Lookup + Zusammenführen:*
```
CSV file input (Hauptdaten) →─────────────────────────┐
                              Filter rows              │
                             →(grün OK)→ Append streams → Dummy
                             →(orange fehlend)→ Stream lookup → Select values →┘
CSV file input (Referenz) ──→ Stream lookup
```

*Bereinigen + Kategorisieren:*
```
CSV file input → Value mapper → Number range → Table output
```

*Unterschiedliche Quellen zusammenführen:*
```
CSV file input (A) → Select values / Add constants / If null →┐
                                                               Append streams → Output
CSV file input (B) → Select values (umbenennen) ──────────────┘
```
]

---

== Zusammenfassung: Konzepte auf einen Blick

#cheat-box[
*Schnellreferenz: Welches Konzept bei welcher Aufgabenstellung?*

- "Finde gleiche Einträge in einer Tabelle" → *Exakte Duplikaterkennung* mit ROW_NUMBER + PARTITION BY
- "Finde ähnliche Strings trotz Tippfehlern" → *Levenshtein-Distanz* (kurze Strings) oder *Jaccard* (Wortmengen)
- "Gleiche Entität in zwei verschiedenen Datenbanken" → *Data Matching* (Rule-based, Learning-based, Clustering, Bayes)
- "Fehlende Spalten aus externer Quelle ergänzen" → *Datenanreicherung*, Lookup via gemeinsames Schlüsselattribut
- "Adresse → Koordinaten" → *Geocodierung* (Adress-Standardisierer + Referenz-DB + Matcher)
- "Testdaten ohne Datenschutzproblem erzeugen" → *Synthetische Datengenerierung* (SQL generate_series, Faker, SDV)
- "Echte Daten anonymisieren" → *PostgreSQL Anonymizer* (statisch, dynamisch, Generalisierung, anonyme Dumps)
- "ETL-Pipeline grafisch bauen" → *Apache Hop* (Hybrid-Tool, OSS, Java)
- "Welches ETL-Tool für Geodaten?" → *FME*, alternativ Apache Hop, KNIME, Looker Studio
- "Workflow orchestrieren (kein starkes Transformieren)" → *Apache Airflow* (Python, OSS)
- "Echtzeit-Datenfluss mit Web-GUI" → *Apache NiFi* (Java, OSS)
- "Transformation nur innerhalb Data Warehouse / Cloud" → *dbt* (Python, OSS+komm.)
]

#warn-box[
*Die häufigsten Fehler in Prüfung und Übung:*

1. *POSTALCODE als Integer einlesen* → führende Nullen gehen verloren, Lookup schlägt fehl. Immer `String`!
2. *Lazy Conversion aktiviert lassen* → falsche Datentypen, Lookup-Fehler. Immer deaktivieren!
3. *Trim type vergessen* → Leerzeichen in Schlüsselfeldern verhindern Matches. Bei allen Join-Keys `both` setzen.
4. *Felder mit Sonderzeichen (Klammern) in Formula verwenden* → Syntaxfehler. Erst umbenennen!
5. *Append streams ohne Schemaangleich* → Felder fehlen oder haben falsche Typen. Erst mit Select values / Add constants angleichen.
6. *Datenbank nicht vorher erstellen* → Apache Hop kann keine Datenbank anlegen, nur Tabellen darin.
7. *Edit-Distanz für lange Texte verwenden* → sehr langsam und ungenau. Besser: Jaccard oder TF/IDF.
8. *Data Matching und String Matching verwechseln* → Matching arbeitet auf Tupeln (mehrere Felder zusammen), String Matching nur auf einzelnen Strings.
]