// Auto-generated by RAG system on 2026-05-09
// Week 9 — do not edit the header

#import "../../template.typ": tip-box, warn-box, formula-box, cheat-box

== Woche 9: Introduction and Preprocessing (1)

= Data Science & Data Mining — Grundlagen

== Was ist Data Science und Data Mining?

*Kernidee:* Data Science ist das übergeordnete Feld, das den gesamten Lebenszyklus der Datenarbeit umfasst — von der Datensammlung bis zur Präsentation von Erkenntnissen. Data Mining ist ein Teilbereich davon, der sich speziell auf das automatische Extrahieren von Mustern und Wissen aus (grossen) Datensätzen konzentriert.

#tip-box[
*Wie unterscheide ich Data Science von Data Mining?*

- *Data Mining* = Teilprozess: Muster aus Rohdaten extrahieren, Algorithmen anwenden, KDD-Schritt (Knowledge Discovery in Databases)
- *Data Science* = Oberbegriff: umfasst zusätzlich Datensammlung, Bereinigung, Visualisierung, Kommunikation, Domänenwissen, ML-Integration
- Analogie: Data Mining ist wie das Graben nach Gold — Data Science umfasst auch den Bau der Mine, den Transport und den Verkauf des Goldes.

*Beziehung zu Machine Learning:*
- Viele DM-Algorithmen sind identisch mit ML-Algorithmen
- Data Mining liefert oft Trainingsdaten und Feature-Verständnis für ML-Modelle
- ML ist ein Werkzeugkasten, den Data Mining benutzt
]

== CRISP-DM — Der Standard-Prozess

*Kernidee:* CRISP-DM (Cross-Industry Standard Process for Data Mining) beschreibt 6 Phasen, die _iterativ_ und nicht strikt sequenziell durchlaufen werden. Rücksprünge sind normal und gewollt.

#formula-box[
*Die 6 CRISP-DM Phasen im Überblick:*

1. *Business Understanding* — Ziele definieren: Was will das Unternehmen erreichen? Welche Fragen sollen beantwortet werden? Grober Plan wird erstellt.

2. *Data Understanding* — Daten sammeln und erstmalig sichten: Welche Daten existieren? Gibt es Qualitätsprobleme? Erste Exploration.

3. *Data Preparation* — Rohdaten bereinigen, transformieren, in das richtige Format bringen, für Modellierung vorbereiten. _Dieser Schritt benötigt am meisten Zeit (~60–80% des Aufwands)._

4. *Modeling* — Geeignete Data-Mining-Methoden auswählen und anwenden. Parameter optimieren. Mehrere Modelle ausprobieren.

5. *Evaluation* — Bestes Modell auswählen. Prüfen ob das Modell die Geschäftsfrage wirklich beantwortet. Genauigkeit beurteilen. _Wenig Aufwand dank automatisierter Metriken._

6. *Deployment* — Ergebnisse präsentieren oder Modell in Entscheidungsprozesse integrieren.

*Merkhilfe:* Bu-Du-Da-Mo-Ev-De → "Businessleute Denken Daran, Modelle Endlich Darzustellen"
]

#tip-box[
*Warum ist Data Preparation so aufwändig?*
- Daten kommen aus heterogenen Quellen mit verschiedenen Formaten
- Fehlende, fehlerhafte, doppelte Werte müssen manuell oder halbautomatisch korrigiert werden
- Grosse Datensätze erfordern viel Rechenleistung
- "Garbage in, garbage out" — schlechte Daten → schlechte Modelle

*Warum ist Evaluation weniger aufwändig?*
- Standardisierte, automatisierte Metriken verfügbar (Accuracy, F1, RMSE, ...)
- Strukturierter Prozess, klare Vergleichskriterien
]

== Die vier Data-Mining-Aufgabentypen

*Kernidee:* Jede Data-Mining-Aufgabe fällt in eine von vier Kategorien. Die Erkennung des Typs bestimmt, welche Methode eingesetzt wird.

#cheat-box[
*Wenn X, dann Y — Welcher Aufgabentyp ist es?*

| Fragestellung | Typ | Methoden | Beispiel |
|---|---|---|---|
| Welche Dinge treten _gemeinsam_ auf? | *Association* | Market Basket Analysis, Apriori | Bier + Windeln |
| In welche _Gruppen_ lassen sich Daten einteilen? | *Clustering* | k-Means, hierarchisch, DBSCAN | Kundensegmente |
| Zu welcher _vordefinierten Kategorie_ gehört X? | *Classification* | Decision Trees, Naive Bayes, kNN | Spam/kein Spam |
| Welchen _numerischen Wert_ wird X haben? | *Regression* | Lineare/multiple Regression | Eiscremeverkäufe |
| Ist X _ungewöhnlich_? | *Anomaly Detection* | Outlier Detection | Kreditkartenbetrug |

*Schlüsselunterschied Classification vs. Clustering:*
- Classification: Labels sind _bekannt_ (supervised), neuen Datenpunkt einordnen
- Clustering: Labels sind _unbekannt_ (unsupervised), Gruppen selbst entdecken

*Schlüsselunterschied Regression vs. Classification:*
- Regression → numerischer, kontinuierlicher Output (Alter, Preis, Umsatz)
- Classification → kategorischer Output (ja/nein, Spam/Ham, Klasse A/B/C)
]

= Was sind Daten? — Datentypen und Attribute

== Datenstruktur: Objekte und Attribute

*Kernidee:* Ein Dataset besteht aus Data Objects (Zeilen), die durch Attribute (Spalten) beschrieben werden. Jedes Attribut hat einen Typ, der bestimmt, welche Operationen sinnvoll sind.

*Begrifflichkeiten:*
- Data Object = Sample, Instance, Data Point, Tuple (z.B. ein Kunde, ein Patient)
- Attribut = Feature, Variable, Dimension (z.B. Alter, Farbe, Temperatur)
- Beobachtung = konkreter Wert eines Attributs (z.B. "rot", 37.2)
- Feature Vector = alle Attribute eines Objekts zusammen

== Attributtypen — Das wichtigste Klassifikationssystem

*Kernidee:* Der Attributtyp bestimmt, welche statistischen Operationen (Mean, Median, Mode) sinnvoll sind und welche Mathe erlaubt ist.

#formula-box[
*Attributtypen — Übersicht und Entscheidungsregeln:*

*1. Nominal (kategorisch)*
- Werte sind Namen/Kategorien ohne sinnvolle Reihenfolge
- Beispiele: Haarfarbe (schwarz, braun, blond), Städtenamen, Länder, Firmenname
- Spezialfall *Binary*: nur 2 mögliche Werte (ja/nein, männlich/weiblich)
- Erlaubte Operationen: nur Mode (häufigster Wert)
- Mean und Median: _nicht sinnvoll_

*2. Ordinal*
- Werte haben eine sinnvolle Reihenfolge, aber Abstände sind nicht messbar
- Beispiele: Schulnoten (1–6), T-Shirt-Grössen (S, M, L, XL), Kundenzufriedenheit (schlecht/mittel/gut)
- Erlaubte Operationen: Mode und Median sinnvoll
- Mean: _nicht sinnvoll_ (der Abstand zwischen S und M ist nicht definiert)

*3. Cardinal (numerisch) — Untertypen:*

*Interval-skaliert:*
- Gleiche Abstände zwischen Werten, aber kein absoluter Nullpunkt
- "0" bedeutet nicht "nichts vorhanden"
- Beispiele: Temperatur in °C (0°C = nicht "keine Temperatur"), Kalenderjahr
- Erlaubt: Mean, Median, Mode, Addition/Subtraktion
- _Kein Verhältnis_: Man kann nicht sagen "20°C ist doppelt so warm wie 10°C"

*Ratio-skaliert:*
- Wie Interval, _aber_ mit echtem absolutem Nullpunkt
- "0" bedeutet wirklich "nichts"
- Beispiele: Gewicht (0 kg = kein Gewicht), Grösse, Einkommen, Alter
- Erlaubt: Mean, Median, Mode, alle arithmetischen Operationen
- Verhältnisse sind sinnvoll: "60 kg ist doppelt so schwer wie 30 kg"
]

#tip-box[
*Woran erkenne ich den Attributtyp in einer Aufgabe?*

Frage dich:
1. Kann ich die Werte sinnvoll sortieren? → Nein: *Nominal*; Ja: weiter zu 2
2. Sind die Abstände zwischen Werten gleichmässig und messbar? → Nein: *Ordinal*; Ja: weiter zu 3
3. Gibt es einen echten Nullpunkt (0 = "nichts")? → Ja: *Ratio*; Nein: *Interval*

*Schnelltabelle — Was ist erlaubt?*

| Operation | Nominal | Ordinal | Interval | Ratio |
|---|---|---|---|---|
| Mode | ✓ | ✓ | ✓ | ✓ |
| Median | ✗ | ✓ | ✓ | ✓ |
| Mean | ✗ | ✗ | ✓ | ✓ |
| Verhältnisse (×, ÷) | ✗ | ✗ | ✗ | ✓ |
]

#warn-box[
*Häufiger Fehler: Temperatur in °C vs. Kelvin*
- Temperatur in °C: _Interval-skaliert_ (kein echter Nullpunkt)
- Temperatur in Kelvin: _Ratio-skaliert_ (0 K = absoluter Nullpunkt)
- "20°C ist doppelt so warm wie 10°C" ist FALSCH (in Kelvin wäre das 293 K vs. 283 K)

*Häufiger Fehler: IQ-Werte*
- IQ ist _Interval-skaliert_, nicht Ratio
- IQ 0 bedeutet nicht "keine Intelligenz"
- Man kann nicht sagen "IQ 120 ist doppelt so intelligent wie IQ 60"
]

= Datenqualität und Preprocessing

== Datenqualität — Dimensionen

*Kernidee:* Schlechte Datenqualität führt direkt zu schlechten Mining-Ergebnissen ("Garbage in, garbage out"). Datenqualität wird durch mehrere Dimensionen definiert.

*Dimensionen der Datenqualität:*
- *Accuracy* — Sind die Werte korrekt? (z.B. negativer Preis -100 CHF)
- *Completeness* — Fehlen Werte? (Missing Values)
- *Consistency* — Widersprüche oder verschiedene Formate für dasselbe? (01/02/2025 vs. 2025/02/01)
- *Timeliness* — Sind die Daten aktuell genug?
- *Believability* — Sind die Daten glaubwürdig?
- *Interpretability* — Sind die Daten verständlich dokumentiert?

== Preprocessing-Techniken

*Kernidee:* Vier Haupttechniken verbessern gemeinsam die Datenqualität vor dem eigentlichen Mining.

#cheat-box[
*Preprocessing-Techniken — Wann welche?*

- *Data Integration* → Wenn Daten aus mehreren Quellen kommen und zusammengeführt werden müssen
- *Data Cleaning* → Wenn fehlende Werte, Rauschen, Ausreisser oder Inkonsistenzen vorhanden sind
- *Data Reduction* → Wenn der Datensatz zu gross ist oder irrelevante Features entfernt werden sollen
- *Data Transformation* → Wenn Werte in andere Skalierungen oder Formate gebracht werden müssen (z.B. Normalisierung)
]

= Statistische Grundlagen — Lagemasse

== Arithmetisches Mittel (Mean)

*Kernidee:* Der Durchschnitt aller Werte — misst das "Zentrum" eines Datensatzes, ist aber empfindlich gegenüber Ausreissern.

#formula-box[
*Formel und Rezept:*

Gegeben: $N$ Beobachtungen $x_1, x_2, ..., x_N$ eines Attributs $X$

$ overline(x) = frac(sum_(i=1)^N x_i, N) $

*Gewichtetes Mittel* (wenn jeder Wert ein Gewicht $w_i$ hat):

$ overline(x) = frac(sum_(i=1)^N w_i x_i, sum_(i=1)^N w_i) $

*Rezept:*
1. Alle Werte aufsummieren: $S = x_1 + x_2 + ... + x_N$
2. Durch Anzahl der Werte dividieren: $overline(x) = frac(S, N)$

*Beispiel* (Temperaturen aus Vorlesung, $N = 14$):
$S = 28.3 + 27.2 + 27.4 + 22.7 + 14.3 + 11.9 + 13.8 + 19.8 + 9.6 + 21.1 + 20.8 + 19.8 + 25.3 + 22.8 = 284.8$
$overline(x) = frac(284.8, 14) = 20.34$

*Übungsaufgabe 9a* (Alter, $N = 27$):
$S = 809$, $overline(x) = frac(809, 27) approx 29.96$
]

#warn-box[
*Mean ist sensitiv gegenüber Ausreissern!*
- Ein einzelner extrem hoher/niedriger Wert verschiebt den Mean stark
- Lösung: *Trimmed Mean* — die obersten und untersten $k$% der Werte entfernen, dann Mean berechnen
- Bei schiefen Verteilungen ist Median robuster als Mean
]

== Median

*Kernidee:* Der mittlere Wert in einer sortierten Reihe — robuster als der Mean bei Ausreissern.

#formula-box[
*Rezept zur Median-Berechnung:*

1. *Daten sortieren* (aufsteigend) — dieser Schritt wird oft vergessen!
2. Anzahl der Werte $N$ bestimmen
3. Falls $N$ *ungerade*: Median = Wert an Position $frac(N+1, 2)$
4. Falls $N$ *gerade*: Median = Durchschnitt der Werte an Position $frac(N, 2)$ und $frac(N, 2) + 1$

*Beispiel ungerade* ($N = 27$, Alters-Daten sortiert):
Position des Medians = $frac(27+1, 2) = 14$ → 14. Wert in sortierter Reihe
Sortiert: 13, 15, 16, 16, 19, 20, 20, 21, 22, 22, 25, 25, 25, *25*, 30, 33, 33, 35, 35, 35, 35, 36, 40, 45, 46, 52, 70
Median = *25*

*Beispiel gerade* ($N = 14$, Temperaturen):
Sortiert: 9.6, 11.9, 13.8, 14.3, 19.8, 19.8, *20.8*, *21.1*, 22.7, 22.8, 25.3, 27.2, 27.4, 28.3
Positionen 7 und 8: 20.8 und 21.1
Median $= frac(20.8 + 21.1, 2) = 20.95$
]

#warn-box[
*Häufigster Fehler beim Median: Vergessen zu sortieren!*
Die Musterlösung warnt explizit: "wenn nicht sortiert, dann kommt man aus 32.9 (typischer Fehler!)"
- *Immer* erst sortieren, dann Median berechnen
- Für %fat-Daten aus Aufgabe 10: sortiert ergibt sich Median 30.7, nicht 32.9
]

== Mode (Modalwert)

*Kernidee:* Der am häufigsten vorkommende Wert — der einzige Lage-Kennwert, der für alle Attributtypen (auch nominal) sinnvoll ist.

#formula-box[
*Rezept:*
1. Häufigkeit jedes Wertes zählen
2. Wert(e) mit der höchsten Häufigkeit = Mode

*Unimodal:* Ein Mode → z.B. Mode = 19.8 (in Temperaturdaten, kommt 2× vor)
*Bimodal:* Zwei Modi → z.B. Mode = {25, 35} (in Altersdaten, beide kommen 4× vor)
*Multimodal:* Mehr als zwei Modi

*Beispiel* (Alters-Daten):
- 25 kommt 4× vor: 13, 15, 16, 16, 19, 20, 20, 21, 22, 22, *25, 25, 25, 25*, 30, ...
- 35 kommt 4× vor: ..., *35, 35, 35, 35*, 36, 40, ...
- Alle anderen Werte kommen seltener vor
- Ergebnis: Mode = {25, 35} → *bimodal*
]

= Statistische Grundlagen — Streumasse

== Range (Spannweite)

*Kernidee:* Einfachstes Mass für die Streuung — Differenz zwischen Maximum und Minimum.

$ R = max(X) - min(X) $

*Beispiel* (Temperaturen): $R = 28.3 - 9.6 = 18.7$
*Beispiel* (Alter): $R = 70 - 13 = 57$

*Nachteil:* Sehr empfindlich gegenüber Ausreissern — ein einzelner extremer Wert verändert den Range stark.

== Quantile und Quartile

*Kernidee:* $q$-Quantile teilen die sortierten Daten in $q$ gleichgrosse Gruppen auf. Die wichtigsten sind Quartile (4 Gruppen) und Perzentile (100 Gruppen).

#formula-box[
*Quartile berechnen — Rezept:*

1. Daten sortieren (aufsteigend)
2. *Median ($Q_2$)* berechnen (teilt Daten in zwei Hälften)
3. *$Q_1$* = Median der _unteren_ Hälfte (Werte unter dem Gesamtmedian)
4. *$Q_3$* = Median der _oberen_ Hälfte (Werte über dem Gesamtmedian)

*Wichtig:* Bei ungerader Anzahl von Werten wird der Median-Wert selbst typischerweise von beiden Hälften *ausgeschlossen* (Methode variiert je nach Software/Konvention — bei Handrechnung: Median aus den Werten links/rechts des Gesamtmedians).

*Beispiel* ($N = 27$ Alterswerte):
Sortiert: 13, 15, 16, 16, 19, 20, 20, 21, 22, 22, 25, 25, 25, | *25* | 30, 33, 33, 35, 35, 35, 35, 36, 40, 45, 46, 52, 70

Untere Hälfte (13 Werte links): 13, 15, 16, 16, 19, 20, *20*, 21, 22, 22, 25, 25, 25
→ $Q_1$ = Median = Wert an Position 7 = *20*
Aber: 7. und 8. Wert = 20 und 21 → $Q_1 = frac(20+21, 2) = 20.5$ _(gemäss Musterlösung)_

Obere Hälfte (13 Werte rechts): 30, 33, 33, 35, 35, 35, *35*, 36, 40, 45, 46, 52, 70
→ $Q_3$ = Median = Wert an Position 7 = *35*

*Interquartile Range (IQR):*
$ I Q R = Q_3 - Q_1 $
Beispiel: $I Q R = 35 - 20.5 = 14.5$
]

#warn-box[
*Verschiedene Quartilmethoden geben leicht unterschiedliche Ergebnisse!*
- In der Prüfung: bei Handrechnung den Median der unteren/oberen Hälfte verwenden
- Bei gerader Anzahl von Werten in jeder Hälfte: Durchschnitt der zwei mittleren Werte
- Konsistenz ist wichtiger als die exakte Methode — solange du erklärst was du tust
]

== Fünf-Zahlen-Zusammenfassung (Five-Number Summary)

*Kernidee:* Fünf Kennzahlen beschreiben die Verteilung vollständig — von den Extremen bis zur Mitte.

$ "Five-Number Summary" = {M i n i m u m, Q_1, M e d i a n (Q_2), Q_3, M a x i m u m} $

*Beispiel* (Altersdaten):
$ {13, quad 20.5, quad 25, quad 35, quad 70} $

== Boxplot

*Kernidee:* Visuelle Darstellung der Five-Number Summary — zeigt Verteilung, Streuung und Ausreisser auf einen Blick.

#formula-box[
*Boxplot zeichnen — Rezept:*

1. Box zeichnen von $Q_1$ bis $Q_3$ (Länge = IQR)
2. Linie in der Box bei $Q_2$ (Median)
3. *Whisker-Grenzen berechnen:*
   - Untere Grenze: $Q_1 - 1.5 times I Q R$
   - Obere Grenze: $Q_3 + 1.5 times I Q R$
4. Whisker reichen bis zum *letzten Datenpunkt innerhalb* der Grenzen (nicht bis zur Grenze selbst!)
5. Datenpunkte *ausserhalb* der Whisker-Grenzen = *Ausreisser* → einzeln einzeichnen (oft als Punkte/Sterne)

*Beispiel* (Altersdaten):
- $Q_1 = 20.5$, $Q_3 = 35$, $I Q R = 14.5$
- Untere Whisker-Grenze: $20.5 - 1.5 times 14.5 = 20.5 - 21.75 = -1.25$ → letzter Datenpunkt über -1.25 ist *13* → unterer Whisker bis 13
- Obere Whisker-Grenze: $35 + 1.5 times 14.5 = 35 + 21.75 = 56.75$ → letzter Datenpunkt unter 56.75 ist *52* → oberer Whisker bis 52
- Wert 70 > 56.75 → *Ausreisser*, einzeln markieren
]

#tip-box[
*Boxplot-Interpretation — Was sehe ich?*
- Box weit oben im Gesamtbereich → rechtsschiefe Verteilung (viele kleine Werte, wenige grosse)
- Median nahe an $Q_1$ → mehr Werte im oberen Bereich
- Langer oberer Whisker → Ausreisser nach oben
- Einzelne Punkte = Ausreisser = potentielle Datenfehler oder echte Extremwerte
]

== Varianz und Standardabweichung

*Kernidee:* Varianz misst die durchschnittliche quadratische Abweichung vom Mittelwert. Standardabweichung ist die Wurzel davon — leichter interpretierbar da in den Originaleinheiten.

#formula-box[
*Formeln:*

*Varianz* ($sigma^2$):
$ sigma^2 = frac(1, N) sum_(i=1)^N (x_i - overline(x))^2 $

*Standardabweichung* ($sigma$):
$ sigma = sqrt(sigma^2) = sqrt(frac(1, N) sum_(i=1)^N (x_i - overline(x))^2) $

*Rezept:*
1. Mean $overline(x)$ berechnen
2. Für jeden Wert $x_i$: Abweichung $(x_i - overline(x))$ berechnen
3. Abweichungen quadrieren: $(x_i - overline(x))^2$
4. Alle quadrierten Abweichungen summieren
5. Durch $N$ dividieren → Varianz $sigma^2$
6. Wurzel ziehen → Standardabweichung $sigma$

*Beispiel* (Temperaturdaten, $overline(x) = 20.34$, $N = 14$):
$sigma^2 = frac(1, 14) dot [(28.3 - 20.34)^2 + (27.2 - 20.34)^2 + ... ] approx 35.67$ → Musterlösung gibt $sigma = sqrt(35.67) approx 5.97$ als Varianz an _(hier als $sigma^2$ notiert, Werte aus Originalfolie)_

*Aufgabe 10 — Alters-Daten* ($N = 18$, $overline(x) = 46.4$):
$sigma^2 = 165.0247$, $sigma = 12.846$

*Aufgabe 10 — %fat-Daten* ($N = 18$, $overline(x) = 28.783$):
$sigma^2 = 80.886$, $sigma = 8.994$
]

#tip-box[
*Interpretation der Standardabweichung:*
- Kleine $sigma$ → Werte liegen nahe am Mean (geringe Streuung)
- Grosse $sigma$ → Werte sind weit verteilt (hohe Streuung)
- *68-Regel* (Normalverteilung): ca. 68% aller Werte liegen im Bereich $[overline(x) - sigma, overline(x) + sigma]$
- *Einheit:* $sigma$ hat dieselbe Einheit wie die Daten (z.B. Jahre, kg, °C)
- *Einheit von $sigma^2$:* Quadrat der Originaleinheit (z.B. Jahre²) → weniger intuitiv
]

#cheat-box[
*Welches Lagemass / Streumass bei welchem Datentyp?*

| | Nominal | Ordinal | Interval/Ratio |
|---|---|---|---|
| *Mean* | ✗ | ✗ | ✓ |
| *Median* | ✗ | ✓ (eingeschränkt) | ✓ |
| *Mode* | ✓ | ✓ | ✓ (mit Binning) |
| *Range* | ✗ | ✗ | ✓ |
| *IQR* | ✗ | ✗ | ✓ |
| *Varianz / $sigma$* | ✗ | ✗ | ✓ |

*Robustheit gegen Ausreisser:*
- Robust: Median, IQR, Trimmed Mean
- Nicht robust: Mean, Range, Varianz (durch quadrieren werden Ausreisser stark gewichtet)
]

= Datenvisualisierung — Überblick

== Histogramm

*Kernidee:* Zeigt die Häufigkeitsverteilung eines Attributs — für nominale Daten als Balkendiagramm (mit Lücken), für kardinale Daten als Histogramm (ohne Lücken, mit Bins).

*Für nominale Attribute:* Ein Balken pro Kategorie, Höhe = Häufigkeit
*Für kardinale Attribute:*
- Wertebereich in gleichbreite *Bins* aufteilen (equiwidth-binning)
- Höhe eines Bins = Anzahl Werte in diesem Bereich
- Gibt intuitiven Eindruck der Verteilungsform (symmetrisch, schief, bimodal?)

== Scatter Plot (Streudiagramm)

*Kernidee:* Visualisiert Beziehungen zwischen zwei Attributen — jeder Datenpunkt wird als Punkt im 2D-Raum dargestellt.

#tip-box[
*Wann verwende ich einen Scatter Plot?*
- Wenn ich wissen will: Gibt es eine Korrelation zwischen Attribut A und Attribut B?
- Erkennung von: Cluster, Ausreisser, lineare/nichtlineare Trends
- Funktioniert für alle Attributtypen (auch gemischt)

*Interpretation:*
- Punkte bilden eine Linie (aufwärts/abwärts) → positive/negative Korrelation
- Punkte ohne Muster → keine/schwache Korrelation
- Korrelationskoeffizient nahe ±1 → starke Korrelation (Aufgabe 10: 0.82 = starke positive Korrelation zwischen Alter und %fat)
]

== Weitere Visualisierungstypen

*Scatterplot Matrix:* $n times n$ Matrix aller paarweisen Scatter Plots für $n$-dimensionale Daten. Diagonale oft mit Histogrammen, oberes Dreieck mit Korrelationskoeffizienten. Wird bei höherer Dimensionalität unübersichtlich.

*Liniendiagramm (Line Graph):* Zeigt wie sich eine kontinuierliche Variable über eine andere verändert (meist Zeitreihen). Weit verbreitet in Finanzen, Marketing, Medizin.

*Q-Q-Plot (Quantile-Quantile Plot):* Prüft ob Daten normalverteilt sind.
- Punkte liegen auf der 45°