= Musterlösung Erweiterung des DW
:lang: de

Um die geforderten Abfragen zu ermöglichen,
ist es sinnvoll, in der neuen Faktentabelle
nicht jeden Zu- und Abgang aus den Lagern abzubilden,
sondern nur die resultierenden Bestandes-Mengen am Tagesende.
Dazu werden die nächtlich angelieferten Daten des Tages
beim ETL-Prozess aggregiert
und mit den Bestandes-Mengen des Vortags verrechnet:
Bezüge durch Filialen verringern den Bestand im Lager,
Anlieferungen erhöhen ihn.

Der neue DW-Stern soll also abbilden,
in welchem Lager (neue Dimension `dim_warehouse`)
es
am Ende welches Tages (bestehende Dimension `dim_time`)
wie viele Exemplare (Attribut `quantity` der neuen Fakten-Tabelle)
welches Films (bestehende Dimension `dim_movie`)
hatte.
Die angelieferten Angaben `FilialId`, `LieferantenId` und `Lieferpreis`
können ignoriert und beim ETL-Prozess verworfen werden.

[plantuml]
----
@startuml
package "schema video_dw, new stock 'star'" << Frame >> {

  together {
    note as Note_not_a_conceptual_model
      This diagram shows
      a //logical// relational DB schema,
      **not** a conceptual domain model.
    end note

    class dim_movie
  }

  note as Note_formatting
    <b>bold</b> = PK components
    <i>italic</i> = FKs
  end note

  dim_warehouse <-- fact_stock : warehouse_id
  fact_stock --> dim_movie : movie_id
  fact_stock -> dim_time : time_id

  class dim_warehouse << (T,lightgray) Table >> {
    {field} <b>warehouse_id</b> : INTEGER
    {field} name : VARCHAR(30)
  }

  class dim_movie << (T, lightgray) Table >> {
    {field} <b>movie_id</b> : INTEGER
    {field} name : VARCHAR(30)
    {field} price : DECIMAL(5,2)
    {field} subgenre : VARCHAR(20)
    {field} subgenre_id : INTEGER
    {field} genre : VARCHAR(10)
  }

  class dim_time << (T, lightgray) Table >> {
    {field} <b>time_id</b> : INTEGER
    {field} ddate : DATE
    {field} month : INTEGER
    {field} season : VARCHAR(10)
    {field} year : INTEGER
  }

  class fact_stock << (T, lightgray) Table >> {
    <b>fact_stock_id</b> : INTEGER
    <i>warehouse_id</i> : INTEGER
    <i>movie_id</i> : INTEGER
    <i>time_id</i> : INTEGER
    quantity_in_stock : INTEGER
  }
}

hide methods

@enduml
----
