// Auto-generated by RAG system on 2026-05-09
// Week 6 — do not edit the header

#import "../../template.typ": tip-box, warn-box, formula-box, cheat-box

== Woche 6: Big Data Analytics, Cloud Platforms & Google Earth Engine

=== Überblick

Diese Woche behandelt drei Themenblöcke:
+ *Cloud vs. On-Premise* — Entscheidungskriterien, Architekturmodelle (IaaS/PaaS/SaaS), Auswahlkriterien für Cloud-Plattformen
+ *Vergleich von Data Analytics Services* — Snowflake, Amazon Redshift, Databricks, Data Lakes/Lakehouses
+ *Spatial Data Analytics & Google Earth Engine (GEE)* — Rasterdaten, GEE-Architektur, praktisches Programmieren mit der GEE JavaScript API

---

== Teil 1: Cloud vs. On-Premise

=== Grundbegriffe

*On-Premise* bedeutet: Hardware steht beim Kunden, der Kunde betreibt und wartet alles selbst.

*Cloud* bedeutet: Der Anbieter hostet die Infrastruktur, der Nutzer zahlt per Abonnement oder nach Nutzung.

#tip-box[
*Woran erkenne ich die Frage?*
Aufgaben fragen nach Vor-/Nachteilen, nach Entscheidungskriterien oder nach der Klassifikation eines Services (IaaS/PaaS/SaaS).

*Schnell-Entscheidung Cloud vs. On-Premise:*
- Hohe Nutzungsschwankungen → Cloud (Elastizität)
- Geringe Nutzung, klar definiert → Cloud oft besserer ROI
- Sensible Daten, strenge Compliance → eher On-Premise
- Hohe Rechenanforderungen mit Latenz-Kritikalität → On-Premise oder Hybrid
]

#cheat-box[
*Wenn X, dann Y:*
- Wenn Kostenkontrolle wichtig + variable Last → Cloud (pay-per-use)
- Wenn Datenschutz / DSGVO / Finanz/Gesundheitswesen → On-Premise oder private Cloud
- Wenn schnelle Skalierung nötig → Cloud
- Wenn volle Kontrolle über Updates → On-Premise
- Wenn KI-Workloads mit Echtzeit-Anforderungen → Performance-Probleme möglich in Cloud
]

*Aktuelle Marktlage (2025):*
- AWS: ~30 % Marktanteil
- Microsoft Azure: ~23 %
- Google Cloud: ~13 %

*Trend:* Nicht mehr "Cloud-first", sondern *"Hybrid-first"* oder *"Workload-first"* — je nach Workload entscheiden, wo er am besten läuft (Kosten, Performance, Jurisdiktion).

#warn-box[
*Häufiger Denkfehler:* "Cloud ist immer günstiger als On-Premise."

In der Praxis können Cloud-Kosten bis zu 50 % der Umsatzkosten ausmachen. Cloud ist *bei geringer oder variabler Nutzung* oft günstiger — bei konstant hoher Last kann On-Premise besser sein. KI-Workloads treiben Cloud-Kosten zusätzlich in die Höhe.
]

=== XaaS — Infrastructure, Platform, Software as a Service

Drei Schichten der Cloud-Abstraktion:

*IaaS (Infrastructure as a Service):*
- Anbieter stellt Rechenleistung, Speicher, Netzwerk bereit
- Kunde verwaltet OS, Middleware, Anwendungen
- Beispiel: Amazon EC2, Google Compute Engine

*PaaS (Platform as a Service):*
- Anbieter stellt Laufzeitumgebung und Entwicklungsplattform bereit
- Kunde entwickelt und deployt Anwendungen
- Beispiel: Google App Engine, *Google Earth Engine*

*SaaS (Software as a Service):*
- Vollständige Anwendung wird geliefert
- Kunde nutzt nur die Software
- Beispiel: Snowflake (als SaaS nutzbar), Microsoft 365

#tip-box[
*Klassifikation eines Services:*
- Muss der Nutzer noch OS/Middleware konfigurieren? → IaaS
- Stellt der Dienst eine Entwicklungsplattform mit APIs bereit, aber keine fertige App? → PaaS
- Nutzt der Nutzer eine fertige Anwendung ohne eigene Infrastruktur? → SaaS
- GEE ist *Function- und Platform-as-a-Service (PaaS)* mit bereits aufbereiteten Daten (Data Warehouse)
]

=== Anforderungen an Cloud-Plattformen

Die sechs wichtigsten Auswahlkriterien (prüfungsrelevant!):

+ *Einfache Einrichtung und Betrieb* — dedizierte Systeme statt monolithischer Allzwecklösungen
+ *Elastizität* — autonomes Provisionieren/Deprovisionieren von Ressourcen je nach Last
+ *Unabhängige Skalierung* von Rechenleistung und Speicher (Shared Nothing)
+ *Gute SQL-Unterstützung*
+ *Verwaltung vielfältiger Daten* — strukturiert, semistrukturiert (JSON/XML), spaltenbasiert
+ *Backup-Möglichkeiten*

*Definition Elastizität:*
"Das Ausmass, in dem sich ein System an Änderungen der Arbeitslast anpassen kann, indem es Ressourcen auf autonome Weise bereitstellt und entfernt, so dass zu jedem Zeitpunkt die verfügbaren Ressourcen so gut wie möglich dem aktuellen Bedarf entsprechen."

=== Scale Up vs. Scale Out

*Scale Up (vertikal):* Leistungsfähigere Hardware einsetzen — mehr RAM, schnellere CPU in einem Knoten.

*Scale Out (horizontal):* Mehr Knoten hinzufügen — *Shared Nothing*-Architektur: Jeder Knoten hat eigenen Speicher, keine geteilte Ressource als Flaschenhals.

#cheat-box[
- Scale Up → begrenzt durch Hardwaremaximum, einfacher zu verwalten
- Scale Out → nahezu unbegrenzt skalierbar, Shared Nothing, besser für Big Data
- Cloud-native Systeme (Snowflake, Redshift) → bevorzugen Scale Out
]

=== Spaltenbasierte Datenspeicherung

*Idee:* Daten werden nicht zeilenweise sondern spaltenweise auf Disk gespeichert.

*Vorteil für Analytics:* Analytische Abfragen lesen typischerweise nur wenige Spalten über viele Zeilen. Bei spaltenbasiertem Speicher müssen nur die relevanten Spalten gelesen werden → weniger I/O.

*Warum viele Spalten in Data Warehouses?* Data Warehouses speichern stark denormalisierte Fakten- und Dimensionstabellen mit vielen Attributen (z.B. alle Eigenschaften eines Verkaufs in einer Zeile).

=== Data Warehouse vs. Data Lake vs. Data Lakehouse

*Data Warehouse:* Strukturierte, aufbereitete Daten; Schema-on-Write; optimiert für SQL-Abfragen; z.B. Snowflake, Redshift.

*Data Lake:* Rohdaten aller Typen (strukturiert, semistrukturiert, unstrukturiert); Schema-on-Read; kostengünstige Speicherung; z.B. S3 + Parquet.

*Data Lakehouse (Trend):* Kombination: Offenes Tabellenformat (Apache Iceberg) über einem Data Lake, mit Data-Warehouse-Abfragefähigkeiten.

#tip-box[
*Schlüsselbegriffe Open-Source Data Lake Formate:*
- *Apache Iceberg* (Snowflake-bevorzugt): ACID-Transaktionen, Schema-Evolution, Time Travel; meiste GitHub-Stars; "hat gewonnen"
- *Delta Lake* (Databricks): Am schnellsten; fast nur Databricks-Contributors
- *Apache Hudi* (ex-Uber): Meiste Contributors insgesamt; gut für Streaming
]

---

== Teil 2: Vergleich Cloud Analytics Services

=== Amazon Redshift

- Verfügbar seit 2013, Teil von AWS
- Vollständig verwalteter Service (Backup, Upgrades automatisch)
- *Spaltenorientierte Datenbank*
- Workload Manager (WLM): Priorisierung von Abfragen, verhindert Blockierung durch lange Queries
- Neu: "on-the-fly"-Elastizität (Serverless)
- Schwäche: Begrenzte Unterstützung semistrukturierter JSON-Daten

=== Snowflake

- 2012 gegründet, cloud-native (nicht von On-Premise abgeleitet)
- *Kernmerkmal: Trennung von Rechenleistung und Speicher* — kann unabhängig skaliert und bezahlt werden
- Spaltenorientierte SQL-Datenbank darunter (Apache Iceberg)
- SaaS: einfache Einrichtung ohne eigene Infrastruktur
- *Virtuelle Warehouses:* Jede Benutzergruppe/jeder Prozess läuft auf isolierter Hardware
- *Zero Copy Clone:* Schnelle Kopie ganzer Datenbanken ohne Datenduplizierung
- Data Warehouse + Data Lake = "Data Lakehouse"

#cheat-box[
*Snowflake-Architektur — drei Schichten:*
- *Storage Layer:* Zentraler, skalierbarer Objektspeicher (S3/Azure Blob/GCS)
- *Compute Layer:* Virtuelle Warehouses — mehrere unabhängig skalierbar
- *Cloud Services Layer:* Metadaten, Query Optimizer, Transaktions-Management

Dieses Modell ist weder rein "Shared Disk" noch rein "Shared Nothing" — es ist ein Hybrid:
Shared Disk auf Storage-Ebene + Shared Nothing auf Compute-Ebene.
]

=== DuckDB (Erwähnung)

- Verarbeitet out-of-the-box bis ~100 GB
- Via Parquet-Dateien und S3-Integration auch Terabyte-grosse Datensätze
- Als Ergänzung zu PostgreSQL: `pg_duckdb` bzw. `pg_lake`
- Relevant für lokale Analytics ohne Cloud

---

== Teil 3: Spatial Data Analytics & Rasterdaten

=== GIS-Grundbegriffe: Zwei Datenmodelle

*Vektor-Datenmodell:*
- Repräsentiert Geometrien als Punkt, Linie, Polygon
- Beispielformat: GeoJSON
- Eignet sich für diskrete Objekte (Strassen, Gebäude, Grenzen)

*Raster-Datenmodell:*
- Repräsentiert Information als Gitter (Grid) aus Pixeln
- Jeder Pixel hat einen oder mehrere Zahlenwerte ("Bänder")
- Beispielformate: GeoTIFF, HDF5, 2D-Matrix
- Eignet sich für kontinuierliche Phänomene (Temperatur, Höhe, Niederschlag)

*Layer (Ebene):* Sachdaten mit einer Geometrie — ein thematischer Datensatz.

*Band:* Ein Wertekanal eines Rasterbildes. Ein Satellitenbild hat typischerweise mehrere Bänder (rot, grün, blau, infrarot, ...).

=== Rasterdaten — Begriffe

- *Satellitenbild:* Bild aufgenommen von einem Satelliten
- *Luftbild:* Bild aufgenommen aus der Luft (Flugzeug, Drohne) nahezu senkrecht auf die Erde
- *Orthophoto:* Verzerrungsfreie, massstabsgetreue Abbildung der Erdoberfläche — abgeleitet aus Luft-/Satellitenbildern durch photogrammetrische Verfahren
- *Auflösung (Resolution):* Grösse eines Pixels in der Realität — z.B. 100 m bedeutet, ein Pixel repräsentiert 100 m × 100 m

#tip-box[
*Warum Rasterdaten besonders anspruchsvoll?*
- Massive Datenmenge (Petabytes für globale, multi-temporale Bilder)
- Teuer in der Beschaffung grosser Gebiete
- Erfordern spezialisierte GIS-/Fernerkundungssoftware
- Georeferenzierung nötig (Pixel haben reale Weltkoordinaten)
]

=== Bildsensoren und Spektralbänder

Satellitensensoren erfassen mehr als das menschliche Auge sieht:
- *Sichtbares Licht (Visible):* Rot, Grün, Blau
- *Nahes Infrarot (NIR):* Vegetation stark reflektierend
- *Thermisches Infrarot:* Wärmestrahlung → Oberflächentemperatur
- *UV, Radar (SAR):* Weitere Anwendungen

*Anwendungsbeispiel Urbane Hitzeinseln:*
Gebiete (v.a. städtisch) die wärmer sind als ihre Umgebung — erkennbar durch thermische Infrarotbänder in Satellitenbildern. Verwendung für Klimakarten, Stadtplanung, Gesundheitsstrategien.

=== Rasterdatenanalyse vs. klassische Bildverarbeitung

*Gemeinsamkeiten:* Beide arbeiten mit digitalen Bildern, nutzen Algorithmen zur Bildbearbeitung, haben ähnliche Vorverarbeitungsschritte.

*Unterschiede:*

#cheat-box[
| Merkmal | Rasterdatenanalyse | Klassische Bildverarbeitung |
|---|---|---|
| Räumlicher Bezug | Ja (georeferenziert) | Nein/optional |
| Datenmenge | Gross (Bildreihen, Mosaike) | Klein (Einzelbilder) |
| Ziel | Abbildung der Realität | Objekterkennung, Verarbeitung |
| Software | GIS-Software + Bildverarbeitung | CV-Bibliotheken |
]

---

== Teil 4: Google Earth Engine (GEE)

=== Was ist GEE?

Google Earth Engine ist eine *Cloud-Computing-Plattform* für das Auffinden, Zugreifen und Analysieren von Satellitendaten und raumbezogenen Beobachtungen.

*Kernfähigkeiten:*
- Zugriff auf *90 Petabytes* Satellitendaten über *45 Jahre* (NASA, ESA, etc.)
- Massive Rechenleistung direkt bei den Daten (keine Daten herunterladen nötig)
- Statistik- und ML-Funktionen in *JavaScript* und *Python*
- Geo-Visualisierung (Google Maps Mashups)
- Teilen als "GEE Apps"

*Klassifikation:* GEE ist *Function- und Platform-as-a-Service (PaaS)* mit bereits aufbereiteten Daten in der Cloud.

*Wichtig:* GEE ist nicht dasselbe wie Google Earth! Kommerzielle Nutzung kostet (Vertrag mit Google nötig). Für Lehre/Forschung kostenlos.

=== GEE Datenkatalog — Wichtige Datensätze

#cheat-box[
*Datensatz — Auflösung — Zeitraum:*
- Landoberflächentemperatur: ASTER AG100 → 100 m, 2000–2008
- Niederschlag: GSMaP → ~11 km, alle 3h seit 2014
- Urbane Hitzeinseln: YCEO Surface Urban Heat Islands → 300 m, 2003–2018
- Höhenmodell: SRTM v4 → 90 m, 2000
- Bodenbedeckung: Copernicus CORINE Land Cover → 100 m, 2018
- Siedlungsflächen: World Settlement Footprint → 10 m, 2015
- Bevölkerungsdichte: GPWv411 → 1 km, 2000/2005/2010/2015/2020
]

=== GEE JavaScript API — Kernkonzepte

==== Datentypen in GEE

- `ee.Image` — Ein einzelnes Rasterbild (ein oder mehrere Bänder)
- `ee.ImageCollection` — Eine Sammlung von Bildern (z.B. Zeitreihe)
- `ee.FeatureCollection` — Eine Sammlung von Vektorobjekten (Polygone, Punkte)
- `ee.Filter` — Filter für Kollektionen

==== Grundprinzip: Lazy Evaluation

GEE führt Berechnungen nicht sofort lokal aus — Operationen werden als Beschreibung an Googles Server geschickt, die dann die eigentliche Berechnung durchführen. Deshalb: Grosse Datenmengen können verarbeitet werden ohne lokalen Download.

=== GEE Code-Rezepte für die Übungsaufgaben

#formula-box[
*Rezept 1: Vektordaten laden und filtern*

+ `ee.FeatureCollection('DATASET_ID')` — Datensatz laden
+ `.filter(ee.Filter.eq('Attribut', 'Wert'))` — auf ein Land/Region filtern
+ `Map.addLayer(feature)` — zur Karte hinzufügen
+ `Map.centerObject(feature, zoom)` — Karte auf Objekt zentrieren

*Beispiel — Land laden:*
```javascript
var countries = ee.FeatureCollection('USDOS/LSIB_SIMPLE/2017');
var switzerland = countries.filter(ee.Filter.eq('country_na', 'Switzerland'));
Map.addLayer(switzerland);
Map.centerObject(switzerland, 7);
```
]

#formula-box[
*Rezept 2: Rasterdaten laden, Band auswählen, visualisieren*

+ `ee.ImageCollection('DATASET_ID')` — Bildserie laden
+ `.select('BANDNAME')` — gewünschtes Band auswählen
+ Zeitfilter anwenden (Jahr, Monat)
+ `.mean()` — Durchschnittsbild über Zeitraum
+ `.clip(region)` — auf Region zuschneiden
+ `Map.addLayer(image, vizParams, 'Name')` — visualisieren

*Visualisierungsparameter:*
```javascript
var vizParams = {
  min: minWert,
  max: maxWert,
  palette: ['blau', ..., 'rot'],
  opacity: 0.7
};
```

*Beispiel — NO2-Konzentration:*
```javascript
var no2ic = ee.ImageCollection('COPERNICUS/S5P/NRTI/L3_NO2')
  .select('NO2_column_number_density');
var no2_2020 = no2ic
  .filter(ee.Filter.calendarRange(2020, 2020, 'year'))
  .filter(ee.Filter.calendarRange(2, 5, 'month'))
  .mean()
  .multiply(1e6)
  .clip(italy);
Map.addLayer(no2_2020, {min: 0, max: 200,
  palette: ['black', 'purple', 'green', 'red']}, 'NO2 2020');
```
]

#formula-box[
*Rezept 3: Kartenausschnitt und Zoom setzen*

```javascript
Map.setCenter(laengengrad, breitengrad, zoom);
```
- Koordinaten in *WGS84* (Längengrad zuerst, dann Breitengrad — Achtung: oft umgekehrt!)
- Zoomlevel: 1 = global, 13 = Stadtebene, 18+ = Gebäudeebene

*Beispiel Zürich:*
```javascript
Map.setCenter(8.5417, 47.3769, 13);
```
]

#formula-box[
*Rezept 4: Einheiten skalieren*

Daten liegen oft in ungewöhnlichen Einheiten vor (z.B. hundertstel Kelvin).
Skalieren vor der Analyse:

```javascript
var temperature = dataset.select('temperature').divide(100);
// Ergebnis: Kelvin mit Dezimalstellen statt hundertstel Kelvin
```

*Verfügbare Methoden:*
- `.divide(zahl)` — durch Zahl teilen
- `.multiply(zahl)` — mit Zahl multiplizieren
- `.add(zahl)` — addieren
- `.subtract(zahl)` — subtrahieren

*Kelvin zu Celsius:* `.subtract(273.15)`
]

#formula-box[
*Rezept 5: Umgebungstemperatur berechnen (reduceNeighborhood)*

Idee: Hitzeinseln sind Orte, die *wärmer als ihre Umgebung* sind.
Schritt 1: Lokalen Durchschnitt (Umgebungstemperatur) berechnen.

```javascript
var kernel = ee.Kernel.square({
  radius: 2000,
  units: 'meters'
});
var tempNeighborhood = temperature.reduceNeighborhood({
  reducer: ee.Reducer.mean(),
  kernel: kernel
});
```

- `radius`: Radius des Suchfensters in Metern (z.B. 2 km = 2000 m)
- `ee.Reducer.mean()`: Mittelwert im Fenster
- Ergebnis: "verschwommenes" Bild — jeder Pixel enthält Umgebungsdurchschnitt
]

#formula-box[
*Rezept 6: Hitze-/Kälteinsel-Differenz berechnen*

Hitze-/Kälteinsel = lokale Temperatur minus Umgebungstemperatur:

$"Differenz" = "Temperatur"_"lokal" - "Temperatur"_"Umgebung"$

```javascript
var heatIsland = temperature.subtract(tempNeighborhood);
```

Positive Werte = wärmer als Umgebung (Hitzeinsel)
Negative Werte = kälter als Umgebung (Kälteinsel)

Visualisierung: Wertebereich symmetrisch um 0 wählen, z.B. min: -5, max: 5
]

#formula-box[
*Rezept 7 (Zusatz): Einschränkung auf besiedeltes Gebiet*

Idee: Besiedeltes Gebiet emittiert nachts mehr Licht.
Nacht-Licht-Datensatz als Maske verwenden:

+ Nacht-Licht-Datensatz laden (z.B. NOAA/VIIRS Nighttime Lights)
+ Schwellenwert anwenden: Pixel unter Schwellenwert = unbewohnt → auf 0 setzen
+ Mit Hitzeinsel-Daten multiplizieren (Pixel in unbewohnten Gebieten werden 0)

```javascript
// Nachtlicht laden
var nightlights = ee.ImageCollection('NOAA/VIIRS/DNB/MONTHLY_V1/VCMSLCFG')
  .select('avg_rad')
  .mean();

// Maske: Pixel mit genug Licht = 1, sonst = 0
var settledMask = nightlights.gt(schwellenwert);

// Ergebnis nur für besiedeltes Gebiet
var heatIslandUrban = heatIsland.updateMask(settledMask);
Map.addLayer(heatIslandUrban, vizParams, 'Urban Heat Islands');
```
]

=== Häufige Fehlerquellen in GEE

#warn-box[
*Häufige Fehler und warum sie passieren:*

1. *Koordinaten-Reihenfolge falsch:* `Map.setCenter` erwartet `(Längengrad, Breitengrad)` — also erst Ost-West, dann Nord-Süd. Wikipedia zeigt oft Breitengrad zuerst. Immer kontrollieren!

2. *Falscher Wertebereich in vizParams:* Wenn `min`/`max` nicht zum tatsächlichen Datenbereich passen, erscheint das Bild einfarbig (alles zu hoch → alles rot; alles zu niedrig → alles blau). Lösung: Im Inspector-Tab auf Pixel klicken und Rohwert prüfen.

3. *Einheiten ignoriert:* Viele Datensätze verwenden Skalierungsfaktoren (z.B. hundertstel Kelvin). Ohne `.divide(100)` sind alle Berechnungen falsch. Immer die Dataset-Dokumentation lesen!

4. *ImageCollection statt Image:* Viele Operationen funktionieren nur auf `ee.Image`, nicht auf `ee.ImageCollection`. Erst `.mean()`, `.first()` oder `.mosaic()` aufrufen um ein einzelnes Bild zu erhalten.

5. *Kein `.clip()`* → globaler Layer, der sehr langsam ist. Immer auf Region zuschneiden.

6. *Opacity vergessen:* Nach jedem Code-Run ist der Layer wieder 100% opak. Opacity im Code mitgeben: `Map.addLayer(img, params, 'Name', true, 0.7)` — letzter Parameter ist Opacity.
]

=== GEE: Stärken und Grenzen

*Stärken:*
- Einzigartige Datenmenge (90 PB, 45 Jahre, täglich aktualisiert)
- Rechenleistung direkt bei den Daten — kein Download nötig
- Einfache JavaScript/Python-API
- Kostenlos für Forschung und Lehre

*Grenzen:*
- Upload eigener Daten mengenmässig beschränkt
- Privacy-Bedenken (Google-Konto zwingend, Tracking)
- Keine Garantie auf dauerhafte Kostenfreiheit
- Eigentumsrechte: Code und eigene Daten bleiben beim Nutzer (anders als bei Google Maps!)

---

== Zusammenfassung: Entscheidungsbaum

#cheat-box[
*Welches Cloud-Modell passt?*

```
Brauche ich fertige Software?
  → Ja → SaaS (z.B. Snowflake SaaS, Office 365)
  → Nein: Entwickle ich eigene Apps?
      → Ja, brauche Plattform/APIs → PaaS (z.B. GEE, App Engine)
      → Nein, brauche nur Infrastruktur → IaaS (z.B. EC2, GCE)
```

*Welche Analytics-Plattform?*

```
Sehr variable Last + einfache Einrichtung?
  → Snowflake (beste Elastizität, SaaS)
Bereits in AWS-Ökosystem?
  → Amazon Redshift
Grosse Datenmengen + Spark/ML-Workflows?
  → Azure Databricks
Satellitendaten / Geo-Analyse?
  → Google Earth Engine
Lokale Analyse bis 100 GB?
  → DuckDB
```

*GEE-Analyse-Pipeline (für Hitzeinseln):*
```
1. Datensatz suchen (Data Catalog)
2. ImageCollection laden → Band auswählen
3. Zeitfilter → .mean() → .clip(region)
4. Skalieren (.divide() / .multiply())
5. Visualisieren (min, max, palette, opacity)
6. Umgebungstemperatur: .reduceNeighborhood(mean, kernel)
7. Differenz: temperature.subtract(neighborhood)
8. (Optional) Maske mit Nachtlicht für urbane Gebiete
```
]