"""Chunks → Claude API → Typst chapter file → make build."""

import os
import subprocess
from datetime import date

import anthropic
from dotenv import load_dotenv

from rag.config import DOCS_WEEKS, SUMMARY_TYP, ROOT, CLAUDE_MODEL
from rag.ingest import get_week_chunks

load_dotenv()

_SYSTEM_PROMPT = """\
Du bist ein Lernhilfe-Assistent. Du schreibst strukturierte Zusammenfassungen \
im Typst-Format für ein Prüfungs-Lernheft.

Regeln:
- Nutze diese Callout-Boxen aus dem Template:
    #formula-box[...] für Formeln und Referenz-Tabellen (blau)
    #tip-box[...]      für Key Insights und Eselsbrücken (grün)
    #warn-box[...]     für Prüfungsfallen (orange)
    #cheat-box[...]    für komprimierte Cheat-Sheet Blöcke (lila)
- Mathe in Typst: $bold(A)$, $A_(i,j)$, $sum_k$, $mat(1,2;3,4)$
- Struktur: === Abschnitt, *Fetttext*, _Kursiv_
- Kein #import, kein #show, keine Header-Zeile — das kommt von der index.typ
- Beginne direkt mit == Chapter X: [Titel]
- Sei präzise und lehrreich. Prüfungsrelevante Punkte hervorheben.
"""

_USER_TEMPLATE = """\
Hier sind die extrahierten Inhalte aus den Vorlesungs-PDFs für Woche {week_nr}:

---
{content}
---

Schreibe eine vollständige, strukturierte Typst-Zusammenfassung für dieses Material. \
Chapter-Nummer: {week_nr}. Nutze formula-box für alle Formeln, tip-box für Kerneinsichten, \
warn-box für häufige Fehler/Prüfungsfallen.
"""


def _build_content(chunks: list[dict], max_chars: int = 80_000) -> str:
    parts, total = [], 0
    for c in chunks:
        text = c["text"]
        if total + len(text) > max_chars:
            break
        parts.append(text)
        total += len(text)
    return "\n\n---\n\n".join(parts)


def _chapter_path(week_nr: int):
    return DOCS_WEEKS / f"week_{week_nr:02d}" / f"chapter_{week_nr:02d}.typ"


def _index_path(week_nr: int):
    return DOCS_WEEKS / f"week_{week_nr:02d}" / "index.typ"


def _ensure_summary_includes(week_nr: int) -> None:
    """Uncomment or add the #include for this week in summary.typ."""
    text = SUMMARY_TYP.read_text(encoding="utf-8")
    tag  = f'#include "weeks/week_{week_nr:02d}/index.typ"'
    commented = f'// {tag}'

    if tag in text:
        return  # already active
    if commented in text:
        text = text.replace(commented, tag)
    else:
        # append before end
        text = text.rstrip() + f'\n{tag}\n'

    SUMMARY_TYP.write_text(text, encoding="utf-8")


def generate_summary(week_nr: int, progress=None) -> str:
    """Generate a Typst chapter file from indexed chunks. Returns the file path."""
    if progress:
        progress("Lade Chunks aus Datenbank...")

    chunks = get_week_chunks(week_nr)
    if not chunks:
        raise RuntimeError(f"Keine Chunks für Woche {week_nr} — erst indexieren!")

    content = _build_content(chunks)

    if progress:
        progress("Generiere Zusammenfassung mit Claude...")

    client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
    message = client.messages.create(
        model=CLAUDE_MODEL,
        max_tokens=8192,
        system=_SYSTEM_PROMPT,
        messages=[{
            "role": "user",
            "content": _USER_TEMPLATE.format(
                week_nr=week_nr,
                content=content,
            ),
        }],
    )
    typst_content = message.content[0].text

    chapter_path = _chapter_path(week_nr)
    chapter_path.parent.mkdir(parents=True, exist_ok=True)

    header = (
        f"// Auto-generated by RAG system on {date.today()}\n"
        f"// Week {week_nr} — do not edit the header\n\n"
        f'#import "../../template.typ": tip-box, warn-box, formula-box, cheat-box\n\n'
    )
    chapter_path.write_text(header + typst_content, encoding="utf-8")

    _ensure_summary_includes(week_nr)

    if progress:
        progress("Baue PDF...")
    _build_pdf()

    return str(chapter_path)


def _build_pdf() -> None:
    result = subprocess.run(
        ["make", "build"],
        cwd=str(ROOT),
        capture_output=True,
        text=True,
        shell=True,
    )
    if result.returncode != 0:
        raise RuntimeError(f"make build fehlgeschlagen:\n{result.stderr}")
