// Auto-generated by RAG system on 2026-05-09
// Week 2 — do not edit the header

#import "../../template.typ": tip-box, warn-box, formula-box, cheat-box

== Woche 2: OLAP, Data Warehouses & SQL-Aggregationen

#let formula-box(content) = block(
  fill: rgb("#e8f4f8"),
  stroke: rgb("#2196F3"),
  radius: 4pt,
  inset: 10pt,
  width: 100%,
)[#content]

#let tip-box(content) = block(
  fill: rgb("#e8f5e9"),
  stroke: rgb("#4CAF50"),
  radius: 4pt,
  inset: 10pt,
  width: 100%,
)[#content]

#let warn-box(content) = block(
  fill: rgb("#fff3e0"),
  stroke: rgb("#FF9800"),
  radius: 4pt,
  inset: 10pt,
  width: 100%,
)[#content]

#let cheat-box(content) = block(
  fill: rgb("#f3e5f5"),
  stroke: rgb("#9C27B0"),
  radius: 4pt,
  inset: 10pt,
  width: 100%,
)[#content]

---

=== 1. OLTP vs. OLAP — Grundunterschied

*Kernidee:* Zwei fundamental verschiedene Datenbanknutzungsarten — transaktional (viele kurze Schreiboperationen) vs. analytisch (wenige, komplexe Leseoperationen auf historischen Daten).

#cheat-box[
*Wenn Aufgabe fragt: "OLTP oder OLAP?"*

- Viele kurze Transaktionen, mission-critical, normalisiert, aktuell $arrow.r$ *OLTP*
- Komplexe Analysen, historische Daten, Redundanz erlaubt, Ad-hoc-Queries $arrow.r$ *OLAP*

| Merkmal | OLTP | OLAP |
|---|---|---|
| Anfragen | häufig, einfach | selten, komplex |
| Datenvolumen pro Anfrage | klein | gross |
| Daten | aktuell | historisch + aktuell |
| Optimierung | schneller Update | schnelle Kalkulation |
| Normalisierung | hoch (3NF) | niedrig erlaubt |
]

*Warum getrennte Systeme?* Paralleles Ausführen von OLAP-Anfragen auf OLTP-Datenbeständen beeinträchtigt die Performance der OLTP-Anwendungen. Ein DB-System kann nicht gleichzeitig für beide optimiert werden.

---

=== 2. Data Warehouse — Architektur und Begriffe

*Kernidee:* Ein Data Warehouse (DW) ist ein separates, für Analysen optimiertes Datenbanksystem, das Daten aus verschiedenen operativen Quellen konsolidiert, bereinigt und historisiert speichert.

==== 2.1 Gesamtarchitektur (OLAP-Systemüberblick)

```
OLTP-Systeme  →  ETL  →  Data Warehouse  →  Data Marts / OLAP Cubes  →  Reporting
(operative        (Extract,   (relational,      (vorberechnete           (Ad-hoc SQL,
 Quellen)          Transform,  Star/Snowflake)   Aggregate,               MDX, BI-Tools)
                   Load)                          materialisierte Views)
```

*ETL (Extract-Transform-Load):*
- *Extract:* Daten aus heterogenen Quellen extrahieren
- *Transform:* Bereinigen, vereinheitlichen, anreichern
- *Load:* Ins DW laden und aktualisieren

*Business Intelligence (BI):* Übergeordneter Begriff — Skills, Tools und Anwendungen für besseres Geschäftsverständnis (z.B. Apache Superset, Tableau).

#tip-box[
*Woran erkenne ich eine DW-Entwurfsaufgabe?*
- Aufgabe nennt mehrere operative Quellsysteme
- Gefordert sind Auswertungen nach verschiedenen Dimensionen (Zeit, Produkt, Region...)
- Vergleiche mit Vorperioden, Budgetvergleiche
- Grosse historische Datenmengen
]

---

=== 3. Star-Schema und Snowflake-Schema

*Kernidee:* Das Star-Schema ist das zentrale Datenmodell im Data Warehouse — eine zentrale Faktentabelle mit numerischen Messwerten, umgeben von denormalisierten Dimensionstabellen.

==== 3.1 Faktentabelle

- Enthält *numerische, aggregierbare Messwerte* (Measures/Fakten): z.B. Umsatz, Anzahl, Preis
- Enthält *Fremdschlüssel* auf alle Dimensionstabellen
- Typischerweise sehr gross (Millionen von Zeilen)
- So granular wie möglich aufbauen!

==== 3.2 Dimensionstabellen

- Beschreiben die Fakten (Kontext): Zeit, Produkt, Kunde, Region, Kanal
- Oft *denormalisiert* (Star) oder normalisiert (Snowflake)
- Haben in der Regel einen *Surrogatschlüssel* (künstlicher PK, unabhängig vom Businesskey)
- Klein bis mittelgross (~1000 Zeilen)

#formula-box[
*Rezept: Star-Schema entwerfen*

1. *Analysiere geforderte Auswertungen:* Welche Kennzahlen (= Fakten) sollen berechnet werden? Welche Gruppierungskriterien (= Dimensionen) kommen vor?
2. *Bestimme Faktentabelle(n):* Eine pro Geschäftsprozess (z.B. Verkauf, Lagerbestand, Budget)
3. *Bestimme Granularität:* Was entspricht genau einer Zeile? (z.B. ein Verkaufsposten = 1 Zeile)
4. *Bestimme Dimensionen:* Für jede Gruppierungsdimension eine Tabelle (Zeit, Produkt, Kunde, ...)
5. *Bestimme Fakten-Attribute:* Numerische Werte in der Faktentabelle (Anzahl, Preis, Betrag)
6. *Füge Dimensionsattribute ein:* Hierarchien flach in Dimensionstabelle (Star) oder normalisiert (Snowflake)
7. *Zeichne das Schema:* Faktentabelle zentral, Dimensionen als Satelliten

*Beispiel (Video-Shop):*
- Auswertung: Verkaufszahlen nach Film, Genre, Kunde, Datum, Monat, Jahr
- Faktentabelle `fact_sales`: `sale_id`, `sale_detail_id`, `movie_id` (FK), `cust_id` (FK), `time_id` (FK), `quantity`, `sales_amount`
- Dimensionen: `dim_movie` (movie_id, name, price, subgenre, genre), `dim_customer` (cust_id, name, city, gender, decade, ...), `dim_time` (time_id, date, month, season, year)
]

#tip-box[
*Erkennungsmerkmale für Star vs. Snowflake:*
- Dimensionsattribute mit Hierarchien *flach in einer Tabelle* (z.B. Ort, Region, Land alle in `dim_customer`) $arrow.r$ *Star-Schema*
- Hierarchieebenen in *separaten Tabellen* mit FK-Verknüpfungen (z.B. `dim_ort` $arrow.r$ `dim_region` $arrow.r$ `dim_land`) $arrow.r$ *Snowflake-Schema*
- Star: einfachere Abfragen (1-stufige Joins), mehr Redundanz
- Snowflake: weniger Redundanz, komplexere Joins
]

==== 3.3 Klassifizierung von Faktentabellen

#cheat-box[
*Wenn Aufgabe fragt: "Welcher Faktentabellentyp?"*

- Jede Zeile = ein Ereignis zu einem Zeitpunkt (z.B. Verkauf) $arrow.r$ *Transaction Fact Table*
- Jede Zeile = kumulativer Stand zu regelmässigen Intervallen (z.B. Lagerbestand jeden Abend) $arrow.r$ *Periodic Snapshot Fact Table*
- Jede Zeile = Geschäftstransaktion mit mehreren Zeitpunkten (z.B. Bestellung: Eingang → Lieferung → Rechnung) $arrow.r$ *Accumulating Snapshot Fact Table*
]

*Beispiele:*
- `fact_sales` (Videoverkäufe): Transaction Fact Table — jede Zeile ist ein Verkaufsposten
- `fact_stock` (Lagerbestand täglich): Periodic Snapshot — Bestand wird täglich um 23h erfasst
- Bestellungsabwicklung mit mehreren Schritten: Accumulating Snapshot

==== 3.4 Spezielle Dimensionen

*Degenerate Dimension:* Kein eigene Tabelle — die Dimension lebt als Attribut in der Faktentabelle.
- Beispiel: `BestellItemNr` in `FaktBestellung` (identifiziert den Order-Header, braucht keine eigene Tabelle)

*Role-Playing Dimension:* Eine Dimension wird von der Faktentabelle *mehrfach in verschiedenen Rollen* referenziert.
- Beispiel: `DimZeit` wird zweimal referenziert — einmal als `BestellZeit_ID`, einmal als `LieferZeit_ID`

*Junk Dimension:* Sammelt korrelierte Flags und Indikatoren, die sonst die Faktentabelle aufblähen würden.

*Conformed Dimension:* Eine Dimension (z.B. Zeit, Geographie) die von *mehreren Faktentabellen* gemeinsam genutzt wird und überall dieselbe Bedeutung hat. Ermöglicht Abfragen über mehrere Faktentabellen.
- Beispiel: `DimZeit` und `DimWeinart` sind in beiden Sternen (Bestellstern und Budgetstern) vorhanden.

#warn-box[
*Häufiger Fehler: Surrogatschlüssel vergessen*

Dimensionstabellen brauchen immer einen künstlichen Surrogatschlüssel (z.B. `Zeit_ID`, `Produkt_ID`) als PK, NICHT den natürlichen Businesskey. Warum? Bei SCD Typ 2 können mehrere Zeilen für dieselbe Entität existieren (verschiedene Historienversionen) — der Businesskey wäre dann nicht mehr eindeutig.
]

---

=== 4. Slowly Changing Dimensions (SCD)

*Kernidee:* Dimensionsattribute können sich im Laufe der Zeit ändern (z.B. Kunde zieht um, Preis ändert sich) — SCD definiert wie mit dieser Änderung umgegangen wird.

==== SCD-Typen im Überblick

#cheat-box[
*Wenn Aufgabe fragt: "Wie Änderungen in Dimension behandeln?"*

- Alte Werte nicht relevant, einfach überschreiben $arrow.r$ *SCD Typ 1* (Overwrite)
- Historienerhaltung wichtig, mehrere Versionen einer Entität $arrow.r$ *SCD Typ 2* (neue Zeile)
- Nur aktueller + ein vorheriger Wert nötig $arrow.r$ *SCD Typ 3* (zusätzliche Spalte)
]

==== SCD Typ 2 (der wichtigste)

*Vorgehen:*
1. Neue Zeile für den Datensatz einfügen mit neuen Attributwerten
2. Alte Zeile bleibt erhalten (historische Version)
3. Gültigkeitsbereich speichern: Attribute `valid_from`, `valid_to` (oder `start_date`, `end_date`)
4. Surrogat-PK wird erweitert (Business-Key allein nicht mehr eindeutig)
5. Optional: Status-Attribut `'Active'` / `'Inactive'`

```sql
-- Beispiel SCD Typ 2: Kunde wechselt Stadt per 1.2.2013
-- Schritt 1: Alte Zeile deaktivieren
UPDATE dim_customer
SET valid_to = '2013-01-31', status = 'Inactive'
WHERE cust_id_bk = 42 AND status = 'Active';

-- Schritt 2: Neue Zeile einfügen
INSERT INTO dim_customer (cust_id_bk, name, city, valid_from, valid_to, status)
VALUES (42, 'Marxer, Markus', 'Zuerich', '2013-02-01', '9999-12-31', 'Active');
```

*Auswertung mit SCD Typ 2:*
- *Über Business-Key* (ignoriert Historisierung): `GROUP BY cust_id_bk` — gibt Gesamtumsatz aller Perioden
- *Über Surrogatschlüssel* (historisierend): `JOIN` mit dem historisch korrekten Dim-Eintrag via Business-Key UND `valid_from`/`valid_to` — gibt Umsatz nur für bestimmte Wohnadresse

#warn-box[
*Häufiger Fehler: Beim ETL-Prozess falschen Dim-Eintrag nehmen*

Beim Laden der Faktentabelle muss das *zeitlich korrekte Tupel* der Dimensionstabelle gefunden werden:
`WHERE dim.cust_id_bk = oltp.cust_id AND oltp.sale_date BETWEEN dim.valid_from AND dim.valid_to`

Wenn man nur nach Business-Key joined, nimmt man eventuell den falschen (neueren) Eintrag.
]

==== Zeitdimension

Die Zeitdimension wird typischerweise *vorab vollständig befüllt* (alle Tage eines Betrachtungszeitraums), nicht nur aus Transaktionen abgeleitet. Sie enthält alle relevanten Zeitattribute als eigene Spalten:

```
ZeitId | Datum      | Jahr | Monat | Tag | MonatsName | Quartal    | Halbjahr
1      | 2004-05-01 | 2004 |   5   |  1  | May        | Q 2 2004   | H 1 2004
```

*Warum?* Damit Abfragen wie "alle Verkäufe im Q2" einfach mit `WHERE quartal = 'Q 2 2004'` formuliert werden können, ohne Datumsfunktionen.

*Wichtig:* KW-Hierarchie und Monats-Hierarchie können sich widersprechen (eine KW kann in zwei Monate fallen) $arrow.r$ mehrere Hierarchien in der Zeitdimension nötig.

---

=== 5. SQL-Aggregationen für OLAP

==== 5.1 GROUP BY (Basis)

*Kernidee:* Teilt die Ergebnismenge in Gruppen auf und berechnet pro Gruppe einen aggregierten Wert.

```sql
SELECT col1, col2, AGG_FUNC(measure)
FROM tabelle
GROUP BY col1, col2
ORDER BY col1, col2;
```

Verfügbare Aggregatfunktionen: `SUM()`, `COUNT()`, `MIN()`, `MAX()`, `AVG()`

==== 5.2 GROUP BY ROLLUP

*Kernidee:* Berechnet hierarchische Zwischensummen von rechts nach links plus eine Gesamtsumme — ersetzt mehrere UNION ALL-Queries.

*Formel:* Bei `ROLLUP(A, B, C)` entstehen Gruppierungen: $(A,B,C)$, $(A,B)$, $(A)$, $()$

#formula-box[
*Rezept: ROLLUP anwenden*

1. Bestimme die Hierarchie der Attribute (von spezifisch zu allgemein)
2. Reihenfolge im ROLLUP: spezifischstes Attribut zuerst, dann aufsteigend genereller
3. `GROUP BY ROLLUP(A, B)` erzeugt:
   - Zeilen mit $(A, B)$ = normale Gruppierung
   - Zeilen mit $(A, "NULL")$ = Subtotal pro $A$ (über alle $B$)
   - Zeile mit $("NULL", "NULL")$ = Gesamttotal
4. NULL in einer Spalte bedeutet: "diese Dimension wurde aggregiert"

*Beispiel:* Verkäufe nach Jahr und Monat mit Jahrestotals:
```sql
SELECT year, month, COUNT(*) AS verkauefe
FROM fact_sales
JOIN dim_time ON fact_sales.time_id = dim_time.time_id
GROUP BY ROLLUP(year, month)
ORDER BY year, month;
```
Ergebnis: Zeilen (2015, Jan, 50), (2015, Feb, 30), ..., (2015, NULL, 480), (NULL, NULL, 950)
]

*Äquivalenz:* `GROUP BY ROLLUP(A, B)` entspricht:
```sql
GROUP BY GROUPING SETS ((A, B), (A), ())
```

==== 5.3 GROUP BY CUBE

*Kernidee:* Berechnet Subtotals für *alle möglichen Kombinationen* der angegebenen Attribute — wie ROLLUP aber symmetrisch.

*Formel:* Bei $n$ Attributen gibt es $2^n$ Kombinationen (inklusive Gesamttotal):
$"CUBE"(A, B, C) arrow.r 2^3 = 8 "Kombinationen"$

Die Kombinationen für `CUBE(A, B, C)` sind:
$(A,B,C), (A,B), (A,C), (B,C), (A), (B), (C), ()$

#formula-box[
*Rezept: CUBE anwenden*

1. Bestimme welche Attribute *alle möglichen Kombinationen* von Subtotals brauchen
2. `GROUP BY CUBE(A, B, C)` — alle $2^n$ Kombinationen werden berechnet
3. Unterschied zu ROLLUP: CUBE erzeugt AUCH (B, NULL, NULL) und (NULL, C, NULL) — also Totals für B allein und C allein
4. Wann CUBE statt ROLLUP? Wenn keine natürliche Hierarchie zwischen den Dimensionen besteht

*Beispiel:* Verkäufe nach Subgenre und Geschlecht — mit Totals pro Subgenre, pro Geschlecht und Gesamttotal:
```sql
SELECT m.subgenre, c.gender, COUNT(*) AS anzahl
FROM fact_sales fs
JOIN dim_movie m ON fs.movie_id = m.movie_id
JOIN dim_customer c ON fs.cust_id = c.cust_id
GROUP BY CUBE(m.subgenre, c.gender)
ORDER BY 1, 2;
```
]

#cheat-box[
*ROLLUP vs. CUBE vs. GROUPING SETS — wann was?*

- *ROLLUP(A, B, C):* Hierarchische Aggregation (A > B > C), z.B. Jahr > Quartal > Monat. Erzeugt $n+1$ Gruppierungen.
- *CUBE(A, B, C):* Alle möglichen Kombinationen, keine Hierarchie. Erzeugt $2^n$ Gruppierungen.
- *GROUPING SETS(...):* Explizit aufgezählt welche Kombinationen gebraucht werden. Maximale Kontrolle.

Prüfungsfalle: Bei ROLLUP kommt z.B. (NULL, Jahr) NICHT vor — NULL steht immer an der Stelle des aggregierten "allgemeineren" Attributs.
]

==== 5.4 GROUP BY GROUPING SETS

*Kernidee:* Explizit angeben, welche Zwischensummen benötigt werden — maximale Flexibilität.

```sql
-- Nur Totals pro Modell und pro Jahr (kein Gesamttotal, keine Kombination):
GROUP BY GROUPING SETS (modell, jahr)

-- Entspricht ROLLUP(modell, jahr):
GROUP BY GROUPING SETS ((modell, jahr), modell, ())
```

==== 5.5 GROUPING()-Funktion

Gibt eine Bitmaske zurück, die anzeigt welche Attribute im aktuellen Gruppierungssatz *nicht* enthalten sind (= aggregiert wurden).

```sql
SELECT modell, jahr, SUM(anzahl), grouping(modell, jahr) AS g
FROM autoverkaeufe
GROUP BY ROLLUP(modell, jahr);
-- g=0: beide Attribute in Gruppe (normale Zeile)
-- g=1: nur modell in Gruppe (Jahr wurde aggregiert)
-- g=3: keine Attribute in Gruppe (Gesamttotal), 3 = binär 11
```

#warn-box[
*Häufiger Fehler: NULL-Bedeutung verwechseln*

NULL in einer Aggregationsspalte bedeutet NICHT "kein Wert" — es bedeutet "diese Dimension wurde zu einer Gesamtsumme aggregiert" (ALL). Um echte NULLs von Aggregations-NULLs zu unterscheiden: `GROUPING(col)` verwenden.
]

---

=== 6. Pivot-Tabellen

*Kernidee:* Zeilen in Spalten umwandeln — Werte einer Spalte werden zu eigenen Spalten mit aggregierten Werten.

==== 6.1 Mit FILTER-Klausel (SQL:2003)

```sql
SELECT modell,
  SUM(anzahl) FILTER (WHERE jahr = 1990) AS "1990",
  SUM(anzahl) FILTER (WHERE jahr = 1991) AS "1991",
  SUM(anzahl) FILTER (WHERE jahr = 1992) AS "1992"
FROM autoverkaeufe
GROUP BY modell;
```

*Problem:* Statisches Pivot — alle Spaltenwerte müssen manuell aufgezählt werden.

==== 6.2 Mit PostgreSQL crosstab

```sql
-- Extension einmalig installieren:
CREATE EXTENSION tablefunc;

-- Pivot-Abfrage:
SELECT *
FROM crosstab(
  'SELECT modell, jahr, SUM(anzahl)
   FROM autoverkaeufe
   GROUP BY modell, jahr ORDER BY 1,2',
  'SELECT DISTINCT jahr FROM autoverkaeufe ORDER BY 1'
) AS tmp(modell text, "1990" int, "1991" int, "1992" int);
```

#warn-box[
*Achtung bei PostgreSQL crosstab:* Die Spaltennamen im `AS tmp(...)` müssen manuell angegeben werden (statisches Pivot). Für dynamisches Pivot braucht man andere Techniken (z.B. JSON, dynamisches SQL).
]

==== 6.3 Mit CASE (universell, alle DBMS)

```sql
SELECT modell,
  SUM(CASE WHEN jahr = 1990 THEN anzahl ELSE 0 END) AS "1990",
  SUM(CASE WHEN jahr = 1991 THEN anzahl ELSE 0 END) AS "1991"
FROM autoverkaeufe
GROUP BY modell;
```

---

=== 7. Data Marts und Materialisierungs-Hierarchie

*Kernidee:* Ein Data Mart ist eine spezialisierte, vorberechnete Teilmenge des DW für eine bestimmte Abteilung oder Analyse — kleiner, schneller, optimierter.

==== Materialisierungs-Hierarchie (Lattice/Verband)

Zeigt welche vorberechneten Aggregate wiederverwendet werden können:

```
{ Modell, Jahr, Farbe }
    /        |        \
{Modell,Jahr} {Modell,Farbe} {Jahr,Farbe}
    |     \   /    |    \   /     |
{Modell}  {Jahr}        {Farbe}
        \     |      /
             { }
```

*Regel:* Teilaggregat $T$ ist wiederverwendbar für Aggregation $A$, wenn ein gerichteter Pfad von $T$ nach $A$ existiert (d.h. $A$ ist allgemeiner als $T$).

*Beispiel:* `{Modell, Jahr}` kann zur Berechnung von `{Modell}` und `{}` wiederverwendet werden — aber NICHT für `{Jahr, Farbe}`.

---

=== 8. Data Cube (OLAP Cube)

*Kernidee:* Mehrdimensionale Datenstruktur mit vorberechneten Aggregaten auf allen Hierarchieebenen aller Dimensionen — optimal für interaktive OLAP-Analysen.

==== Bestandteile eines Cubes

- *Measures (Fakten):* Numerische Kennzahlen (Umsatz, Kosten, Gewinn). Oft eigene Dimension ("Kennzahlen-Dimension")
- *Dimensionen:* Beschreibende Achsen (Zeit, Produkt, Region). Jede Dimension hat Hierarchien.
- *Hierarchien:* z.B. Tag $arrow.r$ Woche $arrow.r$ Monat $arrow.r$ Quartal $arrow.r$ Jahr
- *Members (Ausprägungen):* Konkrete Werte einer Dimension (z.B. "Januar", "Merlot")
- *Zellen:* Schnittpunkt aller Dimensionen = ein Messwert

==== OLAP-Operationen auf dem Cube

#cheat-box[
*OLAP-Operationen — wann welche?*

- *Drill-Down:* Detailierungsgrad erhöhen, z.B. von Quartalen zu Monaten. "Zoom in."
- *Roll-Up:* Detailierungsgrad verringern, z.B. von Monaten zu Quartalen. "Zoom out."
- *Slice:* Eine Dimension auf einen Wert fixieren, z.B. nur Region = "Schweiz". Gibt 2D-Querschnitt.
- *Dice:* Mehrere Dimensionen einschränken, z.B. Region IN ('CH', 'D') AND Zeit = Q1. Gibt Sub-Cube.
- *Pivot (Rotate):* Achsen austauschen, Zeilen und Spalten vertauschen.
]

==== Cube-Dimensionalität

- *0D Cube:* Ein Punkt (Gesamtsumme)
- *1D Cube:* Eine Linie (GROUP BY eine Dimension)
- *2D Cube:* Kreuztabelle (GROUP BY zwei Dimensionen)
- *3D Cube:* Würfel (GROUP BY drei Dimensionen)

*Abfragesprache:* MDX (Multidimensional Expressions, proprietär von Microsoft) — Alternative zu SQL für Cube-Abfragen.

---

=== 9. Analytische Funktionen (Window Functions)

*Kernidee:* Window-Funktionen berechnen einen Wert pro Zeile basierend auf einer "Fenstermenge" anderer Zeilen — ohne die Ergebnismenge zu reduzieren (im Gegensatz zu GROUP BY).

*Syntax-Grundstruktur:*

```sql
FUNKTION() OVER (
  [PARTITION BY col1, col2]  -- Gruppen definieren
  [ORDER BY col3]            -- Reihenfolge innerhalb Partition
  [ROWS/RANGE BETWEEN ...]   -- Fenstergrösse einschränken
)
```

==== 9.1 Ranking-Funktionen

```sql
SELECT name, salaer,
  ROW_NUMBER() OVER (ORDER BY salaer DESC) AS nr,    -- immer eindeutig
  RANK()       OVER (ORDER BY salaer DESC) AS rank,  -- Lücken bei Gleich
  DENSE_RANK() OVER (ORDER BY salaer DESC) AS drank, -- keine Lücken
  NTILE(4)     OVER (ORDER BY salaer DESC) AS quartil -- in N Gruppen
FROM angestellter;
```

#cheat-box[
*RANK vs. DENSE_RANK vs. ROW_NUMBER:*

Bei Gehältern 5000, 4000, 4000, 3000:
- `RANK`: 1, 2, 2, 4 (Lücke nach Gleichstand)
- `DENSE_RANK`: 1, 2, 2, 3 (keine Lücke)
- `ROW_NUMBER`: 1, 2, 3, 4 (immer eindeutig)
]

#formula-box[
*Rezept: Top-N-Abfrage mit RANK()*

1. CTE erstellen der die Ränge berechnet
2. Äussere Abfrage filtert auf `rang <= N`

```sql
WITH ranking AS (
  SELECT name, SUM(sales_amount) AS umsatz,
    RANK() OVER (ORDER BY SUM(sales_amount) DESC) AS rang
  FROM fact_sales
  JOIN dim_customer ON fact_sales.cust_id = dim_customer.cust_id
  GROUP BY name
)
SELECT * FROM ranking WHERE rang <= 3;
```
]

==== 9.2 PARTITION BY — Rang innerhalb Gruppen

```sql
SELECT abtnr, name, salaer,
  SUM(salaer) OVER (PARTITION BY abtnr) AS abt_total,
  RANK() OVER (PARTITION BY abtnr ORDER BY salaer DESC) AS rang_in_abt
FROM angestellter;
```

*Unterschied GROUP BY vs. PARTITION BY:*
- `GROUP BY`: gibt *ein Ergebnistupel pro Gruppe* (reduziert Zeilen)
- `PARTITION BY`: gibt *ein Ergebnistupel pro Originalzeile* (Zeilen bleiben erhalten, Wert aus Fenster wird angehängt)

==== 9.3 Year-to-Date (YTD)

```sql
SELECT year, month, SUM(sales_amount) AS betrag,
  SUM(SUM(sales_amount)) OVER (
    PARTITION BY year
    ORDER BY month
  ) AS ytd
FROM fact_sales
JOIN dim_time ON fact_sales.time_id = dim_time.time_id
GROUP BY year, month;
```

*Beachte:* `SUM(SUM(...))` — die innere SUM ist die Aggregation des GROUP BY, die äussere SUM ist die Window-Funktion die kumuliert.

==== 9.4 Moving Average (gleitender Durchschnitt)

```sql
SELECT monat, SUM(sales_amount) AS betrag,
  ROUND(AVG(SUM(sales_amount)) OVER (
    ORDER BY monat
    ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
  ), 0) AS moving_avg_3
FROM fact_sales
JOIN dim_time ON ...
GROUP BY monat;
```

*`ROWS BETWEEN 2 PRECEDING AND CURRENT ROW`* = die aktuelle Zeile plus die 2 vorherigen