// Auto-generated by RAG system on 2026-05-09
// Week 1 — do not edit the header

#import "../../template.typ": tip-box, warn-box, formula-box, cheat-box

== Woche 1: Business Intelligence & Data Visualization

=== 1. Datenkompetenz (Data Literacy)

*Kernidee:* Datenkompetenz ist die Fähigkeit, Daten kritisch zu sammeln, zu managen, zu bewerten und anzuwenden — nicht als Selbstzweck, sondern für konkrete Entscheidungen.

Die vier Leitfragen der Datenkompetenz:

#tip-box[
*Woran erkenne ich Datenkompetenz-Fragen in der Prüfung?*
Aufgaben die fragen "Darf man diesen Datensatz verwenden?" oder "Was will man mit diesen Daten erreichen?" testen Datenkompetenz.

- *Was will ich?* → Ziel definieren (konkrete Anwendung, nicht Daten um ihrer selbst willen)
- *Was kann ich?* → Datenquellen, Qualität, technische Möglichkeiten und Grenzen prüfen
- *Was darf ich?* → Datenschutz, Urheberrecht, Lizenzfragen klären (z.B. OPEN-BY-ASK beim BfS: freie Nutzung, Quellenangabe Pflicht, kommerzielle Nutzung nur mit Bewilligung)
- *Was soll ich?* → Ethischer Anspruch: Daten zum Wohl von Individuen und Gesellschaft nutzen
]

=== 2. Datentypen und Skalenniveaus

*Kernidee:* Jedes Datenmerkmal hat ein Skalenniveau — dieses bestimmt, welche Analysen und Visualisierungen zulässig und sinnvoll sind.

==== Oberste Ebene: Qualitativ vs. Quantitativ

#cheat-box[
*Qualitativ (kategorisch):* Beschreibt Eigenschaften, nicht messbare Mengen. Meist Text, kann aber numerisch codiert sein.
- Beispiele: Augenfarbe, Autotyp, Ja/Nein-Antworten, Farbe eines Regals

*Quantitativ:* Beschreibt zählbare/messbare Mengen. Immer numerisch.
- Beispiele: Entfernung, Geschwindigkeit, Höhe (100 cm), Anzahl Objekte (10 Stück)

*Merkhilfe Quiz:* "Ein Regal hat 10 Objekte (quantitativ) und ist rot (qualitativ)."
]

==== Die vier Skalenniveaus — Merkkürzel "N-O-I-R"

#formula-box[
*N-O-I-R: Die vier Skalenniveaus*

*1. Nominal* — "ein Name, etwas Benanntes"
- Nur Kategorien, keine Reihenfolge, kein Abstand, kein Nullpunkt
- Erlaubte Operationen: Gleich / Ungleich ($=$, $!=$ )
- Datentyp: meist Text
- Beispiele: Augenfarbe (blau, grün, braun), Geschlecht, Postleitzahl als Kategorie, Automarke

*2. Ordinal* — "eine Ordnung, ein Rang"
- Kategorien mit sinnvoller Reihenfolge, aber Abstände nicht bedeutsam
- Erlaubte Operationen: Gleich / Ungleich + Größer/Kleiner ($<$, $>$)
- Datentyp: meist Ganzzahl oder Text mit Rang
- Beispiele: Schulnoten (1–6), Zufriedenheitsskala (sehr gut / gut / mittel / schlecht), Militärränge, Platziergungen

*3. Intervall* — "ein Maßstab, etwas Relatives"
- Geordnete Werte mit gleichmäßigen, bedeutsamen Abständen, aber _kein_ absoluter Nullpunkt
- Erlaubte Operationen: +, $-$ (Differenzen sinnvoll), aber _keine_ Verhältnisse
- Datentyp: meist Fließ- oder Festkommazahl
- Beispiele: Temperatur in °C oder °F (0°C ist nicht "keine Temperatur"), Jahreszahlen, IQ-Werte

*4. Ratio (Verhältnis)* — "ein absoluter Nullpunkt"
- Wie Intervall, aber mit absolutem Nullpunkt → Verhältnisse sinnvoll ("doppelt so schwer")
- Erlaubte Operationen: +, $-$, $times$, $div$ (alle arithmetischen Operationen)
- Datentyp: meist Fließ- oder Festkommazahl
- Beispiele: Gewicht, Länge, Entfernung, Temperatur in Kelvin, Bevölkerungszahl, Einkommen

*Hierarchie:* Ratio $supset$ Intervall $supset$ Ordinal $supset$ Nominal
(jede höhere Skala enthält alle Eigenschaften der niedrigeren)
]

#warn-box[
*Häufige Verwechslungen:*
- Postleitzahlen sind *Nominal*, nicht Ratio — obwohl sie Zahlen sind, hat "8000 + 1 = 8001" keine sinnvolle Bedeutung
- Jahreszahlen sind *Intervall*, nicht Ratio — das Jahr 0 ist kein absoluter Nullpunkt; "2024 ist doppelt so groß wie 1012" ist sinnlos
- Schulnoten sind *Ordinal*, nicht Intervall — der Abstand zwischen Note 1 und 2 ist nicht zwingend gleich dem Abstand zwischen 5 und 6
- Temperaturen in °C sind *Intervall* (0°C = kein Nullpunkt), in Kelvin sind sie *Ratio* (0 K = absoluter Nullpunkt)
]

#tip-box[
*Schnell-Test: Welches Skalenniveau?*

Frage 1: Kann man sinnvoll sortieren/vergleichen? → Nein → *Nominal*

Frage 2 (wenn Ja): Sind die Abstände zwischen Werten bedeutsam und gleichmäßig? → Nein → *Ordinal*

Frage 3 (wenn Ja): Gibt es einen absoluten Nullpunkt (= "nichts davon")? → Nein → *Intervall*; Ja → *Ratio*
]

=== 3. Business Intelligence (BI) und Decision Support Systems (DSS)

*Kernidee:* BI-Tools helfen Unternehmen, Rohdaten in handlungsleitende Erkenntnisse umzuwandeln; DSS stellen die Methoden bereit, um auf Basis dieser Erkenntnisse Entscheidungen zu treffen.

==== BI-Tools vs. DSS

#cheat-box[
*Business Intelligence (BI) Tools:*
- Sammeln, analysieren und visualisieren Daten
- Umfassen: Data Warehousing, Data Mining, Reporting, Dashboards
- Liefern die _Grundlage_ für Entscheidungen (Was ist passiert? Was ist der Ist-Zustand?)
- Bekannte Tools: Tableau, Microsoft PowerBI, Looker (Google Data Studio), Apache Superset (Open Source), Oracle Analytics, Datawrapper

*Decision Support Systems (DSS):*
- Computergestützte Systeme mit Methoden zur Entscheidungsunterstützung
- Helfen Entscheidungsträgern, bessere und fundiertere Entscheidungen zu treffen
- Fokus auf Analyse des Ist-Zustands und zurückblickende Analyse

*Unterschied:* BI liefert _Daten und Erkenntnisse_; DSS liefert _Werkzeuge und Methoden_ für die Entscheidung selbst.
]

==== Methoden von DSS

#cheat-box[
*Drei Hauptmethoden:*

1. *Datenbankansatz* (inkl. Visualisierung):
   - Benutzer konsultieren → konzeptionelles Modell entwickeln → logisches Modell implementieren → erneut konsultieren (iterativ)

2. *Data-Mining-Ansatz:*
   - Lerndatensatz wählen → Modell erstellen → Testdatensatz wählen → Modellgüte berechnen

3. *Informationsbeschaffungsansatz:*
   - Benutzer nach Relevanz befragen → Relevanz durch Retrieval-Algorithmus modellieren → Ergebnisse vergleichen (Recall, Präzision)
]

==== Gemeinsame Funktionen von BI-Tools

Alle BI-Tools bieten typischerweise:
- *Analysieren:* Daten selektieren, filtern, aufbereiten
- *Visualisieren:* Listen, interaktive Diagramme, Karten
- *Präsentieren:* Cockpits / Dashboards zusammenstellen
- *Publizieren:* Dashboards über das Web teilen
- Dazu: Benutzerverwaltung

==== Evolution von BI

Die Entwicklung verlief grob: 1990er → BI Reporting / OLAP / Data Warehouses → 2000er → Interactive BI / In-Memory → 2010er → Big Data (Batch & Real-Time), Graph Databases

=== 4. Data Visualization (DataViz)

==== DataViz vs. InfoViz

#cheat-box[
*DataViz* = Daten grafisch darstellen, damit Menschen Muster schneller erkennen — gute grafische Kodierung (Diagramme, Karten für Analyse oder Kommunikation)

*InfoViz (InfoVis)* = DataViz + interaktive Systeme: menschliche Wahrnehmung/Kognition, UI/UX-Design, Interaktionstechniken, Evaluation, Datenperspektiven

*Merksatz:* DataViz = gute grafische Kodierung; InfoVis = gute grafische Kodierung _plus_ Interaktion, UI/UX, Kognition als System
]

==== Datenperspektiven: What / When / Where / With whom

#tip-box[
*Woran erkenne ich, welche Perspektive gefragt ist?*

- *What? (thematisch):* Vergleiche zwischen Kategorien, Gruppen, Werten → Welche Kategorie ist größer? Wie verteilen sich Werte?
- *When? (temporal):* Zeitliche Entwicklung, Trends, Zeitreihen → Wie verändert sich etwas über die Zeit?
- *Where? (räumlich):* Werte auf Karten, geografische Muster, Hotspots → Wo tritt etwas auf?
- *With whom? (Netzwerk):* Beziehungen und Flüsse zwischen Akteuren/Objekten → Wer hängt mit wem zusammen?
]

==== Warum Visualisierung wichtig ist

- Menschen sind *schlecht* im Vergleich von Zahlen, aber *gut* im Erkennen grafischer Muster
- Visualisierung ist nicht nur Veranschaulichung, sondern ein eigenständiges *Analysewerkzeug*
- Häufig erkennt man Zusammenhänge in Daten erst durch geschickte Darstellung

==== Die Klassiker: Tufte und Bertin

*Edward Tufte* (1942–heute): Bekanntester Informationswissenschaftler/Grafikdesigner; Kernprinzip: maximale Informationsdichte bei minimaler grafischer "Tinte" (Data-Ink-Ratio).

*Jacques Bertin* (1918–2010): Französischer Kartograf; entwickelte die Theorie der *6 grafischen Variablen* (visuelle Variablen):

#cheat-box[
*Bertins 6 grafische Variablen* — ein Zeichen kann kodiert werden durch:
1. *Farbe* (Farbton / Hue)
2. *Form* (Shape)
3. *Muster* (Texture/Pattern)
4. *Helligkeit* (Value/Brightness)
5. *Richtung* (Orientation)
6. *Größe* (Size)

Je nach Skalenniveau empfiehlt Bertin unterschiedliche visuelle Variablen:
- Nominal → Farbe, Form, Muster (unterschiedlich, aber nicht geordnet)
- Ordinal → Helligkeit, Größe (hat eine natürliche Ordnung)
- Intervall/Ratio → Größe, Helligkeit (proportionale Abstände darstellbar)
]

=== 5. Die richtige Grafik wählen

==== Skalenniveau → empfohlene Diagrammtypen

#formula-box[
*Rezept: Diagrammtyp aus Skalenniveau ableiten*

*Schritt 1:* Bestimme das Skalenniveau der relevanten Variablen (N-O-I-R)

*Schritt 2:* Bestimme die Botschaft / den Nachrichtentyp (siehe Stephen Few)

*Schritt 3:* Wähle den passenden Diagrammtyp:

| Skalenniveau | Business Charts | Karten |
|---|---|---|
| *Nominal* | Torten-, Balkendiagramme | Dot map, Network map, Colored area map |
| *Ordinal* | Gestapelte Balken, Punktdiagramme | Symbol map, Ordered network map, Ordered colored map |
| *Intervall* | Liniendiagramme, Streudiagramme | Graduated symbol map, Flow map, Choropleth map |
| *Ratio* | Histogramme, Boxplots | (wie Intervall) |
]

==== Die 7 quantitativen Nachrichtentypen (Stephen Few, 2004)

#cheat-box[
*Wenn die Botschaft ist... → dann nimm...*

1. *Nominaler Vergleich* (Kategorien vergleichen ohne Reihenfolge) → *Bar Chart* (horizontal oder vertikal)
2. *Zeitserie* (Entwicklung über Zeit) → *Liniendiagramm* (horizontal)
3. *Rangfolge* (geordnete Liste) → *Balkendiagramm* (horizontal)
4. *Teil-zu-Ganzes* (Anteile am Ganzen) → *Bar Chart* (horizontal oder vertikal)
5. *Abweichung* (Differenz von einem Referenzwert) → *Bar Chart* (horizontal oder vertikal)
6. *Häufigkeitsverteilung* (wie oft tritt ein Wert auf) → *Bar Chart* (horizontal)
7. *Korrelation* (Zusammenhang zwischen zwei Variablen) → *Scatter Plot*
]

#warn-box[
*Häufige Fehler bei der Diagrammwahl:*

- *Liniendiagramm statt XY-Streudiagramm für Zeitreihen mit unregelmäßigen Abständen:* Ein normales Liniendiagramm verteilt alle Datenpunkte gleichmäßig auf der X-Achse — auch wenn die Zeitabstände ungleich sind! Das führt zu irreführenden Steigungen. Lösung: XY-Streudiagramm (Scatter Plot) mit Linien verwenden, dann entsprechen die horizontalen Abstände den echten Zeitabständen.

- *Tortendiagramm für zu viele Kategorien:* Mehr als 5–6 Segmente sind schwer lesbar. Besser: Balkendiagramm.

- *Defaults der Office-Programme blind übernehmen:* Excel/LibreOffice schlagen oft nicht den optimalen Diagrammtyp vor. Immer selbst nachdenken!

- *3D-Diagramme:* Fast immer irreführend, da perspektivische Verzerrung die Werte verändert.
]

#tip-box[
*Entscheidungsbaum: Scatter Plot vs. Liniendiagramm bei Zeitreihen*

Frage: Sind die Zeitabstände zwischen den Messpunkten *gleichmäßig*?
- Ja → Liniendiagramm akzeptabel
- Nein (z.B. Daten von 1950, 1960, 1970... aber auch 1975) → *XY-Streudiagramm mit Linien* verwenden!

Begründung: Nur der Scatter Plot mappt die X-Position proportional zum tatsächlichen Zeitwert.
]

=== 6. Praktisches Rezept: Business Chart erstellen (Übung 1)

#formula-box[
*Allgemeines Rezept: Zeitreihen-Diagramm in LibreOffice / Excel erstellen*

*Schritt 1: Datei öffnen und relevante Daten identifizieren*
- Welche Zeile/Spalte enthält die X-Achsen-Variable (z.B. Jahres­zahlen)?
- Welche Zeile(n)/Spalte(n) enthalten die Y-Werte (z.B. Bevölkerungszahlen)?
- Beschriftungen (Labels) notieren

*Schritt 2: Daten auswählen*
- In LibreOffice: Ctrl+Klick auf Zeilennummern für mehrere nicht-benachbarte Zeilen
- Beschriftungsspalte/-zeile mit einschließen

*Schritt 3: Diagramm einfügen*
- Menü: Einfügen → Diagramm...

*Schritt 4: Richtigen Diagrammtyp wählen*
- Für Zeitreihen mit ungleichen Abständen: *XY (Streudiagramm)* → Variante "Punkte und Linien" oder "Nur Linien"
- Für Zeitreihen mit gleichen Abständen: Liniendiagramm möglich

*Schritt 5: Datenbereich konfigurieren*
- "Datenreihen in Zeilen" anwählen (wenn Daten zeilenweise angeordnet)
- "Erste Zeile als Beschriftung" anwählen
- "Erste Spalte als Beschriftung" anwählen

*Schritt 6: Fertigstellen und optimieren*
- Achsenbeschriftungen prüfen (Einheiten angeben!)
- Diagramm strecken wenn nötig (Datenpunkte besser sichtbar)
- Legende prüfen (sind alle Datenreihen klar beschriftet?)

*Schritt 7: Diagrammwahl begründen*
- Warum dieser Typ? (z.B. "XY-Diagramm, weil die Zeitabstände ungleichmäßig sind und nur so die Steigungen korrekt dargestellt werden")

*Beispiel (Bevölkerungsdaten CH 1950–2024):*
- X-Achse: Jahreszahlen (Zeile 2) → ungleichmäßige Abstände → XY-Streudiagramm!
- Y-Achse 1: Ständige Wohnbevölkerung in 1'000 (Zeile 4)
- Y-Achse 2: Davon Ausländer in 1'000 (Zeile 5)
- Botschaft: Zeitserie → Liniendiagramm-Variante des XY-Diagramms
]

#tip-box[
*Woran erkenne ich, welcher Diagrammtyp in der Aufgabe gefragt ist?*

- Aufgabe nennt "zeitliche Entwicklung" / "Trend" / "über die Jahre" → *Zeitserie* → Liniendiagramm oder XY-Scatter mit Linien
- Aufgabe nennt "Vergleich zwischen Kategorien" → *Nominaler Vergleich* → Bar Chart
- Aufgabe nennt "Anteile" / "Prozent von Gesamt" → *Teil-zu-Ganzes* → Bar Chart (oder Pie Chart bei wenigen Kategorien)
- Aufgabe nennt "Zusammenhang zwischen zwei numerischen Variablen" → *Korrelation* → Scatter Plot
- Aufgabe nennt "Häufigkeit" / "wie oft" → *Verteilung* → Histogramm / Bar Chart
]

=== 7. Apache Superset — BI-Tool Grundlagen (Übung 2 & 3)

*Kernidee:* Apache Superset ist ein Open-Source-BI-Tool, das den kompletten Workflow von Datenquelle über Chart bis zum veröffentlichten Dashboard abdeckt.

#cheat-box[
*Workflow in Apache Superset:*

1. *Datenbankverbindung herstellen* (oder CSV hochladen)
2. *Dataset definieren* (Tabelle/View aus der Datenbank auswählen)
3. *Chart erstellen:* Charttyp wählen → X-Achse / Y-Achse / Dimensionen konfigurieren → speichern
4. *Dashboard erstellen:* Charts zum Dashboard hinzufügen
5. *Dashboard publizieren:* Link teilen (Dashboard → Publish → Link kopieren)

*CSV-Upload:* Für eigene Datensätze (Aufgabe 3) muss die CSV-Datei zuerst in Superset hochgeladen werden (Datenbank-Upload-Funktion), bevor sie als Dataset verwendet werden kann.

*Wichtig beim CSV:* Trennzeichen (Komma / Semikolon), Zeichenkodierung (UTF-8), erste Zeile als Header sicherstellen.
]

=== 8. Zusammenfassung: Entscheidungsmatrix

#cheat-box[
*Wenn ich eine Aufgabe sehe die fragt...*

"Welches Skalenniveau?" → N-O-I-R-Test (sortierbar? gleichmäßige Abstände? absoluter Nullpunkt?)

"Welches Diagramm?" → Erst Botschaft bestimmen (Few's 7 Typen), dann Skalenniveau prüfen

"Warum XY-Streudiagramm statt Liniendiagramm?" → Ungleichmäßige Zeitabstände: XY mappt X-Position proportional zum echten Wert

"Darf ich diese Daten nutzen?" → Datenkompetenz-Check: Was will/kann/darf/soll ich?

"Was ist BI? Was ist DSS?" → BI = Daten & Erkenntnisse; DSS = Methoden & Werkzeuge für Entscheidungen; BI liefert Input für DSS
]